"""indices

Revision ID: 004ac48ffe18
Revises: 81c96876355a
Create Date: 2021-03-29 18:24:10.485482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004ac48ffe18'
down_revision = '81c96876355a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_index(op.f('ix_hourly_actuals_rh_valid'), 'hourly_actuals', ['rh_valid'], unique=False)
    op.create_index(op.f('ix_hourly_actuals_station_code'), 'hourly_actuals', ['station_code'], unique=False)
    op.create_index(op.f('ix_hourly_actuals_temp_valid'), 'hourly_actuals', ['temp_valid'], unique=False)
    op.create_index(op.f('ix_hourly_actuals_weather_date'), 'hourly_actuals', ['weather_date'], unique=False)
    op.create_index(op.f('ix_model_run_grid_subset_predictions_prediction_model_grid_subset_id'),
                    'model_run_grid_subset_predictions', ['prediction_model_grid_subset_id'], unique=False)
    op.create_index(op.f('ix_model_run_grid_subset_predictions_prediction_model_run_timestamp_id'),
                    'model_run_grid_subset_predictions', ['prediction_model_run_timestamp_id'], unique=False)
    op.create_index(op.f('ix_model_run_grid_subset_predictions_prediction_timestamp'),
                    'model_run_grid_subset_predictions', ['prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_noon_forecasts_created_at'), 'noon_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_noon_forecasts_station_code'), 'noon_forecasts', ['station_code'], unique=False)
    op.create_index(op.f('ix_noon_forecasts_weather_date'), 'noon_forecasts', ['weather_date'], unique=False)
    op.create_index(op.f('ix_prediction_model_grid_subsets_prediction_model_id'),
                    'prediction_model_grid_subsets', ['prediction_model_id'], unique=False)
    op.create_index(op.f('ix_prediction_model_run_timestamps_prediction_model_id'),
                    'prediction_model_run_timestamps', ['prediction_model_id'], unique=False)
    op.create_index(op.f('ix_prediction_model_run_timestamps_prediction_run_timestamp'),
                    'prediction_model_run_timestamps', ['prediction_run_timestamp'], unique=False)
    op.create_index(op.f('ix_prediction_models_abbreviation'),
                    'prediction_models', ['abbreviation'], unique=False)
    op.drop_constraint('processed_model_run_files_url_key', 'processed_model_run_urls', type_='unique')
    op.create_index(op.f('ix_processed_model_run_urls_url'), 'processed_model_run_urls', ['url'], unique=True)
    op.create_index(op.f('ix_weather_station_model_predictions_prediction_model_run_timestamp_id'),
                    'weather_station_model_predictions', ['prediction_model_run_timestamp_id'], unique=False)
    op.create_index(op.f('ix_weather_station_model_predictions_prediction_timestamp'),
                    'weather_station_model_predictions', ['prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_weather_station_model_predictions_station_code'),
                    'weather_station_model_predictions', ['station_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_weather_station_model_predictions_station_code'),
                  table_name='weather_station_model_predictions')
    op.drop_index(op.f('ix_weather_station_model_predictions_prediction_timestamp'),
                  table_name='weather_station_model_predictions')
    op.drop_index(op.f('ix_weather_station_model_predictions_prediction_model_run_timestamp_id'),
                  table_name='weather_station_model_predictions')
    op.drop_index(op.f('ix_processed_model_run_urls_url'), table_name='processed_model_run_urls')
    op.create_unique_constraint('processed_model_run_files_url_key', 'processed_model_run_urls', ['url'])
    op.drop_index(op.f('ix_prediction_models_abbreviation'), table_name='prediction_models')
    op.drop_index(op.f('ix_prediction_model_run_timestamps_prediction_run_timestamp'),
                  table_name='prediction_model_run_timestamps')
    op.drop_index(op.f('ix_prediction_model_run_timestamps_prediction_model_id'),
                  table_name='prediction_model_run_timestamps')
    op.drop_index(op.f('ix_prediction_model_grid_subsets_prediction_model_id'),
                  table_name='prediction_model_grid_subsets')
    op.drop_index(op.f('ix_noon_forecasts_weather_date'), table_name='noon_forecasts')
    op.drop_index(op.f('ix_noon_forecasts_station_code'), table_name='noon_forecasts')
    op.drop_index(op.f('ix_noon_forecasts_created_at'), table_name='noon_forecasts')
    op.drop_index(op.f('ix_model_run_grid_subset_predictions_prediction_timestamp'),
                  table_name='model_run_grid_subset_predictions')
    op.drop_index(op.f('ix_model_run_grid_subset_predictions_prediction_model_run_timestamp_id'),
                  table_name='model_run_grid_subset_predictions')
    op.drop_index(op.f('ix_model_run_grid_subset_predictions_prediction_model_grid_subset_id'),
                  table_name='model_run_grid_subset_predictions')
    op.drop_index(op.f('ix_hourly_actuals_weather_date'), table_name='hourly_actuals')
    op.drop_index(op.f('ix_hourly_actuals_temp_valid'), table_name='hourly_actuals')
    op.drop_index(op.f('ix_hourly_actuals_station_code'), table_name='hourly_actuals')
    op.drop_index(op.f('ix_hourly_actuals_rh_valid'), table_name='hourly_actuals')
    # ### end Alembic commands ###
