"""warn-advisory-one-record

Revision ID: 0f9913be0033
Revises: 52a8664e0681
Create Date: 2022-12-08 14:44:51.297445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f9913be0033'
down_revision = '52a8664e0681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('high_hfi_area', sa.Column('advisory_area', sa.Float(), nullable=False))
    op.add_column('high_hfi_area', sa.Column('warn_area', sa.Float(), nullable=False))
    op.drop_index('ix_high_hfi_area_threshold', table_name='high_hfi_area')
    op.drop_constraint('high_hfi_area_threshold_fkey', 'high_hfi_area', type_='foreignkey')
    op.drop_column('high_hfi_area', 'area')
    op.drop_column('high_hfi_area', 'threshold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('high_hfi_area', sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('high_hfi_area', sa.Column('area', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key('high_hfi_area_threshold_fkey', 'high_hfi_area', 'advisory_hfi_classification_threshold', ['threshold'], ['id'])
    op.create_index('ix_high_hfi_area_threshold', 'high_hfi_area', ['threshold'], unique=False)
    op.drop_column('high_hfi_area', 'warn_area')
    op.drop_column('high_hfi_area', 'advisory_area')
    # ### end Alembic commands ###
