"""Add nullable daily UUID to morecast2 table

Revision ID: 2140341e63f0
Revises: 2169aa76dfea
Create Date: 2023-05-23 16:08:47.534835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2140341e63f0'
down_revision = '2169aa76dfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('morecast_forecast', sa.Column('wf1_daily_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('morecast_forecast', 'wf1_daily_id')
    # ### end Alembic commands ###
