"""add column to min win speed threshold table

Revision ID: 395caeeeaf77
Revises: 08799237842e
Create Date: 2025-03-18 10:31:43.997506

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '395caeeeaf77'
down_revision = '08799237842e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('advisory_hfi_wind_speed', sa.Column('threshold_temp', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_advisory_hfi_wind_speed_threshold_temp'), 'advisory_hfi_wind_speed', ['threshold_temp'], unique=False)
    op.create_foreign_key(None, 'advisory_hfi_wind_speed', 'advisory_hfi_classification_threshold', ['threshold_temp'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'advisory_hfi_wind_speed', type_='foreignkey')
    op.drop_index(op.f('ix_advisory_hfi_wind_speed_threshold_temp'), table_name='advisory_hfi_wind_speed')
    op.drop_column('advisory_hfi_wind_speed', 'threshold_temp')
    # ### end Alembic commands ###
