"""Processed snow

Revision ID: 403586c146ae
Revises: 7cd069b79aaa
Create Date: 2024-01-15 11:05:24.330674

"""
from alembic import op
import sqlalchemy as sa
from wps_shared.db.models.common import TZTimeStamp

# revision identifiers, used by Alembic.
revision = '403586c146ae'
down_revision = '7cd069b79aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('processed_snow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('for_date', TZTimeStamp(), nullable=False),
    sa.Column('processed_date', TZTimeStamp(), nullable=False),
    sa.Column('snow_source', sa.Enum('viirs', name='snowsourceenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Record containing information about processed snow coverage data.'
    )
    op.create_index(op.f('ix_processed_snow_for_date'), 'processed_snow', ['for_date'], unique=False)
    op.create_index(op.f('ix_processed_snow_id'), 'processed_snow', ['id'], unique=False)
    op.create_index(op.f('ix_processed_snow_processed_date'), 'processed_snow', ['processed_date'], unique=False)
    op.create_index(op.f('ix_processed_snow_snow_source'), 'processed_snow', ['snow_source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_processed_snow_snow_source'), table_name='processed_snow')
    op.drop_index(op.f('ix_processed_snow_processed_date'), table_name='processed_snow')
    op.drop_index(op.f('ix_processed_snow_id'), table_name='processed_snow')
    op.drop_index(op.f('ix_processed_snow_for_date'), table_name='processed_snow')
    op.drop_table('processed_snow')
    # ### end Alembic commands ###
