"""Add is_deleted and audit cols to planning_weather_stations

Revision ID: 41ec381bf3ee
Revises: 52c8a568364e
Create Date: 2022-06-16 14:30:58.981268

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ec381bf3ee'
down_revision = 'b99dce009b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('planning_weather_stations', sa.Column('create_user', sa.String(), nullable=True))
    op.add_column('planning_weather_stations', sa.Column(
        'create_timestamp', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('planning_weather_stations', sa.Column('update_user', sa.String(), nullable=True))
    op.add_column('planning_weather_stations', sa.Column(
        'update_timestamp', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('planning_weather_stations', sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False))
    op.create_index(op.f('ix_planning_weather_stations_create_timestamp'),
                    'planning_weather_stations', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_planning_weather_stations_update_timestamp'),
                    'planning_weather_stations', ['update_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_planning_weather_stations_update_timestamp'), table_name='planning_weather_stations')
    op.drop_index(op.f('ix_planning_weather_stations_create_timestamp'), table_name='planning_weather_stations')
    op.drop_column('planning_weather_stations', 'is_deleted')
    op.drop_column('planning_weather_stations', 'update_timestamp')
    op.drop_column('planning_weather_stations', 'update_user')
    op.drop_column('planning_weather_stations', 'create_timestamp')
    op.drop_column('planning_weather_stations', 'create_user')
    # ### end Alembic commands ###
