"""Add cols to advisory_shapes

Revision ID: 4765023976e0
Revises: fc2d4ff7398d
Create Date: 2022-09-06 17:38:06.263921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4765023976e0'
down_revision = 'fc2d4ff7398d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('advisory_shapes', sa.Column('combustible_area', sa.Float(), nullable=True))
    op.add_column('advisory_shapes', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('advisory_shapes', 'name')
    op.drop_column('advisory_shapes', 'combustible_area')
    # ### end Alembic commands ###
