"""high hfi area

Revision ID: 519649de934f
Revises: 7d240064d71a
Create Date: 2022-12-01 15:00:50.369825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '519649de934f'
down_revision = '7d240064d71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_parameters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('run_type', postgresql.ENUM(name='runtypeenum', create_type=False), nullable=False),
                    sa.Column('run_datetime', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('for_date', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('run_type', 'run_datetime', 'for_date'),
                    comment='A combination of run type, run datetime and for date.'
                    )
    op.create_index(op.f('ix_run_parameters_id'), 'run_parameters', ['id'], unique=False)
    op.create_table('high_hfi_area',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('advisory_shape_id', sa.Integer(), nullable=False),
                    sa.Column('run_parameters', sa.Integer(), nullable=False),
                    sa.Column('advisory_area', sa.Float(), nullable=False),
                    sa.Column('warn_area', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['advisory_shape_id'], ['advisory_shapes.id'], ),
                    sa.ForeignKeyConstraint(['run_parameters'], ['run_parameters.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Area under advisory/warning per fire zone.'
                    )
    op.create_index(op.f('ix_high_hfi_area_id'), 'high_hfi_area', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_high_hfi_area_id'), table_name='high_hfi_area')
    op.drop_table('high_hfi_area')
    op.drop_index(op.f('ix_run_parameters_id'), table_name='run_parameters')
    op.drop_table('run_parameters')
    # ### end Alembic commands ###
