"""store area by threshold

Revision ID: 52a8664e0681
Revises: 519649de934f
Create Date: 2022-12-06 11:33:35.467445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52a8664e0681'
down_revision = '519649de934f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('high_hfi_area', sa.Column('threshold', sa.Integer(), nullable=False))
    op.add_column('high_hfi_area', sa.Column('area', sa.Float(), nullable=False))
    op.create_index(op.f('ix_high_hfi_area_threshold'), 'high_hfi_area', ['threshold'], unique=False)
    op.create_foreign_key(None, 'high_hfi_area', 'advisory_hfi_classification_threshold', ['threshold'], ['id'])
    op.drop_column('high_hfi_area', 'warn_area')
    op.drop_column('high_hfi_area', 'advisory_area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('high_hfi_area', sa.Column('advisory_area', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('high_hfi_area', sa.Column('warn_area', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'high_hfi_area', type_='foreignkey')
    op.drop_index(op.f('ix_high_hfi_area_threshold'), table_name='high_hfi_area')
    op.drop_column('high_hfi_area', 'area')
    op.drop_column('high_hfi_area', 'threshold')
    # ### end Alembic commands ###
