"""adding rh

Revision ID: 5741da7c7902
Revises: 8c7f3d10fe9d
Create Date: 2020-09-17 15:06:43.327377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5741da7c7902'
down_revision = '8c7f3d10fe9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_station_model_predictions', sa.Column('bias_adjusted_rh', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_station_model_predictions', 'bias_adjusted_rh')
    # ### end Alembic commands ###
