"""Add station_code to ModelRunPrediction

Revision ID: 5b745fe0bd7a
Revises: 2442f07d975c
Create Date: 2023-10-25 11:34:45.429269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b745fe0bd7a'
down_revision = '2442f07d975c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_run_predictions', sa.Column('station_code', sa.Integer(), nullable=True))
    op.drop_constraint('model_run_predictions_prediction_model_run_timestamp_id_pre_key', 'model_run_predictions', type_='unique')
    op.create_unique_constraint(None, 'model_run_predictions', ['prediction_model_run_timestamp_id', 'prediction_timestamp', 'station_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_run_predictions', type_='unique')
    op.create_unique_constraint('model_run_predictions_prediction_model_run_timestamp_id_pre_key', 'model_run_predictions', ['prediction_model_run_timestamp_id', 'prediction_timestamp'])
    op.drop_column('model_run_predictions', 'station_code')
    # ### end Alembic commands ###
