"""chaines poly

Revision ID: 65ad8540f7d7
Revises: ad4f37763020
Create Date: 2021-01-15 16:08:15.876409

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '65ad8540f7d7'
down_revision = 'ad4f37763020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_model_c_haines_polygons',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON',
                                                                 from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                    sa.Column('severity', sa.Integer(), nullable=False),
                    sa.Column('prediction_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('model_run_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('prediction_model_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['prediction_model_id'], ['prediction_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_prediction_model_c_haines_polygons_id'),
                    'prediction_model_c_haines_polygons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_model_c_haines_polygons_id'),
                  table_name='prediction_model_c_haines_polygons')
    op.drop_table('prediction_model_c_haines_polygons')
    # ### end Alembic commands ###
