"""drop c-haines step b

Revision ID: 6d5a3c660f1a
Revises: 935bde11a18b
Create Date: 2021-06-10 11:07:26.198769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d5a3c660f1a'
down_revision = '935bde11a18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - and adjusted ###
    op.drop_index('ix_c_haines_predictions_id', table_name='c_haines_predictions')
    op.drop_index('ix_c_haines_predictions_model_run_id', table_name='c_haines_predictions')
    op.drop_table('c_haines_predictions')
    op.drop_index('ix_c_haines_model_runs_id', table_name='c_haines_model_runs')
    op.drop_index('ix_c_haines_model_runs_prediction_model_id', table_name='c_haines_model_runs')
    op.drop_table('c_haines_model_runs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - and adjusted ###
    op.create_table('c_haines_model_runs',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('c_haines_model_runs_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('model_run_timestamp', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('prediction_model_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['prediction_model_id'], ['prediction_models.id'],
                                            name='c_haines_model_runs_prediction_model_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='c_haines_model_runs_pkey'),
                    sa.UniqueConstraint('model_run_timestamp', 'prediction_model_id',
                                        name='c_haines_model_runs_model_run_timestamp_prediction_model_id_key'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index('ix_c_haines_model_runs_prediction_model_id',
                    'c_haines_model_runs', ['prediction_model_id'], unique=False)
    op.create_index('ix_c_haines_model_runs_id', 'c_haines_model_runs', ['id'], unique=False)
    op.create_table('c_haines_predictions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('prediction_timestamp', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('model_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['model_run_id'], ['c_haines_model_runs.id'],
                                            name='c_haines_predictions_model_run_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='c_haines_predictions_pkey'),
                    sa.UniqueConstraint('prediction_timestamp', 'model_run_id',
                                        name='c_haines_predictions_prediction_timestamp_model_run_id_key')
                    )
    op.create_index('ix_c_haines_predictions_model_run_id',
                    'c_haines_predictions', ['model_run_id'], unique=False)
    op.create_index('ix_c_haines_predictions_id', 'c_haines_predictions', ['id'], unique=False)
    # ### end Alembic commands ###
