"""advisory_shape_fuels and advisory_fuel_stats FK fix

Revision ID: 6f67d6d96750
Revises: 2cf10021c5f1
Create Date: 2025-02-28 15:00:56.897772

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6f67d6d96750"
down_revision = "2cf10021c5f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_unique_constraint("uq_sfms_fuel_types_fuel_type_id", "sfms_fuel_types", ["fuel_type_id"])

    op.drop_constraint("advisory_fuel_stats_fuel_type_fkey", "advisory_fuel_stats", type_="foreignkey")
    op.create_foreign_key(None, "advisory_fuel_stats", "sfms_fuel_types", ["fuel_type"], ["fuel_type_id"])
    op.drop_constraint("advisory_shape_fuels_fuel_type_fkey", "advisory_shape_fuels", type_="foreignkey")
    op.create_foreign_key(None, "advisory_shape_fuels", "sfms_fuel_types", ["fuel_type"], ["fuel_type_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_sfms_fuel_types_fuel_type_id", "sfms_fuel_types", type_="unique")

    op.drop_constraint(None, "advisory_shape_fuels", type_="foreignkey")
    op.create_foreign_key("advisory_shape_fuels_fuel_type_fkey", "advisory_shape_fuels", "sfms_fuel_types", ["fuel_type"], ["id"])
    op.drop_constraint(None, "advisory_fuel_stats", type_="foreignkey")
    op.create_foreign_key("advisory_fuel_stats_fuel_type_fkey", "advisory_fuel_stats", "sfms_fuel_types", ["fuel_type"], ["id"])

    # ### end Alembic commands ###
