"""morecast2 grass curing table

Revision ID: 730547c35fdb
Revises: f6400f2140b9
Create Date: 2023-08-22 14:05:29.302062

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '730547c35fdb'
down_revision = 'f6400f2140b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('morecast_grass_curing',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('station_code', sa.Integer(), nullable=False),
                    sa.Column('grass_curing', sa.Float(), nullable=False),
                    sa.Column('create_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('create_user', sa.String(), nullable=False),
                    sa.Column('update_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('update_user', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_morecast_grass_curing_create_timestamp'),
                    'morecast_grass_curing', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_morecast_grass_curing_grass_curing'),
                    'morecast_grass_curing', ['grass_curing'], unique=False)
    op.create_index(op.f('ix_morecast_grass_curing_id'), 'morecast_grass_curing', ['id'], unique=False)
    op.create_index(op.f('ix_morecast_grass_curing_station_code'),
                    'morecast_grass_curing', ['station_code'], unique=False)
    op.create_index(op.f('ix_morecast_grass_curing_update_timestamp'),
                    'morecast_grass_curing', ['update_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_morecast_grass_curing_update_timestamp'), table_name='morecast_grass_curing')
    op.drop_index(op.f('ix_morecast_grass_curing_station_code'), table_name='morecast_grass_curing')
    op.drop_index(op.f('ix_morecast_grass_curing_id'), table_name='morecast_grass_curing')
    op.drop_index(op.f('ix_morecast_grass_curing_grass_curing'), table_name='morecast_grass_curing')
    op.drop_index(op.f('ix_morecast_grass_curing_create_timestamp'), table_name='morecast_grass_curing')
    op.drop_table('morecast_grass_curing')
    # ### end Alembic commands ###
