"""high hfi area

Revision ID: 7886d378bc0b
Revises: 7d240064d71a
Create Date: 2022-11-29 13:31:34.025932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7886d378bc0b'
down_revision = '7d240064d71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_hfi_area',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source_identifier', sa.String(), nullable=False),
                    sa.Column('run_type', sa.Enum('forecast', 'actual', name='runtypeenum'), nullable=False),
                    sa.Column('run_datetime', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('for_date', sa.Date(), nullable=False),
                    sa.Column('advisory_area', sa.Float(), nullable=False),
                    sa.Column('warn_area', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['source_identifier'], ['advisory_shapes.source_identifier'], ),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Area under advisory/warning per fire zone.'
                    )
    op.create_index(op.f('ix_high_hfi_area_id'), 'high_hfi_area', ['id'], unique=False)
    op.create_index(op.f('ix_high_hfi_area_source_identifier'), 'high_hfi_area', ['source_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_high_hfi_area_source_identifier'), table_name='high_hfi_area')
    op.drop_index(op.f('ix_high_hfi_area_id'), table_name='high_hfi_area')
    op.drop_table('high_hfi_area')
    # ### end Alembic commands ###
