"""bias adjusted temperature and rh

Revision ID: 7bedf64b703c
Revises: c9f9b2849fef
Create Date: 2020-09-25 09:26:42.350014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bedf64b703c'
down_revision = 'c9f9b2849fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_station_model_predictions', sa.Column('bias_adjusted_rh', sa.Float(), nullable=True))
    op.add_column('weather_station_model_predictions', sa.Column('bias_adjusted_temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_station_model_predictions', 'bias_adjusted_temperature')
    op.drop_column('weather_station_model_predictions', 'bias_adjusted_rh')
    # ### end Alembic commands ###
