"""drop classification

Revision ID: 834f6cd90d69
Revises: fc2d4ff7398d
Create Date: 2022-09-07 14:54:29.674015

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '834f6cd90d69'
down_revision = 'fc2d4ff7398d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_advisory_classified_hfi_geom', table_name='advisory_classified_hfi')
    op.drop_index('ix_advisory_classified_hfi_id', table_name='advisory_classified_hfi')
    op.drop_table('advisory_classified_hfi')
    op.drop_index('ix_advisory_fire_zones_for_date', table_name='advisory_fire_zones')
    op.drop_index('ix_advisory_fire_zones_id', table_name='advisory_fire_zones')
    op.drop_index('ix_advisory_fire_zones_mof_fire_zone_id', table_name='advisory_fire_zones')
    op.drop_table('advisory_fire_zones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_fire_zones',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('mof_fire_zone_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('elevated_hfi_area', postgresql.DOUBLE_PRECISION(
                        precision=53), autoincrement=False, nullable=False),
                    sa.Column('elevated_hfi_percentage', postgresql.DOUBLE_PRECISION(
                        precision=53), autoincrement=False, nullable=False),
                    sa.Column('for_date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='advisory_fire_zones_pkey'),
                    comment='Information about advisories.'
                    )
    op.create_index('ix_advisory_fire_zones_mof_fire_zone_id',
                    'advisory_fire_zones', ['mof_fire_zone_id'], unique=False)
    op.create_index('ix_advisory_fire_zones_id', 'advisory_fire_zones', ['id'], unique=False)
    op.create_index('ix_advisory_fire_zones_for_date', 'advisory_fire_zones', ['for_date'], unique=False)
    op.create_table('advisory_classified_hfi',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('hfi', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=3005, from_text='ST_GeomFromEWKT',
                                                                 name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='advisory_classified_hfi_pkey')
                    )
    op.create_index('ix_advisory_classified_hfi_id', 'advisory_classified_hfi', ['id'], unique=False)
    op.create_index('idx_advisory_classified_hfi_geom', 'advisory_classified_hfi', ['geom'], unique=False)
    # ### end Alembic commands ###
