"""adding temperature estimate to station model prediction

Revision ID: 8c7f3d10fe9d
Revises: c9f9b2849fef
Create Date: 2020-09-15 15:29:23.969703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7f3d10fe9d'
down_revision = 'c9f9b2849fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_station_model_predictions', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_station_model_predictions', 'temperature')
    # ### end Alembic commands ###
