"""add push notifications tables

Revision ID: 91f416ca0a38
Revises: 6d3221d339c8
Create Date: 2025-08-25 11:30:41.335725

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "91f416ca0a38"
down_revision = "6d3221d339c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "push_notification_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_token", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("device_model", sa.String(length=100), nullable=True),
        sa.Column("os_version", sa.String(length=50), nullable=True),
        sa.Column("app_version", sa.String(length=50), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("weather_alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("fire_alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("general_notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("latitude", sa.String(length=20), nullable=True),
        sa.Column("longitude", sa.String(length=20), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("environment", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_token", "environment", name="unique_device_token_environment"),
    )
    op.create_index(
        op.f("ix_push_notification_devices_device_token"),
        "push_notification_devices",
        ["device_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_push_notification_devices_id"), "push_notification_devices", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_push_notification_devices_user_id"),
        "push_notification_devices",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "push_notification_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_token", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("delivery_status", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("environment", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_push_notification_logs_device_token"),
        "push_notification_logs",
        ["device_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_push_notification_logs_id"), "push_notification_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_push_notification_logs_notification_type"),
        "push_notification_logs",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_push_notification_logs_user_id"),
        "push_notification_logs",
        ["user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f("ix_push_notification_logs_user_id"), table_name="push_notification_logs")
    op.drop_index(
        op.f("ix_push_notification_logs_notification_type"), table_name="push_notification_logs"
    )
    op.drop_index(op.f("ix_push_notification_logs_id"), table_name="push_notification_logs")
    op.drop_index(
        op.f("ix_push_notification_logs_device_token"), table_name="push_notification_logs"
    )
    op.drop_table("push_notification_logs")
    op.drop_index(
        op.f("ix_push_notification_devices_user_id"), table_name="push_notification_devices"
    )
    op.drop_index(op.f("ix_push_notification_devices_id"), table_name="push_notification_devices")
    op.drop_index(
        op.f("ix_push_notification_devices_device_token"), table_name="push_notification_devices"
    )
    op.drop_table("push_notification_devices")
    # ### end Alembic commands ###
