"""Alter fire_watch - optional columns

Revision ID: 945a5d8e55b6
Revises: a1553ead7fde
Create Date: 2025-06-17 08:48:51.171800

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "945a5d8e55b6"
down_revision = "a1553ead7fde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column(
        "fire_watch",
        "burn_window_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "fire_watch",
        "burn_window_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "fire_watch",
        "temp_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "fire_watch", "rh_preferred", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch",
        "wind_speed_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "fire_watch", "ffmc_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch",
        "ffmc_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "fire_watch", "ffmc_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch", "dmc_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch",
        "dmc_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "fire_watch", "dmc_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch", "dc_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch", "dc_preferred", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch", "dc_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch", "isi_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch",
        "isi_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "fire_watch", "isi_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch", "bui_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch",
        "bui_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "fire_watch", "bui_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "fire_watch",
        "hfi_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column(
        "fire_watch",
        "hfi_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch", "bui_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch",
        "bui_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch", "bui_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch", "isi_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch",
        "isi_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch", "isi_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch", "dc_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch",
        "dc_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch", "dc_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch", "dmc_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch",
        "dmc_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch", "dmc_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch", "ffmc_max", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch",
        "ffmc_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch", "ffmc_min", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "fire_watch",
        "wind_speed_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch",
        "rh_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch",
        "temp_preferred",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "fire_watch",
        "burn_window_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "fire_watch",
        "burn_window_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###
