"""drop c-haines

Revision ID: 972039fc9ba3
Revises: 4ac7d9f38f85
Create Date: 2021-06-10 09:47:04.746012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '972039fc9ba3'
down_revision = '4ac7d9f38f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('c_haines_polygons')
    op.drop_table('c_haines_predictions')
    op.drop_table('c_haines_model_runs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_haines_predictions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('prediction_timestamp', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('model_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='c_haines_predictions_pkey'),
                    sa.UniqueConstraint('prediction_timestamp', 'model_run_id',
                                        name='c_haines_predictions_prediction_timestamp_model_run_id_key')
                    )
    op.create_table('c_haines_polygons',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON',
                              from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=False),
                    sa.Column('c_haines_index', postgresql.ENUM('<4', '4-8', '8-11', '>11',
                                                                name='c_haines_severity_levels'), autoincrement=False, nullable=False),
                    sa.Column('c_haines_prediction_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='c_haines_polygons_pkey')
                    )
    op.create_table('c_haines_model_runs',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('model_run_timestamp', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('prediction_model_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='c_haines_model_runs_pkey'),
                    sa.UniqueConstraint('model_run_timestamp', 'prediction_model_id',
                                        name='c_haines_model_runs_model_run_timestamp_prediction_model_id_key')
                    )
    # ### end Alembic commands ###
