"""drop c-haines

Revision ID: 972039fc9ba3
Revises: 4ac7d9f38f85
Create Date: 2021-06-10 09:47:04.746012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '972039fc9ba3'
down_revision = '4ac7d9f38f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('c_haines_model_runs')
    op.drop_table('c_haines_polygons')
    op.drop_table('c_haines_predictions')
    op.create_index(op.f('ix_api_access_audits_create_timestamp'),
                    'api_access_audits', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_api_access_audits_create_user'),
                    'api_access_audits', ['create_user'], unique=False)
    op.create_index(op.f('ix_api_access_audits_path'), 'api_access_audits', ['path'], unique=False)
    op.create_index(op.f('ix_hourly_actuals_rh_valid'), 'hourly_actuals', ['rh_valid'], unique=False)
    op.create_index(op.f('ix_hourly_actuals_station_code'), 'hourly_actuals', ['station_code'], unique=False)
    op.create_index(op.f('ix_hourly_actuals_temp_valid'), 'hourly_actuals', ['temp_valid'], unique=False)
    op.create_index(op.f('ix_hourly_actuals_weather_date'), 'hourly_actuals', ['weather_date'], unique=False)
    op.create_index(op.f('ix_model_run_grid_subset_predictions_id'),
                    'model_run_grid_subset_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_model_run_grid_subset_predictions_prediction_model_grid_subset_id'),
                    'model_run_grid_subset_predictions', ['prediction_model_grid_subset_id'], unique=False)
    op.create_index(op.f('ix_model_run_grid_subset_predictions_prediction_model_run_timestamp_id'),
                    'model_run_grid_subset_predictions', ['prediction_model_run_timestamp_id'], unique=False)
    op.create_index(op.f('ix_model_run_grid_subset_predictions_prediction_timestamp'),
                    'model_run_grid_subset_predictions', ['prediction_timestamp'], unique=False)
    op.create_foreign_key(None, 'model_run_grid_subset_predictions', 'prediction_model_run_timestamps', [
                          'prediction_model_run_timestamp_id'], ['id'])
    op.create_foreign_key(None, 'model_run_grid_subset_predictions', 'prediction_model_grid_subsets', [
                          'prediction_model_grid_subset_id'], ['id'])
    op.create_index(op.f('ix_noon_forecasts_created_at'), 'noon_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_noon_forecasts_station_code'), 'noon_forecasts', ['station_code'], unique=False)
    op.create_index(op.f('ix_noon_forecasts_weather_date'), 'noon_forecasts', ['weather_date'], unique=False)
    op.create_index('idx_prediction_model_grid_subsets_geom', 'prediction_model_grid_subsets',
                    ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_prediction_model_grid_subsets_id'),
                    'prediction_model_grid_subsets', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_model_grid_subsets_prediction_model_id'),
                    'prediction_model_grid_subsets', ['prediction_model_id'], unique=False)
    op.create_foreign_key(None, 'prediction_model_grid_subsets',
                          'prediction_models', ['prediction_model_id'], ['id'])
    op.create_index(op.f('ix_prediction_model_run_timestamps_id'),
                    'prediction_model_run_timestamps', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_model_run_timestamps_prediction_model_id'),
                    'prediction_model_run_timestamps', ['prediction_model_id'], unique=False)
    op.create_index(op.f('ix_prediction_model_run_timestamps_prediction_run_timestamp'),
                    'prediction_model_run_timestamps', ['prediction_run_timestamp'], unique=False)
    op.create_foreign_key(None, 'prediction_model_run_timestamps',
                          'prediction_models', ['prediction_model_id'], ['id'])
    op.create_index(op.f('ix_prediction_models_abbreviation'),
                    'prediction_models', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_prediction_models_id'), 'prediction_models', ['id'], unique=False)
    op.create_index(op.f('ix_processed_model_run_urls_id'), 'processed_model_run_urls', ['id'], unique=False)
    op.create_index(op.f('ix_processed_model_run_urls_url'), 'processed_model_run_urls', ['url'], unique=True)
    op.create_index(op.f('ix_weather_station_model_predictions_id'),
                    'weather_station_model_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_weather_station_model_predictions_prediction_model_run_timestamp_id'),
                    'weather_station_model_predictions', ['prediction_model_run_timestamp_id'], unique=False)
    op.create_index(op.f('ix_weather_station_model_predictions_prediction_timestamp'),
                    'weather_station_model_predictions', ['prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_weather_station_model_predictions_station_code'),
                    'weather_station_model_predictions', ['station_code'], unique=False)
    op.create_foreign_key(None, 'weather_station_model_predictions', 'prediction_model_run_timestamps', [
                          'prediction_model_run_timestamp_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_station_model_predictions', type_='foreignkey')
    op.drop_index(op.f('ix_weather_station_model_predictions_station_code'),
                  table_name='weather_station_model_predictions')
    op.drop_index(op.f('ix_weather_station_model_predictions_prediction_timestamp'),
                  table_name='weather_station_model_predictions')
    op.drop_index(op.f('ix_weather_station_model_predictions_prediction_model_run_timestamp_id'),
                  table_name='weather_station_model_predictions')
    op.drop_index(op.f('ix_weather_station_model_predictions_id'),
                  table_name='weather_station_model_predictions')
    op.drop_index(op.f('ix_processed_model_run_urls_url'), table_name='processed_model_run_urls')
    op.drop_index(op.f('ix_processed_model_run_urls_id'), table_name='processed_model_run_urls')
    op.drop_index(op.f('ix_prediction_models_id'), table_name='prediction_models')
    op.drop_index(op.f('ix_prediction_models_abbreviation'), table_name='prediction_models')
    op.drop_constraint(None, 'prediction_model_run_timestamps', type_='foreignkey')
    op.drop_index(op.f('ix_prediction_model_run_timestamps_prediction_run_timestamp'),
                  table_name='prediction_model_run_timestamps')
    op.drop_index(op.f('ix_prediction_model_run_timestamps_prediction_model_id'),
                  table_name='prediction_model_run_timestamps')
    op.drop_index(op.f('ix_prediction_model_run_timestamps_id'), table_name='prediction_model_run_timestamps')
    op.drop_constraint(None, 'prediction_model_grid_subsets', type_='foreignkey')
    op.drop_index(op.f('ix_prediction_model_grid_subsets_prediction_model_id'),
                  table_name='prediction_model_grid_subsets')
    op.drop_index(op.f('ix_prediction_model_grid_subsets_id'), table_name='prediction_model_grid_subsets')
    op.drop_index('idx_prediction_model_grid_subsets_geom',
                  table_name='prediction_model_grid_subsets', postgresql_using='gist')
    op.drop_index(op.f('ix_noon_forecasts_weather_date'), table_name='noon_forecasts')
    op.drop_index(op.f('ix_noon_forecasts_station_code'), table_name='noon_forecasts')
    op.drop_index(op.f('ix_noon_forecasts_created_at'), table_name='noon_forecasts')
    op.drop_constraint(None, 'model_run_grid_subset_predictions', type_='foreignkey')
    op.drop_constraint(None, 'model_run_grid_subset_predictions', type_='foreignkey')
    op.drop_index(op.f('ix_model_run_grid_subset_predictions_prediction_timestamp'),
                  table_name='model_run_grid_subset_predictions')
    op.drop_index(op.f('ix_model_run_grid_subset_predictions_prediction_model_run_timestamp_id'),
                  table_name='model_run_grid_subset_predictions')
    op.drop_index(op.f('ix_model_run_grid_subset_predictions_prediction_model_grid_subset_id'),
                  table_name='model_run_grid_subset_predictions')
    op.drop_index(op.f('ix_model_run_grid_subset_predictions_id'),
                  table_name='model_run_grid_subset_predictions')
    op.drop_index(op.f('ix_hourly_actuals_weather_date'), table_name='hourly_actuals')
    op.drop_index(op.f('ix_hourly_actuals_temp_valid'), table_name='hourly_actuals')
    op.drop_index(op.f('ix_hourly_actuals_station_code'), table_name='hourly_actuals')
    op.drop_index(op.f('ix_hourly_actuals_rh_valid'), table_name='hourly_actuals')
    op.drop_index(op.f('ix_api_access_audits_path'), table_name='api_access_audits')
    op.drop_index(op.f('ix_api_access_audits_create_user'), table_name='api_access_audits')
    op.drop_index(op.f('ix_api_access_audits_create_timestamp'), table_name='api_access_audits')
    op.create_table('c_haines_predictions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('prediction_timestamp', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('model_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='c_haines_predictions_pkey'),
                    sa.UniqueConstraint('prediction_timestamp', 'model_run_id',
                                        name='c_haines_predictions_prediction_timestamp_model_run_id_key')
                    )
    op.create_table('c_haines_polygons',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON',
                              from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=False),
                    sa.Column('c_haines_index', postgresql.ENUM('<4', '4-8', '8-11', '>11',
                                                                name='c_haines_severity_levels'), autoincrement=False, nullable=False),
                    sa.Column('c_haines_prediction_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='c_haines_polygons_pkey')
                    )
    op.create_table('c_haines_model_runs',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('model_run_timestamp', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('prediction_model_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='c_haines_model_runs_pkey'),
                    sa.UniqueConstraint('model_run_timestamp', 'prediction_model_id',
                                        name='c_haines_model_runs_model_run_timestamp_prediction_model_id_key')
                    )
    # ### end Alembic commands ###
