"""Import revised HFI calc data

Revision ID: 9a5bb047ae19
Revises: 1161fab52ef5
Create Date: 2022-02-09 11:14:13.773005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5bb047ae19'
down_revision = '1161fab52ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
