"""Change classified_hfi run_date to run_datetime

Revision ID: a38c9ba9f392
Revises: cb626d81dec9
Create Date: 2022-11-03 16:51:16.889119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38c9ba9f392'
down_revision = 'cb626d81dec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('advisory_classified_hfi', sa.Column('run_datetime', sa.DateTime(), nullable=False))
    op.drop_column('advisory_classified_hfi', 'run_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('advisory_classified_hfi', sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('advisory_classified_hfi', 'run_datetime')
    # ### end Alembic commands ###
