"""Modify unique constraint on planning_weather_stations

Revision ID: b557469a7727
Revises: 1caf3488a340
Create Date: 2022-01-17 10:15:33.448252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b557469a7727'
down_revision = '1caf3488a340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('planning_weather_stations_station_code_key', 'planning_weather_stations', type_='unique')
    op.create_unique_constraint(None, 'planning_weather_stations', ['station_code', 'planning_area_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planning_weather_stations', type_='unique')
    op.create_unique_constraint('planning_weather_stations_station_code_key', 'planning_weather_stations', ['station_code'])
    # ### end Alembic commands ###
