"""Change default fuel types for coastal weather stations

Revision ID: b99dce009b9f
Revises: 52c8a568364e
Create Date: 2022-06-21 10:55:55.604206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session


# revision identifiers, used by Alembic.
revision = 'b99dce009b9f'
down_revision = '35acf3b96d8a'
branch_labels = None
depends_on = None


fuel_types_table = sa.Table('fuel_types', sa.MetaData(),
                            sa.Column('id', sa.Integer),
                            sa.Column('abbrev', sa.String),
                            sa.Column('fuel_type_code', sa.String),
                            sa.Column('description', sa.String),
                            sa.Column('percentage_conifer', sa.Integer),
                            sa.Column('percentage_dead_fir', sa.Integer))

planning_weather_stations_table = sa.Table('planning_weather_stations', sa.MetaData(),
                                           sa.Column('id', sa.Integer),
                                           sa.Column('fuel_type_id', sa.Integer),
                                           sa.Column('planning_area_id', sa.Integer),
                                           sa.Column('station_code', sa.Integer),
                                           sa.Column('order_of_appearance_in_planning_area_list', sa.Integer))

nahatlatch = 316
ford_mountain = 1144
honna = 93

cheakamus = 1283
frank_creek = 1375
meager_creek = 1083
squamish_ap = 83

sechelt_ec = 1016
powell_river_west_lake = 1218
toba_camp = 75
scar_creek = 82

mesachie_2 = 934

cedar = 59
beaver_creek = 37
chef_creek = 1383

quinsam_base_fwx = 1093
menzies_camp = 19
woss_camp = 21

stations_to_update = [
    nahatlatch,
    ford_mountain,
    honna,
    cheakamus,
    frank_creek,
    meager_creek,
    squamish_ap,
    sechelt_ec,
    powell_river_west_lake,
    toba_camp,
    scar_creek,
    mesachie_2,
    cedar,
    beaver_creek,
    chef_creek,
    quinsam_base_fwx,
    menzies_camp,
    woss_camp
]


def get_m2_25_fuel_type_id(session: Session):
    res = session.query(fuel_types_table) \
        .filter(fuel_types_table.c.abbrev.ilike(f'M2 25%'))
    return int(res.first().id)


def upgrade():
    # ### commands auto generated by Alembic ###
    session = Session(bind=op.get_bind())
    m2_25_id = get_m2_25_fuel_type_id(session)

    stmt = planning_weather_stations_table.update().\
        where(planning_weather_stations_table.c.station_code.in_(stations_to_update)).\
        values({
            'fuel_type_id': m2_25_id,
        })

    session.execute(stmt)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###

    # Skip downgrade, apply forward fixes
    pass
    # ### end Alembic commands ###
