"""Adds Audit model

Revision ID: c92ba5b2b3d5
Revises: 004ac48ffe18
Create Date: 2021-04-12 14:33:00.507000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92ba5b2b3d5'
down_revision = '004ac48ffe18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('create_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    comment='The audit log of an authenticated request by a user.'
                    )
    op.create_index(op.f('ix_audits_create_timestamp'), 'audits', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_audits_path'), 'audits', ['path'], unique=False)
    op.create_index(op.f('ix_audits_username'), 'audits', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audits_username'), table_name='audits')
    op.drop_index(op.f('ix_audits_path'), table_name='audits')
    op.drop_index(op.f('ix_audits_create_timestamp'), table_name='audits')
    op.drop_table('audits')
    # ### end Alembic commands ###
