"""Add advisory_zone_status table

Revision ID: d276ba9eed1f
Revises: 6d3221d339c8
Create Date: 2025-11-21 10:55:28.590720

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d276ba9eed1f"
down_revision = "6d3221d339c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "advisory_zone_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("advisory_percentage", sa.Float(), nullable=True),
        sa.Column("warning_percentage", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status"],
            ["advisory_hfi_classification_threshold.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_parameters", "advisory_shape_id"),
        comment="Status of zones (advisory/warning) for a given run parameter.",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f("ix_advisory_zone_status_run_parameters"), table_name="advisory_zone_status")
    op.drop_index(op.f("ix_advisory_zone_status_id"), table_name="advisory_zone_status")
    op.drop_index(
        op.f("ix_advisory_zone_status_advisory_shape_id"), table_name="advisory_zone_status"
    )
    op.drop_table("advisory_zone_status")
    # ### end Alembic commands ###
