"""fire centres

Revision ID: d6e9a814aa6f
Revises: 3ae0eeb6720d
Create Date: 2021-01-25 16:24:42.217376

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd6e9a814aa6f'
down_revision = '3ae0eeb6720d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('fire_centers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON',
                                                                 from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    comment='Bounds for fire centres'
                    )
    op.create_index(op.f('ix_fire_centers_id'), 'fire_centers', ['id'], unique=False)
    op.drop_index('idx_c_haines_polygons_geom', table_name='c_haines_polygons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.create_index('idx_c_haines_polygons_geom', 'c_haines_polygons', ['geom'], unique=False)
    op.drop_index(op.f('ix_fire_centers_id'), table_name='fire_centers')
    op.drop_table('fire_centers')
    # ### end Alembic commands ###
