"""morecast forecast table

Revision ID: de8355996f8e
Revises: 971848399c46
Create Date: 2023-02-14 15:00:50.990100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8355996f8e'
down_revision = '971848399c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('morecast_forecast',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('station_code', sa.Integer(), nullable=False),
                    sa.Column('for_date', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('temp', sa.Integer(), nullable=False),
                    sa.Column('rh', sa.Integer(), nullable=False),
                    sa.Column('precip', sa.Integer(), nullable=False),
                    sa.Column('wind_speed', sa.Integer(), nullable=False),
                    sa.Column('wind_direction', sa.Integer(), nullable=False),
                    sa.Column('create_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('create_user', sa.String(), nullable=False),
                    sa.Column('update_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('update_user', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_morecast_forecast_create_timestamp'),
                    'morecast_forecast', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_for_date'), 'morecast_forecast', ['for_date'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_id'), 'morecast_forecast', ['id'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_precip'), 'morecast_forecast', ['precip'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_rh'), 'morecast_forecast', ['rh'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_station_code'), 'morecast_forecast', ['station_code'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_temp'), 'morecast_forecast', ['temp'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_update_timestamp'),
                    'morecast_forecast', ['update_timestamp'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_wind_direction'), 'morecast_forecast', ['wind_direction'], unique=False)
    op.create_index(op.f('ix_morecast_forecast_wind_speed'), 'morecast_forecast', ['wind_speed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_morecast_forecast_wind_speed'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_wind_direction'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_update_timestamp'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_temp'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_station_code'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_rh'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_precip'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_id'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_for_date'), table_name='morecast_forecast')
    op.drop_index(op.f('ix_morecast_forecast_create_timestamp'), table_name='morecast_forecast')
    op.drop_table('morecast_forecast')
    # ### end Alembic commands ###
