"""Index update_date on weather_model_prediction table

Revision ID: edb25d3a5286
Revises: 2169aa76dfea
Create Date: 2023-06-22 14:37:38.676153

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'edb25d3a5286'
down_revision = '2169aa76dfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_index(op.f('ix_weather_station_model_predictions_update_date'),
                    'weather_station_model_predictions', ['update_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_weather_station_model_predictions_update_date'),
                  table_name='weather_station_model_predictions')
    # ### end Alembic commands ###
