"""c_haines

Revision ID: eee97e38d5df
Revises: ad4f37763020
Create Date: 2021-03-02 17:45:41.751605

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'eee97e38d5df'
down_revision = 'ad4f37763020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('fire_centers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON',
                                                                 from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    comment='Bounds for fire centres'
                    )
    op.create_index(op.f('ix_fire_centers_id'), 'fire_centers', ['id'], unique=False)
    op.create_table('c_haines_model_runs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('model_run_timestamp', sa.TIMESTAMP(), nullable=False),
                    sa.Column('prediction_model_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['prediction_model_id'], ['prediction_models.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('model_run_timestamp', 'prediction_model_id'),
                    comment='Identifies the model run and prediction for a particular set of c-haines calculations'
                    )
    op.create_index(op.f('ix_c_haines_model_runs_id'), 'c_haines_model_runs', ['id'], unique=False)
    op.create_table('c_haines_predictions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('prediction_timestamp', sa.TIMESTAMP(), nullable=False),
                    sa.Column('model_run_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['model_run_id'], ['c_haines_model_runs.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('prediction_timestamp', 'model_run_id'),
                    comment='Identifies the model run and prediction for a particular set of c-haines calculations'
                    )
    op.create_index(op.f('ix_c_haines_predictions_id'), 'c_haines_predictions', ['id'], unique=False)
    op.create_table('c_haines_polygons',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON',
                                                                 from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                    sa.Column('c_haines_index', sa.Enum('<4', '4-8', '8-11', '11+',
                                                        name='c_haines_severity_levels'), nullable=False),
                    sa.Column('c_haines_prediction_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['c_haines_prediction_id'], ['c_haines_predictions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_c_haines_polygons_id'), 'c_haines_polygons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_c_haines_polygons_id'), table_name='c_haines_polygons')
    op.drop_table('c_haines_polygons')
    op.drop_index(op.f('ix_c_haines_predictions_id'), table_name='c_haines_predictions')
    op.drop_table('c_haines_predictions')
    op.drop_index(op.f('ix_c_haines_model_runs_id'), table_name='c_haines_model_runs')
    op.drop_table('c_haines_model_runs')
    op.drop_index(op.f('ix_fire_centers_id'), table_name='fire_centers')
    op.drop_table('fire_centers')
    op.execute('DROP TYPE c_haines_severity_levels')
    # ### end Alembic commands ###
