"""classified hfi

Revision ID: fc2d4ff7398d
Revises: ef2482f08074
Create Date: 2022-09-01 15:53:54.406633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fc2d4ff7398d'
down_revision = 'ef2482f08074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_classified_hfi',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hfi', sa.String(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=3005,
                                                                 spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_advisory_classified_hfi_geom', 'advisory_classified_hfi',
                    ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_advisory_classified_hfi_id'), 'advisory_classified_hfi', ['id'], unique=False)
    op.add_column('advisory_fire_zones', sa.Column('for_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_advisory_fire_zones_for_date'), 'advisory_fire_zones', ['for_date'], unique=False)
    op.create_index('idx_advisory_areas_geom', 'advisory_shapes', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
    session = Session(bind=op.get_bind())
    session.execute("SELECT UpdateGeometrySRID('advisory_shapes','geom',3005);")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_advisory_areas_geom', table_name='advisory_shapes', postgresql_using='gist')
    op.drop_index(op.f('ix_advisory_fire_zones_for_date'), table_name='advisory_fire_zones')
    op.drop_column('advisory_fire_zones', 'for_date')
    op.drop_index(op.f('ix_advisory_classified_hfi_id'), table_name='advisory_classified_hfi')
    op.drop_index('idx_advisory_classified_hfi_geom', table_name='advisory_classified_hfi', postgresql_using='gist')
    op.drop_table('advisory_classified_hfi')
    # ### end Alembic commands ###
