"""Fire start range

Revision ID: fe33ab8c6c01
Revises: 9a5bb047ae19
Create Date: 2022-03-15 17:54:03.322910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe33ab8c6c01'
down_revision = '9a5bb047ae19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('hfi_fire_start_range',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Fire start range'
                    )
    op.create_table('hfi_fire_centre_fire_start_range',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fire_start_range_id', sa.Integer(), nullable=False),
                    sa.Column('fire_centre_id', sa.Integer(), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['fire_centre_id'], ['fire_centres.id'], ),
                    sa.ForeignKeyConstraint(['fire_start_range_id'], ['hfi_fire_start_range.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('fire_start_range_id', 'fire_centre_id',
                                        name='unique_fire_start_range_for_fire_centre'),
                    comment='Link table for fire centre fire start ranges'
                    )
    op.create_index(op.f('ix_hfi_fire_centre_fire_start_range_fire_centre_id'),
                    'hfi_fire_centre_fire_start_range', ['fire_centre_id'], unique=False)
    op.create_index(op.f('ix_hfi_fire_centre_fire_start_range_fire_start_range_id'),
                    'hfi_fire_centre_fire_start_range', ['fire_start_range_id'], unique=False)
    op.create_table('hfi_fire_start_lookup',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fire_start_range_id', sa.Integer(), nullable=False),
                    sa.Column('mean_intensity_group', sa.Integer(), nullable=False),
                    sa.Column('prep_level', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['fire_start_range_id'], ['hfi_fire_start_range.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Fire start mean intensity group prep level lookup'
                    )
    op.create_index(op.f('ix_hfi_fire_start_lookup_fire_start_range_id'),
                    'hfi_fire_start_lookup', ['fire_start_range_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_hfi_fire_start_lookup_fire_start_range_id'), table_name='hfi_fire_start_lookup')
    op.drop_table('hfi_fire_start_lookup')
    op.drop_index(op.f('ix_hfi_fire_centre_fire_start_range_fire_start_range_id'),
                  table_name='hfi_fire_centre_fire_start_range')
    op.drop_index(op.f('ix_hfi_fire_centre_fire_start_range_fire_centre_id'),
                  table_name='hfi_fire_centre_fire_start_range')
    op.drop_table('hfi_fire_centre_fire_start_range')
    op.drop_table('hfi_fire_start_range')
    # ### end Alembic commands ###
