#!/usr/bin/env bash
# Based on: https://itnext.io/using-git-hooks-to-enforce-branch-naming-policy-ffd81fa01e5e
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(task|story|bug)\/[A-Za-z0-9._-]+(\/[0-9]+)?$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
