version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `web` directory
    directory: "/web"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for Poetry (pip value also checks for poetry)
  - package-ecosystem: "pip"
    # Look for a `pyproject.toml` in the `api` directory
    directory: "/api"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
