version: 2
# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `web` directory
    directory: "/web"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Limit to only 1 pr at a time.
    # If there's one thing out of date, there's probably more. Consider running `poetry update`
    # and saving yourself a bunch of time.
    open-pull-requests-limit: 1

  # Enable version updates for Poetry (pip value also checks for poetry)
  - package-ecosystem: "pip"
    # Look for a `pyproject.toml` in the `api` directory
    directory: "/api"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Limit to only 2 pr's at a time. If there are too many PR's - we just end up running out of compute
    # space on our cluster.
    open-pull-requests-limit: 2
