name: OpenShift Runner
description: Run OpenShift Commands with a Common Set of Base Scripts
inputs:
  AUTH_TOKEN:
    description: OpenShift service account authorization token
    required: true
  NAMESPACE:
    description: OpenShift project namespace
    required: true
  APP_NAME:
    description: OpenShift app name label
    required: true
  BRANCH:
    description: Branch of the application repo that is to be deployed
    required: false
    default: master
  CLUSTER:
    description: The target OpenShift cluster
    required: false
    default: https://console.pathfinder.gov.bc.ca:8443
  SCRIPT:
    description: Custom script to 
    required: false
    default: ''
runs:
  using: docker
  image: Dockerfile