# feeling sad? remember to validate this file!
# curl --data-binary @codecov.yml https://codecov.io/validate

# Ignore prototype features until matured
ignore:
  - "web/src/features/cHaines"
  - "web/src/features/fwiCalculator"
coverage:
  # https://docs.codecov.com/docs/commit-status
  status:
    patch:
      default:
        threshold: 100%
    project:
      # https://docs.codecov.com/docs/commit-status#project-status
      default:
        # target: minimum coverage ratio that the commit must meet
        target: 80%
        # threshold: Allow the coverage to drop by X%, and posting a success status.
        threshold: 1%
      # https://docs.codecov.com/docs/commit-status#splitting-up-projects-example
      api:
        paths:
          - api/app
      web:
        paths:
          - web/src
        # web isn't quite amazing yet - would be nice to push it up to 80%
        target: 73%
