coverage:
  # precision: 1
  # round: nearest
  # https://docs.codecov.com/docs/commit-status
  status:
    project:
      # https://docs.codecov.com/docs/commit-status#project-status
      default:
        # target: minimum coverage ratio that the commit must meet
        target: 80%
        # threshold: Allow the coverage to drop by X%, and posting a success status.
        threshold: 5%
      # https://docs.codecov.com/docs/commit-status#splitting-up-projects-example
      api:
        paths:
          - api/app
      web:
        path:
          - web/src
