# feeling sad? remember to validate this file!
# curl --data-binary @codecov.yml https://codecov.io/validate

# Ignore prototype features until matured
ignore:
  - "web/src/features/cHaines"
  - "web/src/features/fwiCalculator"
  - "web/src/features/fireWatch"
  - "web/src/api/fbaAPI.ts" # Unstable while we work on ASA prototype
  - "web/src/utils/env.ts" # Just configuration
  - "api/app/auto_spatial_advisory" # Unstable while we work on ASA prototype
  - "backend/packages/wps-shared/src/wps_shared/db/crud" # We don't write tests for the crud layer, the crud layer is mocked out in tests.
  - "backend/packages/wps-shared/src/wps_shared/db/database.py" # We don't write tests for the database layer, it's mocked out in tests.
  - "backend/packages/wps-shared/src/wps_shared/db/models" # We don't care about testing table schema.
  - "backend/packages/wps-shared/src/wps_shared/schemas" # We don't care about explicitly testing pydantic response schema.
  - "web/src/utils/fwi" # We're temporarily hardcoding cffdrs ts modules here. Will switch to npm package eventually.
  - "mobile/keycloak/ios/" # CAPPlugin, OIDAuthState are seemingly not mockable
  - "**/tests/**"
  - "**/local/**"

coverage:
  # https://docs.codecov.com/docs/commit-status
  status:
    patch:
      default:
        threshold: 100%
    project:
      # https://docs.codecov.com/docs/commit-status#project-status
      default:
        # target: minimum coverage ratio that the commit must meet
        target: 70%
        # threshold: Allow the coverage to drop by X%, and posting a success status.
        threshold: 3%
        paths:
          - api/app
          - web/src
          - wps_jobs
          - wps_shared
          - wps_wf1
      # https://docs.codecov.com/docs/commit-status#splitting-up-projects-example
      api:
        paths:
          - api/app
        threshold: 3%
      web:
        paths:
          - web/src
        # web isn't quite amazing yet - would be nice to push it up to 80%
        target: 71%
      wps_jobs:
        paths:
          - wps_jobs
        threshold: 3%
      wps_shared:
        paths:
          - wps_shared
        threshold: 3%
      wps_wf1:
        paths:
          - wps_wf1
        threshold: 3%
      asa_go:
        paths:
          - mobile/asa-go
        threshold: 3%
