coverage:
  precision: 1
  status:
    project:
      # https://docs.codecov.com/docs/commit-status#splitting-up-projects-example
      api:
        paths:
          - app
      web:
        path:
          - src
      # https://docs.codecov.com/docs/commit-status#project-status
      default:
        target: 80%
        threshold: 5%
      # basic
      # target: auto
      # we're ok with a tiny drop
      # threshold: 1%
