version: '3'
services:
    web:
      build:
        context: .
        dockerfile: dev.Dockerfile
      env_file:
        - .env
      ports:
        - "3000:3000"
      volumes:
        - .:/app:delegated # Volume optimizations https://engageinteractive.co.uk/blog/making-docker-faster-on-mac
