version: "3.7"
services:
  api:
    build: .
    env_file:
      - app/.env
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app:delegated
    depends_on:
      - db
  db:
    # https://hub.docker.com/r/postgis/postgis
    image: postgis/postgis
    hostname: db
    ports:
      - "5432:5432"
