version: "3.7"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - ./api/app/.env.docker
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app:delegated
      - ./web/build:/app/static:delegated
    networks:
      - wps_network
  # Application's local database container & service
  db:
    image: postgis/postgis
    hostname: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wps
      - POSTGRES_PASSWORD=wps
      - POSTGRES_DB=wps
      - POSTGRES_HOST_AUTH_METHOD="trust"
    networks:
      - wps_network
  web:
    build:
      context: web
      dockerfile: Dockerfile
    env_file:
      - web/.env
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app:delegated # Volume optimizations https://engageinteractive.co.uk/blog/making-docker-faster-on-mac
networks:
  wps_network:
    driver: bridge
