version: "3.7"
services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app:delegated
