ARG DOCKER_IMAGE=image-registry.openshift-image-registry.svc:5000/e1e498-tools/wps-web-base
# SUPER IMPORTANT: NODE_OPTIONS="--v8-pool-size=1"
# A pod running in our openshift cluster, will report a ridiculous amount of cpu's available, as
# it's reporting on the underlying hardware. Node, in it's wisdom, will try to scale to using a
# huge amount of cpu's, which in turn results in massive memory usage. It's very important to limit
# the cpu pool size to something realistic.
ARG NODE_OPTIONS="--v8-pool-size=4"

# PHASE 1 - build static html.
# Pull from local registry - we can't pull from docker due to limits.
# see https://catalog.redhat.com/software/containers/ubi8/nodejs-14/5ed7887dd70cc50e69c2fabb for
# details
FROM registry.access.redhat.com/ubi8/nodejs-16 as static

# Switch to root user for package installs
USER 0

ADD web .
# NOTE: Can't use "--production=true", because we need react-scripts for yarn run start.
RUN npm install -g npm@latest && npm install -g yarn@latest && yarn install --frozen-lockfile

# Switch back to default user
USER 1001

# while testing stuff out:
# docker build -f ./Dockerfile.web --tag=wps/web .
# -p 8080:3000 - "map port 3000 in the container, to 8080 in the host"
# docker run -p 3000:3000 wps/web
# docker contains ls
# docker stop [the container id]
# 

CMD ["yarn", "run", "start"]

# # PHASE 2 - prepare hosting.
# # Using local docker image to speed up build. See openshift/wps-api-base for details.
# FROM ${DOCKER_IMAGE}

# # Copy the static content:
# COPY --from=static /opt/app-root/src/build /app/static

# The fastapi docker image defaults to port 80, but openshift doesn't allow non-root users port 80.
# EXPOSE 8080