version: "3.7"
volumes:
  # Create volumes for docker to store stuff in that doesn't clash with local!
  node_modules:
  static:
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - ./api/app/.env.docker
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app:delegated
      - static:/app/static
    networks:
      - wps_network
    command: bash -c "PYTHONPATH=. alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8080"
  # Application's local database container & service
  db:
    image: postgis/postgis
    hostname: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wps
      - POSTGRES_PASSWORD=wps
      - POSTGRES_DB=wps
      - POSTGRES_HOST_AUTH_METHOD="trust"
    networks:
      - wps_network
  web:
    build:
      context: web
      dockerfile: Dockerfile
    env_file:
      - web/.env
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app # Volume optimizations https://engageinteractive.co.uk/blog/making-docker-faster-on-mac
      - node_modules:/app/node_modules/
      - static:/app/build
    command: bash -c "npm run build & npm run start"
networks:
  wps_network:
    driver: bridge
