version: '3'
services:
    web:
      env_file:
        - .env
      build: .
      ports:
        - "3000:3000"
      volumes:
        - .:/app:delegated # Volume optimizations https://engageinteractive.co.uk/blog/making-docker-faster-on-mac
