apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: wps-jobs-base
labels:
  app: ${NAME}${SUFFIX}
  phase: build
  app.kubernetes.io/name: wps-jobs-base
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "ubuntu.24.04"
parameters:
  - name: NAME
    value: wps-jobs-base
  - name: SUFFIX
  - name: VERSION
    description: Output version
    required: true
  - name: GIT_URL
    value: https://github.com/bcgov/wps.git
  - name: GIT_BRANCH
    value: main
objects:
  #ImageStream is created if it doesn't already exist
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: wps-jobs-base
        common: "true"
      name: wps-jobs-base
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: wps-jobs-base
      name: wps-jobs-base
    spec:
      completionDeadlineSeconds: 3600 # 60 minutes
      resources:
        limits:
          cpu: 2000m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 256Mi
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}${SUFFIX}:${VERSION}
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: origin/${GIT_BRANCH}
        contextDir: wps_jobs/openshift/docker
      strategy:
        type: Docker