apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: patroni
labels:
  app: ${NAME}${SUFFIX}
  phase: build
  app.kubernetes.io/component: database
  app.kubernetes.io/name: patroni
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "12"
parameters:
  - name: NAME
    value: patroni-postgres
  - name: SUFFIX
  - name: VERSION
    description: Output version
    value: "v12-latest"
  - name: GIT_URI
    value: https://github.com/bcgov/wps.git
  - name: GIT_REF
    value: main
  - name: POSTGRES_VERSION
    value: "12"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${VERSION}"
      postCommit: {}
      resources: {}
      source:
        contextDir: openshift/patroni-postgis/docker
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URI}
        type: Git
      strategy:
        dockerStrategy:
        type: Docker
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    status:
      lastVersion: 0
