kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-template
  labels:
    name: ${NAME}-template
    app: ${APP_NAME}
    app-group: ${APP_GROUP}
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}-admin
      labels:
        name: ${NAME}-admin
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
    stringData:
      username: ${MATOMO_ADMIN_USER}
      password: ${MATOMO_ADMIN_PASSWORD}
    type: Opaque
parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to
      the server instance.
    required: true
    value: matomo
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: matomo
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: matomo-controller
  - name: MATOMO_ADMIN_USER
    displayName: Matomo Admin Username
    description: Admin Username for Matomo
    required: true
    value: admin
  - name: MATOMO_ADMIN_PASSWORD
    displayName: Matomo Admin Password
    description: Password for the Matomo Admin user.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
