kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-template
  labels:
    name: ${NAME}-template
    app: ${APP_NAME}
    app-group: ${APP_GROUP}
    role: ${ROLE}
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        service: ${NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}:${TAG_NAME}
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-proxy
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}-proxy:${TAG_NAME}
      replicas: 1
      test: false
      selector:
        app: ${NAME}
        deploymentconfig: ${NAME}
        template: ${NAME}-template
      template:
        metadata:
          labels:
            name: ${NAME}
            app: ${APP_NAME}
            deploymentconfig: matomo
            template: ${NAME}-template
            app-group: ${APP_GROUP}
            role: ${ROLE}
        spec:
          volumes:
            - name: ${NAME}-source
              emptyDir: {}
            - name: ${NAME}-config
              persistentVolumeClaim:
                claimName: ${NAME}-config
          containers:
            - image: ${SOURCE_IMAGE_NAME}
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 9000
                timeoutSeconds: 5
              name: matomo
              ports:
                - containerPort: 9000
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 9000
                timeoutSeconds: 5
              resources:
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/www/html
                  name: matomo-source
                - mountPath: /var/www/html/config
                  name: matomo-config
            - image: ${NAME}-proxy
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 1
              name: ${NAME}-proxy
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 1
              resources: {}
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/www/html
                  name: matomo-source
  # TODO: Add KNP (k8t network policy)
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}-config
      labels:
        name: ${NAME}-config
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
    spec:
      storageClassName: ${PERSISTENT_VOLUME_CLASS}
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: ${PERSISTENT_VOLUME_SIZE}
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
    spec:
      host: ${MATOMO_URL}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        service: ${NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}
      type: ClusterIP
      sessionAffinity: None
parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to
      the server instance.
    required: true
    value: matomo
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: matomo
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description:
      The namespace of the OpenShift project containing the imagestream
      for the application.
    value: e1e498-tools
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: matomo
  - name: NAMESPACE_NAME
    displayName: Namespace Name
    description: The name of the namespace being deployed to..
    required: true
    value: e1e498-dev
  - name: ROLE
    displayName: Role
    description:
      The role of this service within the application - used for Network
      Policies
    required: true
    value: matomo
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: matomo-controller
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: prod
  - name: MATOMO_URL
    displayName: Matomo URL
    description:
      The public domain endpoint for Matomo. A value will be created by
      default if not specified.
    required: false
    value: ""
  - name: PERSISTENT_VOLUME_SIZE
    displayName: Persistent Volume Size
    description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
    required: true
    value: 1Gi
  - name: PERSISTENT_VOLUME_CLASS
    displayName: Persistent Volume Class name
    description:
      The class of the volume; gluster-file, gluster-block, netapp-file-standard,
      netapp-file-standard, netapp-block-standard
    required: false
    value: netapp-file-standard
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 100m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 512Mi
