apiVersion: loki.grafana.com/v1
kind: AlertingRule
metadata:
  labels:
    openshift.io/loki: "true" # This is required for Loki to pick up the config
    app: "nats-logging"
  name: nats-alerts
  namespace: e1e498-prod
spec:
  groups:
    - interval: 1m
      name: LoggingAlerts
      repeat_interval: 30m
      rules:
        - alert: NatsErrors
          annotations:
            description: Alerts fire when any error/critical logs occur.
            summary: Nats is generating too many errors
          # Get the rate of error logs per second over the last minute, alert if any errors occurred.
          expr: |
            sum(rate({ kubernetes_namespace_name="e1e498-prod", kubernetes_pod_name=~"wps-prod-nats.*" } | json | level=~"critical|emerg|fatal|alert|crit|error|err|eror" [1m])) > 0
          for: 0s
          labels:
            namespace: e1e498-prod
            severity: critical
  tenantID: application
