python_sources()

poetry_requirements(
    name="poetry",
)

pex_binary(
    name="prune",
    entry_point="prune.py",
)

pex_binary(
    name="prune_test",
    entry_point="prune_test.py",
)

python_tests(
    name="tests",
)
