import React, { useState } from 'react'
import { makeStyles } from '@material-ui/core/styles'
import Table from '@material-ui/core/Table'
import TableBody from '@material-ui/core/TableBody'
import TableCell from '@material-ui/core/TableCell'
import TableContainer from '@material-ui/core/TableContainer'
import TableRow from '@material-ui/core/TableRow'
import TableHead from '@material-ui/core/TableHead'
import TableSortLabel from '@material-ui/core/TableSortLabel'
import Paper from '@material-ui/core/Paper'
import Typography from '@material-ui/core/Typography'

import { ModelValue } from 'api/modelAPI'
import { NoonForecastValue } from 'api/forecastAPI'
import { MODEL_VALUE_DECIMAL } from 'utils/constants'
import { getDatetimeComparator, Order } from 'utils/table'

/**
 * Reusable component used to display noon forecasts (issued by forecasters)
 * and/or model forecasts (generated by computer-run models) in table format
 */

const useStyles = makeStyles({
  display: {
    paddingTop: 8,
    paddingBottom: 8
  },
  paper: {
    width: '100%'
  },
  tableContainer: {
    maxHeight: 300
  },
  title: {
    paddingBottom: 4
  }
})

interface Column {
  id:
    | 'datetime'
    | 'temperature'
    | 'relative_humidity'
    | 'wind_direction'
    | 'wind_speed'
    | 'total_precipitation'
  label: string
  minWidth?: number
  maxWidth?: number
  align?: 'left' | 'right' | 'center'
  format?: (value: number) => string | number
}

const columns: Column[] = [
  { id: 'datetime', label: 'Date (PDT)', align: 'left' },
  {
    id: 'temperature',
    label: 'Temp (°C)',
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  },
  {
    id: 'relative_humidity',
    label: 'RH (%)',
    align: 'right',
    format: (value: number) => Math.round(value)
  },
  {
    id: 'wind_direction',
    label: 'Wind Dir',
    align: 'right',
    format: (value: number) => Math.round(value)
  },
  {
    id: 'wind_speed',
    label: 'Wind Spd (km/h)',
    minWidth: 70,
    maxWidth: 100,
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  },
  {
    id: 'total_precipitation',
    label: 'Precip (mm/cm)',
    minWidth: 70,
    maxWidth: 100,
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  }
]

interface Props {
  rows: (ModelValue | NoonForecastValue)[] | undefined
  testId: string
  title: string
}

const NoonWeatherValueTable = ({ rows, testId, title }: Props) => {
  const classes = useStyles()
  const [order, setOrder] = useState<Order>('asc')

  if (!rows) {
    return null
  }

  const rowsSortedByDatetime = [...rows].sort(getDatetimeComparator(order))
  const toggleDatetimeOrder = () => {
    setOrder(order === 'asc' ? 'desc' : 'asc')
  }

  return (
    <div className={classes.display} data-testid={testId}>
      <Typography className={classes.title} variant="subtitle2" component="div">
        {title}
      </Typography>
      <Paper className={classes.paper} elevation={1}>
        <TableContainer className={classes.tableContainer}>
          <Table stickyHeader size="small" aria-label="noon weather data table">
            <TableHead>
              <TableRow>
                {columns.map(column => {
                  const canSort = column.id === 'datetime'

                  return (
                    <TableCell
                      key={column.id}
                      align={column.align}
                      style={{ minWidth: column.minWidth, maxWidth: column.maxWidth }}
                      sortDirection={canSort ? order : false}
                    >
                      {canSort ? (
                        <TableSortLabel
                          active={canSort}
                          direction={order}
                          onClick={toggleDatetimeOrder}
                        >
                          {column.label}
                        </TableSortLabel>
                      ) : (
                        column.label
                      )}
                    </TableCell>
                  )
                })}
              </TableRow>
            </TableHead>

            <TableBody>
              {rowsSortedByDatetime.map((row, idx) => (
                <TableRow key={idx} hover tabIndex={-1}>
                  {columns.map(column => {
                    const value = row[column.id]
                    let display = null

                    if (typeof value === 'string' && column.id === 'datetime') {
                      display = value.slice(0, 10)
                    }
                    if (typeof value === 'number' && column.format) {
                      display = column.format(value)
                    }

                    return (
                      <TableCell key={column.id} align={column.align}>
                        {display}
                      </TableCell>
                    )
                  })}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>
    </div>
  )
}

export default React.memo(NoonWeatherValueTable)
