name: GWA Setup
description: Install the gwa CLI

runs:
  using: composite
  steps:
    - name: Install GWA CLI
      shell: bash
      run: |
        set -euo pipefail
        GWA_BIN_DIR="${RUNNER_TEMP}/gwa-bin"
        mkdir -p "${GWA_BIN_DIR}"
        curl -L "https://github.com/bcgov/gwa-cli/releases/download/v3.0.7/gwa_Linux_x86_64.tgz" \
          | tar -zxf - -C "${GWA_BIN_DIR}"
        echo "${GWA_BIN_DIR}" >> "${GITHUB_PATH}"
