"""Classified HFI table

Revision ID: 1c0954110d4e
Revises: fdb4438ff783
Create Date: 2022-11-23 11:57:21.068362

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from models import TZTimeStamp


# revision identifiers, used by Alembic.
revision = '1c0954110d4e'
down_revision = 'fdb4438ff783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hfi',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hfi', sa.String(), nullable=True),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=3005,
                                                                 spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                    sa.Column('run_date', TZTimeStamp(), nullable=False),
                    sa.Column('for_date', TZTimeStamp(), nullable=False),
                    sa.Column('run_type', sa.Enum('forecast', 'actual', name='runtype'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Processed HFI by run date and time'
                    )
    op.create_index('idx_hfi_geom', 'hfi', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_hfi_hfi'), 'hfi', ['hfi'], unique=False)
    op.create_index('sfms_run_multiindex', 'hfi', ['run_date', 'for_date', 'run_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sfms_run_multiindex', table_name='hfi')
    op.drop_index(op.f('ix_hfi_hfi'), table_name='hfi')
    op.drop_index('idx_hfi_geom', table_name='hfi', postgresql_using='gist')
    op.drop_table('hfi')
    # drop the enum explicitly, alembic doesn't know how to do this
    op.execute('DROP TYPE runtype')
    # ### end Alembic commands ###
