"""drop zones

Revision ID: 4e9825746735
Revises: c6e39ac9dc29
Create Date: 2023-01-30 12:43:21.159086

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm.session import Session
from sqlalchemy.dialects import postgresql
import geoalchemy2
from models import TZTimeStamp

# revision identifiers, used by Alembic.
revision = '4e9825746735'
down_revision = 'c6e39ac9dc29'
branch_labels = None
depends_on = None

fire_zone_table = sa.Table('fire_zones', sa.MetaData(),
                           sa.Column('id', sa.Integer(), nullable=False),
                           sa.Column('feature_id', sa.Integer(), nullable=False),
                           sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326,
                                                                        spatial_index=False, from_text='ST_GeomFromEWKT',
                                                                        name='geometry'), nullable=False),
                           sa.Column('create_date', TZTimeStamp(), nullable=False),
                           sa.Column('update_date', TZTimeStamp(), nullable=False),
                           sa.Column('mof_fire_zone_id', sa.Integer(), nullable=True),
                           sa.Column('mof_fire_zone_name', sa.String(), nullable=True),
                           sa.Column('mof_fire_centre_name', sa.String(), nullable=True),
                           sa.Column('headquarters_city_name', sa.String(), nullable=True),
                           sa.Column('objectid', sa.Integer(), nullable=True),
                           sa.Column('feature_area_sqm', postgresql.DOUBLE_PRECISION(), nullable=True),
                           sa.Column('feature_length_m', postgresql.DOUBLE_PRECISION(), nullable=True),
                           sa.Column('geometry.area', sa.Integer(), nullable=True),
                           sa.Column('geometry.len', sa.Integer(), nullable=True))

fire_zone_labels_table = sa.Table('fire_zones_labels', sa.MetaData(),
                                  sa.Column('id', sa.Integer(), nullable=False),
                                  sa.Column('feature_id', sa.Integer(), nullable=False),
                                  sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326,
                                                                               spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                                  sa.Column('create_date', TZTimeStamp(), nullable=False),
                                  sa.Column('update_date', TZTimeStamp(), nullable=False),
                                  sa.Column('mof_fire_zone_id', sa.Integer(), nullable=True),
                                  sa.Column('mof_fire_zone_name', sa.String(), nullable=True),
                                  sa.Column('mof_fire_centre_name', sa.String(), nullable=True),
                                  sa.Column('headquarters_city_name', sa.String(), nullable=True),
                                  sa.Column('objectid', sa.Integer(), nullable=True),
                                  sa.Column('feature_area_sqm', postgresql.DOUBLE_PRECISION(), nullable=True),
                                  sa.Column('feature_length_m', postgresql.DOUBLE_PRECISION(), nullable=True),
                                  sa.Column('geometry.area', sa.Integer(), nullable=True),
                                  sa.Column('geometry.len', sa.Integer(), nullable=True),
                                  sa.PrimaryKeyConstraint('id'),
                                  comment='BC fire zone labels'
                                  )


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    session = Session(bind=op.get_bind())
    session.query(fire_zone_table).delete()
    session.query(fire_zone_labels_table).delete()
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    pass
    # ### end Alembic commands ###
