"""Add snow masked

Revision ID: 76ae33fd9c63
Revises: 8a1117356bfa
Create Date: 2022-12-28 15:27:57.150872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ae33fd9c63'
down_revision = '8a1117356bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('hfi', sa.Column('snow_masked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('hfi', 'snow_masked')
    # ### end Alembic commands ###
