"""indexes run_date, for_date, run_type on hfi

Revision ID: 8dd1ac777de7
Revises: 8a1117356bfa
Create Date: 2022-12-14 17:17:12.731872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd1ac777de7'
down_revision = '8a1117356bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_index(op.f('ix_hfi_for_date'), 'hfi', ['for_date'], unique=False)
    op.create_index(op.f('ix_hfi_run_date'), 'hfi', ['run_date'], unique=False)
    op.create_index(op.f('ix_hfi_run_type'), 'hfi', ['run_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_hfi_run_type'), table_name='hfi')
    op.drop_index(op.f('ix_hfi_run_date'), table_name='hfi')
    op.drop_index(op.f('ix_hfi_for_date'), table_name='hfi')
    # ### end Alembic commands ###
