"""Fire Labels tables

Revision ID: 950a9e61996c
Revises: dbe8db639a6d
Create Date: 2022-11-23 14:40:35.541707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
from models import TZTimeStamp

# revision identifiers, used by Alembic.
revision = '950a9e61996c'
down_revision = 'dbe8db639a6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('fire_zones_labels',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('feature_id', sa.Integer(), nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326,
                                                                 spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                    sa.Column('create_date', TZTimeStamp(), nullable=False),
                    sa.Column('update_date', TZTimeStamp(), nullable=False),
                    sa.Column('mof_fire_zone_id', sa.Integer(), nullable=True),
                    sa.Column('mof_fire_zone_name', sa.String(), nullable=True),
                    sa.Column('mof_fire_centre_name', sa.String(), nullable=True),
                    sa.Column('headquarters_city_name', sa.String(), nullable=True),
                    sa.Column('objectid', sa.Integer(), nullable=True),
                    sa.Column('feature_area_sqm', postgresql.DOUBLE_PRECISION(), nullable=True),
                    sa.Column('feature_length_m', postgresql.DOUBLE_PRECISION(), nullable=True),
                    sa.Column('geometry.area', sa.Integer(), nullable=True),
                    sa.Column('geometry.len', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    comment='BC fire zone labels'
                    )
    op.create_index('idx_fire_zones_labels_geom', 'fire_zones_labels', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('fire_zones_labels_ext',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326,
                              spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
                    sa.Column('create_date', TZTimeStamp(), nullable=False),
                    sa.Column('update_date', TZTimeStamp(), nullable=False),
                    sa.Column('fire_zone_feature_id', sa.Integer(), nullable=False),
                    sa.Column('fire_zone_mof_fire_zone_id', sa.Integer(), nullable=True),
                    sa.Column('fire_zone_mof_fire_zone_name', sa.String(), nullable=True),
                    sa.Column('fire_zone_headquarters_city_name', sa.String(), nullable=True),
                    sa.Column('fire_zone_mof_fire_centre_name', sa.String(), nullable=True),
                    sa.Column('fire_zone_objectid', sa.Integer(), nullable=True),
                    sa.Column('fire_zone_feature_area_sqm', postgresql.DOUBLE_PRECISION(), nullable=True),
                    sa.Column('fire_zone_feature_length_m', postgresql.DOUBLE_PRECISION(), nullable=True),
                    sa.Column('fire_zone_geometry.area', sa.Integer(), nullable=True),
                    sa.Column('fire_zone_geometry.len', sa.Integer(), nullable=True),
                    sa.Column('fire_centre_feature_id', sa.Integer(), nullable=False),
                    sa.Column('fire_centre_mof_fire_centre_id', sa.Integer(), nullable=True),
                    sa.Column('fire_centre_mof_fire_centre_name', sa.String(), nullable=True),
                    sa.Column('fire_centre_objectid', sa.Integer(), nullable=True),
                    sa.Column('fire_centre_feature_area_sqm', postgresql.DOUBLE_PRECISION(), nullable=True),
                    sa.Column('fire_centre_feature_length_m', postgresql.DOUBLE_PRECISION(), nullable=True),
                    sa.Column('fire_centre_geometry.area', sa.Integer(), nullable=True),
                    sa.Column('fire_centre_geometry.len', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    comment='BC fire zone extended labels'
                    )
    op.create_index('idx_fire_zones_labels_ext_geom', 'fire_zones_labels_ext',
                    ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index('idx_fire_zones_labels_ext_geom', table_name='fire_zones_labels_ext', postgresql_using='gist')
    op.drop_table('fire_zones_labels_ext')
    op.drop_index('idx_fire_zones_labels_geom', table_name='fire_zones_labels', postgresql_using='gist')
    op.drop_table('fire_zones_labels')
    # ### end Alembic commands ###
