"""Initial migration, add postgis

Revision ID: fdb4438ff783
Revises: 
Create Date: 2022-11-22 15:38:43.218787

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'fdb4438ff783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.execute(
        'create extension IF NOT EXISTS postgis'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.execute(
        'drop extension IF EXISTS postgis'
    )
    # ### end Alembic commands ###
