"""Add combust area col to advisory_shapes

Revision ID: 0669994d4089
Revises: fbca68ccc9da
Create Date: 2022-09-09 15:50:57.376665

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0669994d4089'
down_revision = 'fbca68ccc9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('advisory_shapes', sa.Column('combustible_area', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('advisory_shapes', 'combustible_area')
    # ### end Alembic commands ###
