"""drop min wind hfi table

Revision ID: 521681b2d802
Revises: 08799237842e
Create Date: 2025-03-18 15:09:42.215661

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '521681b2d802'
down_revision = '08799237842e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('advisory_hfi_wind_speed')
    # ### end Alembic commands ###


def downgrade():
    # no-op, forward fix
    pass
