"""Adds placename labels to advisory_shapes

Revision ID: c5bea0920d53
Revises: c9e46d098c73
Create Date: 2024-09-10 12:54:07.552418

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from wps_shared.db.models.auto_spatial_advisory import Shape
from sqlalchemy import update
from app.utils.zone_units import get_zone_units_geojson

# revision identifiers, used by Alembic.
revision = "c5bea0920d53"
down_revision = "c9e46d098c73"
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())

    op.add_column("advisory_shapes", sa.Column("placename_label", sa.String(), nullable=True))

    fire_zone_units = get_zone_units_geojson()
    for feature in fire_zone_units.get("features", []):
        properties = feature.get("properties", {})
        object_id = properties.get("OBJECTID")

        prefix = properties.get("FIRE_ZONE_")
        suffix = properties.get("FIRE_ZON_1")
        placename_label = f"{prefix}-{suffix}"

        stmt = update(Shape).where(Shape.source_identifier == str(object_id)).values(placename_label=placename_label)

        session.execute(stmt)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("advisory_shapes", "placename_label")
    # ### end Alembic commands ###
