apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: wps-api-base
labels:
  app: ${NAME}${SUFFIX}
  phase: build
  app.kubernetes.io/name: wps-api-base
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "ubuntu.22.04"
parameters:
  - name: NAME
    value: wps-api-base
  - name: SUFFIX
  - name: VERSION
    description: Output version
    value: "ubuntu.22.04-latest"
  - name: GIT_URL
    value: https://github.com/bcgov/wps.git
  - name: GIT_BRANCH
    value: gunicorn_python
objects:
  #ImageStream is created if it doesn't already exist
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: wps-api-base
        common: "true"
      name: wps-api-base
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: wps-api-base
      name: wps-api-base
    spec:
      completionDeadlineSeconds: 3600 # 60 minutes
      resources:
        limits:
          memory: 2Gi
          cpu: 4000m
        requests:
          memory: 1Gi
          cpu: 500m
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}${SUFFIX}:${VERSION}
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: origin/${GIT_BRANCH}
        contextDir: openshift/wps-api-base/docker
      strategy:
        type: Docker
