apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: uvicorn-gunicorn-fastapi
labels:
  app: ${NAME}${SUFFIX}
  phase: build
  app.kubernetes.io/name: uvicorn-gunicorn-fastapi
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "python3.8"
parameters:
  - name: NAME
    value: wps-api-base
  - name: SUFFIX
  - name: VERSION
    description: Output version
    value: "python3.8-latest"
  - name: GIT_URL
    value: https://github.com/bcgov/wps.git
  - name: GIT_BRANCH
    value: main
objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: wps-api-base
      labels:
        app: wps-api-base
    spec:
      storageClassName: netapp-file-standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
  #ImageStream is created if it doesn't already exist
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: wps-api-base
        common: "true"
      name: wps-api-base
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: wps-api-base
      name: wps-api-base
    spec:
      completionDeadlineSeconds: 3600 # 60 minutes
      resources:
        limits:
          memory: 2Gi
          cpu: 4000m
        requests:
          memory: 1Gi
          cpu: 500m
      volumes:
        - name: wps-api-base
          persistentVolumeClaim:
            claimName: wps-api-base
      volumeMounts:
        - mountPath: /var/tmp
          name: wps-api-base
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}${SUFFIX}:${VERSION}
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: origin/${GIT_BRANCH}
        contextDir: openshift/wps-api-base/docker
      strategy:
        type: Docker
