kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-template
  labels:
    name: ${NAME}-template
    app: ${APP_NAME}
    app-group: ${APP_GROUP}
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
    stringData:
      database-root-password: "${MYSQL_ROOT_PASSWORD}"
      database-password: "${MYSQL_PASSWORD}"
      database-user: "${MYSQL_USER}"
      database-name: "${MYSQL_DATABASE}"
    type: Opaque
parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to
      the server instance.
    required: true
    value: matomo-db
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: matomo-db
  - name: "MYSQL_DATABASE"
    displayName: "MariaDB Database Name"
    description: "The name of the MariaDB database."
    required: true
    value: "matomo"
  - name: "MYSQL_USER"
    displayName: "MariaDB Connection Username"
    description: "Username for MariaDB user that will be used for accessing the database.  Needs to be base64 encoded/"
    required: true
    generate: "expression"
    from: "[a-zA-Z0-9]{10}"
  - name: "MYSQL_PASSWORD"
    displayName: "MariaDB Connection Password"
    description: "Password for the MariaDB connection user.  Needs to be base64 encoded/"
    required: true
    generate: "expression"
    from: "[a-zA-Z0-9]{10}"
  - name: "MYSQL_ROOT_PASSWORD"
    displayName: "MariaDB Admin Password"
    description: "Password for the MariaDB administrative account.  Needs to be base64 encoded."
    required: true
    generate: "expression"
    from: "[a-zA-Z0-9]{16}"
