"""simplify high hfi area

Revision ID: 0961883640ef
Revises: 298f400dfa64
Create Date: 2023-02-02 16:58:43.239162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0961883640ef'
down_revision = '298f400dfa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic  ###
    op.add_column('high_hfi_area', sa.Column('threshold', sa.Integer(), nullable=False))
    op.add_column('high_hfi_area', sa.Column('area', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'high_hfi_area', 'advisory_hfi_classification_threshold', ['threshold'], ['id'])
    op.drop_column('high_hfi_area', 'warn_area')
    op.drop_column('high_hfi_area', 'advisory_area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('high_hfi_area', sa.Column('advisory_area', postgresql.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=False))
    op.add_column('high_hfi_area', sa.Column('warn_area', postgresql.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'high_hfi_area', type_='foreignkey')
    op.drop_column('high_hfi_area', 'area')
    op.drop_column('high_hfi_area', 'threshold')
    # ### end Alembic commands ###
