"""drop shape combustible_area column

Revision ID: 0f0c47b0c47a
Revises: 7ac7f5600d81
Create Date: 2026-05-07 13:45:04.280862

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f0c47b0c47a"
down_revision = "7ac7f5600d81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("advisory_shapes", "combustible_area")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###

    op.add_column(
        "advisory_shapes",
        sa.Column(
            "combustible_area",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )

    # ### end Alembic commands ###
