"""spot forecast columns - issued/expired

Revision ID: 3b9310ff54f5
Revises: 8ad2e0d77c9f
Create Date: 2026-05-22 10:52:22.798252

"""

import sqlalchemy as sa
from alembic import op
from wps_shared.db.models.common import TZTimeStamp

# revision identifiers, used by Alembic.
revision = "3b9310ff54f5"
down_revision = "8ad2e0d77c9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("spot_forecast", sa.Column("issued_at", TZTimeStamp(), nullable=False))
    op.add_column("spot_forecast", sa.Column("expires_at", TZTimeStamp(), nullable=True))
    op.drop_column("spot_forecast", "for_date")
    op.drop_column("spot_forecast", "updated_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###

    op.add_column(
        "spot_forecast",
        sa.Column("updated_at", TZTimeStamp(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "spot_forecast",
        sa.Column("for_date", TZTimeStamp(), autoincrement=False, nullable=True),
    )
    op.drop_column("spot_forecast", "expires_at")
    op.drop_column("spot_forecast", "issued_at")

    # ### end Alembic commands ###
