"""smurfi-related data models

Revision ID: 61f7af3a7407
Revises: cf8397b26783
Create Date: 2026-01-21 16:56:30.800155

"""
from alembic import op
import sqlalchemy as sa
from wps_shared.db.models.common import TZTimeStamp

# revision identifiers, used by Alembic.
revision = '61f7af3a7407'
down_revision = 'cf8397b26783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('fire_number', sa.String(), nullable=False),
    sa.Column('request_time', TZTimeStamp(), nullable=False),
    sa.Column('end_time', TZTimeStamp(), nullable=False),
    sa.Column('status', sa.Enum('Requested', 'Started', 'Suspended', 'Complete', 'Archived', name='spotrequeststatusenum'), nullable=False),
    sa.Column('requested_frequency', sa.ARRAY(sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='frequencydayenum')), nullable=True),
    sa.Column('requested_type', sa.Enum('Full', 'Mini', 'Ventilation', name='requesttypeenum'), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('geographic_area_name', sa.String(), nullable=True),
    sa.Column('email_distribution_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fire_centre', sa.String(), nullable=True),
    sa.Column('created_at', TZTimeStamp(), nullable=False),
    sa.Column('updated_at', TZTimeStamp(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id'),
    comment='Requests for SMURFI spot forecasts'
    )
    op.create_table('spot_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('additional_fire_numbers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('forecaster', sa.String(), nullable=False),
    sa.Column('forecaster_email', sa.String(), nullable=True),
    sa.Column('forecaster_phone', sa.String(), nullable=True),
    sa.Column('representative_weather_stations', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('fire_size', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('aspect', sa.String(), nullable=True),
    sa.Column('valley', sa.String(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('inversion_and_venting', sa.Text(), nullable=True),
    sa.Column('outlook', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZTimeStamp(), nullable=False),
    sa.Column('updated_at', TZTimeStamp(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Versions of SMURFI spot forecasts'
    )
    op.create_table('spot_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_version_id', sa.Integer(), nullable=False),
    sa.Column('forecast_time', TZTimeStamp(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('wind', sa.String(), nullable=True),
    sa.Column('probability_of_precipitation', sa.Float(), nullable=True),
    sa.Column('precipitation_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['spot_version_id'], ['spot_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Detailed forecasts for SMURFI spot versions'
    )
    op.create_table('spot_general_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_version_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('Today', 'Tonight', 'Tomorrow', name='spotforecastperiodenum'), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('conditions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spot_version_id'], ['spot_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='General (less specific) forecasts for SMURFI spot versions'
    )


def downgrade():
   
    op.drop_table('spot_general_forecast')
    op.drop_table('spot_forecast')
    op.drop_table('spot_version')
    op.drop_table('spot')
    # ### end Alembic commands ###
