"""add fire watch weather and prescription tables

Revision ID: 65d5edb3f200
Revises: 54176235e225
Create Date: 2025-05-08 15:11:13.879236

"""

from alembic import op
import sqlalchemy as sa
from wps_shared.db.models.common import TZTimeStamp

# revision identifiers, used by Alembic.
revision = "65d5edb3f200"
down_revision = "54176235e225"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "prescription_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Contains the status of a fire watch prescription.",
    )
    op.create_index(op.f("ix_prescription_status_id"), "prescription_status", ["id"], unique=False)

    op.create_table(
        "fire_watch_weather",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fire_watch_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("prediction_model_run_timestamp_id", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("relative_humidity", sa.Float(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("precip_24hr", sa.Float(), nullable=False),
        sa.Column("ffmc", sa.Float(), nullable=False),
        sa.Column("dmc", sa.Float(), nullable=False),
        sa.Column("dc", sa.Float(), nullable=False),
        sa.Column("isi", sa.Float(), nullable=False),
        sa.Column("bui", sa.Float(), nullable=False),
        sa.Column("hfi", sa.Float(), nullable=False),
        sa.Column("in_prescription", sa.Integer(), nullable=False),
        sa.Column("created_at", TZTimeStamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fire_watch_id"],
            ["fire_watch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["in_prescription"],
            ["prescription_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prediction_model_run_timestamp_id"],
            ["prediction_model_run_timestamps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Contains weather forecasts and FWI/FBP indices related to a fire watch prescribed burn.",
    )
    op.create_index(op.f("ix_fire_watch_weather_date"), "fire_watch_weather", ["date"], unique=False)
    op.create_index(op.f("ix_fire_watch_weather_fire_watch_id"), "fire_watch_weather", ["fire_watch_id"], unique=False)
    op.create_index(op.f("ix_fire_watch_weather_id"), "fire_watch_weather", ["id"], unique=False)
    op.create_index(op.f("ix_fire_watch_weather_in_prescription"), "fire_watch_weather", ["in_prescription"], unique=False)
    op.create_index(op.f("ix_fire_watch_weather_prediction_model_run_timestamp_id"), "fire_watch_weather", ["prediction_model_run_timestamp_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f("ix_fire_watch_weather_prediction_model_run_timestamp_id"), table_name="fire_watch_weather")
    op.drop_index(op.f("ix_fire_watch_weather_in_prescription"), table_name="fire_watch_weather")
    op.drop_index(op.f("ix_fire_watch_weather_id"), table_name="fire_watch_weather")
    op.drop_index(op.f("ix_fire_watch_weather_fire_watch_id"), table_name="fire_watch_weather")
    op.drop_index(op.f("ix_fire_watch_weather_date"), table_name="fire_watch_weather")
    op.drop_table("fire_watch_weather")
    op.drop_index(op.f("ix_prescription_status_id"), table_name="prescription_status")
    op.drop_table("prescription_status")
    # ### end Alembic commands ###
