"""advisory_fuel_shapes constraints

Revision ID: 7ac7f5600d81
Revises: 05349c55c1e2
Create Date: 2026-05-05 14:44:35.738801

"""

import sqlalchemy as sa
from alembic import op
from wps_shared.db.models.common import TZTimeStamp

# revision identifiers, used by Alembic.
revision = "7ac7f5600d81"
down_revision = "05349c55c1e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.execute(
        """
        DELETE FROM advisory_shape_fuels
        WHERE fuel_type_raster_id IS NULL
        """
    )

    # set the default time for server default to a fixed point in time to avoid issues with existing 
    # records having a null created_at value
    op.add_column(
        "advisory_shape_fuels",
        sa.Column(
            "created_at",
            TZTimeStamp(),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    # remove the server default now that the column has been added and existing records have a value 
    # to ensure future records get the correct timestamp
    op.alter_column("advisory_shape_fuels", "created_at", server_default=None)
    
    op.alter_column(
        "advisory_shape_fuels", "fuel_type_raster_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_unique_constraint(
        "uq_advisory_shape_fuels_shape_fuel_raster",
        "advisory_shape_fuels",
        ["advisory_shape_id", "fuel_type", "fuel_type_raster_id"],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###

    op.drop_constraint(
        "uq_advisory_shape_fuels_shape_fuel_raster", "advisory_shape_fuels", type_="unique"
    )
    op.alter_column(
        "advisory_shape_fuels", "fuel_type_raster_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("advisory_shape_fuels", "created_at")

    # ### end Alembic commands ###
