"""add advisory fuel stats table

Revision ID: 7cd069b79aaa
Revises: 8e85e2b291a9
Create Date: 2023-11-09 15:34:35.225016

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7cd069b79aaa'
down_revision = '8e85e2b291a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('advisory_fuel_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisory_shape_id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('run_parameters', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['advisory_shape_id'], ['advisory_shapes.id'], ),
    sa.ForeignKeyConstraint(['fuel_type'], ['sfms_fuel_types.id'], ),
    sa.ForeignKeyConstraint(['run_parameters'], ['run_parameters.id'], ),
    sa.ForeignKeyConstraint(['threshold'], ['advisory_hfi_classification_threshold.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisory_shape_id', 'threshold', 'run_parameters', 'fuel_type'),
    comment='Fuel type stats per fire shape by advisory threshold'
    )
    op.create_index(op.f('ix_advisory_fuel_stats_advisory_shape_id'), 'advisory_fuel_stats', ['advisory_shape_id'], unique=False)
    op.create_index(op.f('ix_advisory_fuel_stats_fuel_type'), 'advisory_fuel_stats', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_advisory_fuel_stats_id'), 'advisory_fuel_stats', ['id'], unique=False)
    op.create_index(op.f('ix_advisory_fuel_stats_run_parameters'), 'advisory_fuel_stats', ['run_parameters'], unique=False)
    op.create_table_comment(
        'advisory_elevation_stats',
        'Elevation stats per fire shape by advisory threshold',
        existing_comment='Elevation stats per fire zone by advisory threshold',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.create_table_comment(
        'advisory_elevation_stats',
        'Elevation stats per fire zone by advisory threshold',
        existing_comment='Elevation stats per fire shape by advisory threshold',
        schema=None
    )
    op.drop_index(op.f('ix_advisory_fuel_stats_run_parameters'), table_name='advisory_fuel_stats')
    op.drop_index(op.f('ix_advisory_fuel_stats_id'), table_name='advisory_fuel_stats')
    op.drop_index(op.f('ix_advisory_fuel_stats_fuel_type'), table_name='advisory_fuel_stats')
    op.drop_index(op.f('ix_advisory_fuel_stats_advisory_shape_id'), table_name='advisory_fuel_stats')
    op.drop_table('advisory_fuel_stats')
    # ### end Alembic commands ###
