"""initial_schema

Revision ID: 9bb0dc8ed7fb
Revises:
Create Date: 2025-12-29 14:38:46.566192

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
import wps_shared.db.models.common

# revision identifiers, used by Alembic.
revision = "9bb0dc8ed7fb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: PostGIS extension must be installed before running this migration
    # Run manually as supervisor: CREATE EXTENSION IF NOT EXISTS postgis;

    # Create metadata table for tracking application data tables
    op.create_table(
        "application_data_tables",
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("seed_order", sa.Integer(), nullable=True),
        sa.Column("last_seeded", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("table_name"),
        comment="Metadata registry tracking which tables contain application/reference data (e.g., fuel types, fire centres, planning areas) that must be preserved and re-seeded during database migrations. Use seed_order for dependency-safe loading order.",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advisory_hfi_classification_threshold",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="The Operational Safe Works Standards specifies that an hfi of greater than 4000 should result in an advisory. However in order for an FBAN to create useful information, there are other thresholds of concern. E.g. > 10000",
    )
    op.create_index(
        op.f("ix_advisory_hfi_classification_threshold_id"),
        "advisory_hfi_classification_threshold",
        ["id"],
        unique=False,
    )
    op.create_table(
        "advisory_shape_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.Enum("fire_centre", "fire_zone", "fire_zone_unit", name="shapetypeenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Identify kind of advisory area (e.g. Zone, Fire etc.)",
    )
    op.create_index(
        op.f("ix_advisory_shape_types_name"), "advisory_shape_types", ["name"], unique=True
    )
    op.create_table(
        "api_access_audits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("create_user", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("create_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="The audit log of an authenticated request by a user.",
    )
    op.create_index(
        op.f("ix_api_access_audits_create_timestamp"),
        "api_access_audits",
        ["create_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_access_audits_create_user"), "api_access_audits", ["create_user"], unique=False
    )
    op.create_index(op.f("ix_api_access_audits_path"), "api_access_audits", ["path"], unique=False)
    op.create_table(
        "fire_centres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fire_centres_id"), "fire_centres", ["id"], unique=False)
    op.create_index(op.f("ix_fire_centres_name"), "fire_centres", ["name"], unique=False)
    op.create_table(
        "fuel_type_raster",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("xsize", sa.Integer(), nullable=False),
        sa.Column("ysize", sa.Integer(), nullable=False),
        sa.Column("object_store_path", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("create_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Processed fuel type rasters.",
    )
    op.create_table(
        "fuel_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("abbrev", sa.String(), nullable=False),
        sa.Column("fuel_type_code", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("percentage_conifer", sa.Integer(), nullable=True),
        sa.Column("percentage_dead_fir", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fuel_types_abbrev"), "fuel_types", ["abbrev"], unique=False)
    op.create_index(op.f("ix_fuel_types_id"), "fuel_types", ["id"], unique=False)
    op.create_table(
        "hfi_fire_start_range",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Fire start range",
    )
    op.create_table(
        "hourly_actuals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weather_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("station_code", sa.Integer(), nullable=False),
        sa.Column("temp_valid", sa.Boolean(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("dewpoint", sa.Float(), nullable=True),
        sa.Column("rh_valid", sa.Boolean(), nullable=False),
        sa.Column("relative_humidity", sa.Float(), nullable=False),
        sa.Column("wdir_valid", sa.Boolean(), nullable=False),
        sa.Column("wind_direction", sa.Float(), nullable=False),
        sa.Column("wspeed_valid", sa.Boolean(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("precip_valid", sa.Boolean(), nullable=False),
        sa.Column("precipitation", sa.Float(), nullable=False),
        sa.Column("ffmc", sa.Float(), nullable=False),
        sa.Column("isi", sa.Float(), nullable=False),
        sa.Column("fwi", sa.Float(), nullable=False),
        sa.Column("created_at", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("weather_date", "station_code"),
        comment="The hourly_actuals for a weather station and weather date.",
    )
    op.create_index(
        op.f("ix_hourly_actuals_rh_valid"), "hourly_actuals", ["rh_valid"], unique=False
    )
    op.create_index(
        op.f("ix_hourly_actuals_station_code"), "hourly_actuals", ["station_code"], unique=False
    )
    op.create_index(
        op.f("ix_hourly_actuals_temp_valid"), "hourly_actuals", ["temp_valid"], unique=False
    )
    op.create_index(
        op.f("ix_hourly_actuals_weather_date"), "hourly_actuals", ["weather_date"], unique=False
    )
    op.create_table(
        "morecast_2_materialized_view",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("apcp_sfc_0", sa.Float(), nullable=False),
        sa.Column("bias_adjusted_precip_24h", sa.Float(), nullable=False),
        sa.Column("bias_adjusted_rh", sa.Float(), nullable=False),
        sa.Column("bias_adjusted_temperature", sa.Float(), nullable=False),
        sa.Column("bias_adjusted_wind_speed", sa.Float(), nullable=False),
        sa.Column("bias_adjusted_wdir", sa.Float(), nullable=False),
        sa.Column("precip_24h", sa.Float(), nullable=False),
        sa.Column(
            "prediction_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False
        ),
        sa.Column("station_code", sa.Integer(), nullable=True),
        sa.Column("rh_tgl_2", sa.Float(), nullable=False),
        sa.Column("tmp_tgl_2", sa.Float(), nullable=False),
        sa.Column("update_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("wdir_tgl_10", sa.Float(), nullable=False),
        sa.Column("wind_tgl_10", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_morecast_2_materialized_view_id"),
        "morecast_2_materialized_view",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_morecast_2_materialized_view_prediction_timestamp"),
        "morecast_2_materialized_view",
        ["prediction_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_morecast_2_materialized_view_station_code"),
        "morecast_2_materialized_view",
        ["station_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_morecast_2_materialized_view_update_date"),
        "morecast_2_materialized_view",
        ["update_date"],
        unique=False,
    )
    op.create_table(
        "morecast_forecast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_code", sa.Integer(), nullable=False),
        sa.Column("for_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("temp", sa.Float(), nullable=False),
        sa.Column("rh", sa.Integer(), nullable=False),
        sa.Column("precip", sa.Float(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("wind_direction", sa.Integer(), nullable=True),
        sa.Column("grass_curing", sa.Float(), nullable=True),
        sa.Column("create_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("create_user", sa.String(), nullable=False),
        sa.Column("update_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("update_user", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_morecast_forecast_create_timestamp"),
        "morecast_forecast",
        ["create_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_morecast_forecast_for_date"), "morecast_forecast", ["for_date"], unique=False
    )
    op.create_index(
        op.f("ix_morecast_forecast_grass_curing"),
        "morecast_forecast",
        ["grass_curing"],
        unique=False,
    )
    op.create_index(op.f("ix_morecast_forecast_id"), "morecast_forecast", ["id"], unique=False)
    op.create_index(
        op.f("ix_morecast_forecast_precip"), "morecast_forecast", ["precip"], unique=False
    )
    op.create_index(op.f("ix_morecast_forecast_rh"), "morecast_forecast", ["rh"], unique=False)
    op.create_index(
        op.f("ix_morecast_forecast_station_code"),
        "morecast_forecast",
        ["station_code"],
        unique=False,
    )
    op.create_index(op.f("ix_morecast_forecast_temp"), "morecast_forecast", ["temp"], unique=False)
    op.create_index(
        op.f("ix_morecast_forecast_update_timestamp"),
        "morecast_forecast",
        ["update_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_morecast_forecast_wind_direction"),
        "morecast_forecast",
        ["wind_direction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_morecast_forecast_wind_speed"), "morecast_forecast", ["wind_speed"], unique=False
    )
    op.create_table(
        "noon_forecasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weather_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("station_code", sa.Integer(), nullable=False),
        sa.Column("temp_valid", sa.Boolean(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("rh_valid", sa.Boolean(), nullable=False),
        sa.Column("relative_humidity", sa.Float(), nullable=False),
        sa.Column("wdir_valid", sa.Boolean(), nullable=False),
        sa.Column("wind_direction", sa.Float(), nullable=False),
        sa.Column("wspeed_valid", sa.Boolean(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("precip_valid", sa.Boolean(), nullable=False),
        sa.Column("precipitation", sa.Float(), nullable=False),
        sa.Column("gc", sa.Float(), nullable=False),
        sa.Column("ffmc", sa.Float(), nullable=False),
        sa.Column("dmc", sa.Float(), nullable=False),
        sa.Column("dc", sa.Float(), nullable=False),
        sa.Column("isi", sa.Float(), nullable=False),
        sa.Column("bui", sa.Float(), nullable=False),
        sa.Column("fwi", sa.Float(), nullable=False),
        sa.Column("created_at", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("wfwx_update_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("weather_date", "wfwx_update_date", "station_code"),
        comment="The noon_forecast for a weather station and weather date.",
    )
    op.create_index(
        op.f("ix_noon_forecasts_created_at"), "noon_forecasts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_noon_forecasts_station_code"), "noon_forecasts", ["station_code"], unique=False
    )
    op.create_index(
        op.f("ix_noon_forecasts_weather_date"), "noon_forecasts", ["weather_date"], unique=False
    )
    op.create_index(
        op.f("ix_noon_forecasts_wfwx_update_date"),
        "noon_forecasts",
        ["wfwx_update_date"],
        unique=False,
    )
    op.create_table(
        "percent_grass_curing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_code", sa.Integer(), nullable=False),
        sa.Column("percent_grass_curing", sa.Float(), nullable=False),
        sa.Column("for_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Record containing information about percent grass curing from the CWFIS.",
    )
    op.create_index(
        op.f("ix_percent_grass_curing_for_date"), "percent_grass_curing", ["for_date"], unique=False
    )
    op.create_index(
        op.f("ix_percent_grass_curing_id"), "percent_grass_curing", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_percent_grass_curing_station_code"),
        "percent_grass_curing",
        ["station_code"],
        unique=False,
    )
    op.create_table(
        "prediction_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("projection", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("abbreviation", "projection"),
        comment="Identifies the Weather Prediction model",
    )
    op.create_index(
        op.f("ix_prediction_models_abbreviation"),
        "prediction_models",
        ["abbreviation"],
        unique=False,
    )
    op.create_index(op.f("ix_prediction_models_id"), "prediction_models", ["id"], unique=False)
    op.create_table(
        "prescription_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Contains the status of a fire watch prescription.",
    )
    op.create_index(op.f("ix_prescription_status_id"), "prescription_status", ["id"], unique=False)
    op.create_table(
        "processed_model_run_urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("create_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("update_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Record to indicate that a particular model run file has been processed.",
    )
    op.create_index(
        op.f("ix_processed_model_run_urls_id"), "processed_model_run_urls", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_processed_model_run_urls_url"), "processed_model_run_urls", ["url"], unique=True
    )
    op.create_table(
        "processed_snow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("for_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("processed_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("snow_source", sa.Enum("viirs", name="snowsourceenum"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Record containing information about processed snow coverage data.",
    )
    op.create_index(
        op.f("ix_processed_snow_for_date"), "processed_snow", ["for_date"], unique=False
    )
    op.create_index(op.f("ix_processed_snow_id"), "processed_snow", ["id"], unique=False)
    op.create_index(
        op.f("ix_processed_snow_processed_date"), "processed_snow", ["processed_date"], unique=False
    )
    op.create_index(
        op.f("ix_processed_snow_snow_source"), "processed_snow", ["snow_source"], unique=False
    )
    op.create_table(
        "run_parameters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "run_type", postgresql.ENUM("actual", "forecast", name="runtypeenum"), nullable=False
        ),
        sa.Column("run_datetime", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("for_date", sa.Date(), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_type", "run_datetime", "for_date"),
        comment="A combination of run type, run datetime and for date.",
    )
    op.create_index(
        op.f("ix_run_parameters_for_date"), "run_parameters", ["for_date"], unique=False
    )
    op.create_index(op.f("ix_run_parameters_id"), "run_parameters", ["id"], unique=False)
    op.create_index(
        op.f("ix_run_parameters_run_datetime"), "run_parameters", ["run_datetime"], unique=False
    )
    op.create_index(
        op.f("ix_run_parameters_run_type"), "run_parameters", ["run_type"], unique=False
    )
    op.create_table(
        "saved_model_run_for_sfms_urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("create_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("update_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Record to indicate that a particular RDPS model run file has been downloaded and saved to S3 storage.",
    )
    op.create_index(
        op.f("ix_saved_model_run_for_sfms_urls_id"),
        "saved_model_run_for_sfms_urls",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_saved_model_run_for_sfms_urls_s3_key"),
        "saved_model_run_for_sfms_urls",
        ["s3_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_saved_model_run_for_sfms_urls_url"),
        "saved_model_run_for_sfms_urls",
        ["url"],
        unique=True,
    )
    op.create_table(
        "sfms_fuel_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fuel_type_id", sa.Integer(), nullable=False),
        sa.Column("fuel_type_code", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="Fuel types used by SFMS to calculate HFI spatially",
    )
    op.create_index(
        op.f("ix_sfms_fuel_types_fuel_type_id"), "sfms_fuel_types", ["fuel_type_id"], unique=False
    )
    op.create_index(op.f("ix_sfms_fuel_types_id"), "sfms_fuel_types", ["id"], unique=False)
    op.create_table(
        "advisory_classified_hfi",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("run_type", sa.Enum("forecast", "actual", name="runtypeenum"), nullable=False),
        sa.Column("run_datetime", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("for_date", sa.Date(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=3005,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["threshold"],
            ["advisory_hfi_classification_threshold.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="HFI classification for some forecast/advisory run on some day, for some date",
    )
    op.create_index(
        "idx_advisory_classified_hfi_geom",
        "advisory_classified_hfi",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_advisory_classified_hfi_id"), "advisory_classified_hfi", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_classified_hfi_run_type"),
        "advisory_classified_hfi",
        ["run_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_classified_hfi_threshold"),
        "advisory_classified_hfi",
        ["threshold"],
        unique=False,
    )
    op.create_table(
        "advisory_fuel_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fuel_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=3005,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("fuel_type_raster_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fuel_type_raster_id"],
            ["fuel_type_raster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Identify some kind of fuel type",
    )
    op.create_index(
        "idx_advisory_fuel_types_geom",
        "advisory_fuel_types",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_advisory_fuel_types_fuel_type_id"),
        "advisory_fuel_types",
        ["fuel_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_fuel_types_fuel_type_raster_id"),
        "advisory_fuel_types",
        ["fuel_type_raster_id"],
        unique=False,
    )
    op.create_index(op.f("ix_advisory_fuel_types_id"), "advisory_fuel_types", ["id"], unique=False)
    op.create_table(
        "advisory_shapes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_identifier", sa.String(), nullable=False),
        sa.Column("shape_type", sa.Integer(), nullable=False),
        sa.Column("combustible_area", sa.Float(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=3005,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("placename_label", sa.String(), nullable=True),
        sa.Column("fire_centre", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fire_centre"],
            ["fire_centres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shape_type"],
            ["advisory_shape_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_identifier", "shape_type"),
        comment="Record identifying some area of interest with respect to advisories",
    )
    op.create_index(
        "idx_advisory_shapes_geom",
        "advisory_shapes",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_advisory_shapes_fire_centre"), "advisory_shapes", ["fire_centre"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_shapes_shape_type"), "advisory_shapes", ["shape_type"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_shapes_source_identifier"),
        "advisory_shapes",
        ["source_identifier"],
        unique=False,
    )
    op.create_table(
        "fire_watch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "burn_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=3005,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("burn_window_end", wps_shared.db.models.common.TZTimeStamp(), nullable=True),
        sa.Column("burn_window_start", wps_shared.db.models.common.TZTimeStamp(), nullable=True),
        sa.Column("contact_email", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("create_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("create_user", sa.String(), nullable=False),
        sa.Column("fire_centre", sa.Integer(), nullable=True),
        sa.Column("station_code", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELLED", "COMPLETE", "HOLD", name="burnstatusenum"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("update_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("update_user", sa.String(), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "C1",
                "C2",
                "C3",
                "C4",
                "C5",
                "C6",
                "C7",
                "C7B",
                "D1",
                "D2",
                "M1",
                "M2",
                "M3",
                "M4",
                "O1A",
                "O1B",
                "S1",
                "S2",
                "S3",
                name="fueltypeenum",
            ),
            nullable=False,
        ),
        sa.Column("percent_conifer", sa.Float(), nullable=True),
        sa.Column("percent_dead_fir", sa.Float(), nullable=True),
        sa.Column("percent_grass_curing", sa.Float(), nullable=True),
        sa.Column("temp_min", sa.Float(), nullable=False),
        sa.Column("temp_preferred", sa.Float(), nullable=True),
        sa.Column("temp_max", sa.Float(), nullable=False),
        sa.Column("rh_min", sa.Float(), nullable=False),
        sa.Column("rh_preferred", sa.Float(), nullable=True),
        sa.Column("rh_max", sa.Float(), nullable=False),
        sa.Column("wind_speed_min", sa.Float(), nullable=False),
        sa.Column("wind_speed_preferred", sa.Float(), nullable=True),
        sa.Column("wind_speed_max", sa.Float(), nullable=False),
        sa.Column("ffmc_min", sa.Float(), nullable=True),
        sa.Column("ffmc_preferred", sa.Float(), nullable=True),
        sa.Column("ffmc_max", sa.Float(), nullable=True),
        sa.Column("dmc_min", sa.Float(), nullable=True),
        sa.Column("dmc_preferred", sa.Float(), nullable=True),
        sa.Column("dmc_max", sa.Float(), nullable=True),
        sa.Column("dc_min", sa.Float(), nullable=True),
        sa.Column("dc_preferred", sa.Float(), nullable=True),
        sa.Column("dc_max", sa.Float(), nullable=True),
        sa.Column("isi_min", sa.Float(), nullable=True),
        sa.Column("isi_preferred", sa.Float(), nullable=True),
        sa.Column("isi_max", sa.Float(), nullable=True),
        sa.Column("bui_min", sa.Float(), nullable=True),
        sa.Column("bui_preferred", sa.Float(), nullable=True),
        sa.Column("bui_max", sa.Float(), nullable=True),
        sa.Column("hfi_min", sa.Float(), nullable=False),
        sa.Column("hfi_preferred", sa.Float(), nullable=True),
        sa.Column("hfi_max", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fire_centre"],
            ["fire_centres.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Contains parameters related to a prescribed burn.",
    )
    op.create_index(
        "idx_fire_watch_burn_location",
        "fire_watch",
        ["burn_location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(op.f("ix_fire_watch_id"), "fire_watch", ["id"], unique=False)
    op.create_index(op.f("ix_fire_watch_status"), "fire_watch", ["status"], unique=False)
    op.create_table(
        "hfi_fire_centre_fire_start_range",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fire_start_range_id", sa.Integer(), nullable=False),
        sa.Column("fire_centre_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fire_centre_id"],
            ["fire_centres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fire_start_range_id"],
            ["hfi_fire_start_range.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fire_start_range_id", "fire_centre_id", name="unique_fire_start_range_for_fire_centre"
        ),
        comment="Link table for fire centre fire start ranges",
    )
    op.create_index(
        op.f("ix_hfi_fire_centre_fire_start_range_fire_centre_id"),
        "hfi_fire_centre_fire_start_range",
        ["fire_centre_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hfi_fire_centre_fire_start_range_fire_start_range_id"),
        "hfi_fire_centre_fire_start_range",
        ["fire_start_range_id"],
        unique=False,
    )
    op.create_table(
        "hfi_fire_start_lookup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fire_start_range_id", sa.Integer(), nullable=False),
        sa.Column("mean_intensity_group", sa.Integer(), nullable=False),
        sa.Column("prep_level", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fire_start_range_id"],
            ["hfi_fire_start_range.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Fire start mean intensity group prep level lookup",
    )
    op.create_index(
        op.f("ix_hfi_fire_start_lookup_fire_start_range_id"),
        "hfi_fire_start_lookup",
        ["fire_start_range_id"],
        unique=False,
    )
    op.create_table(
        "hfi_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fire_centre_id", sa.Integer(), nullable=False),
        sa.Column("prep_start_day", sa.Date(), nullable=False),
        sa.Column("prep_end_day", sa.Date(), nullable=False),
        sa.Column("create_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("create_user", sa.String(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fire_centre_id"],
            ["fire_centres.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fire_centre_id",
            "prep_start_day",
            "prep_end_day",
            "create_timestamp",
            name="unique_request_create_timestamp_for_fire_centre",
        ),
        comment="Identifies the unique code used to identify the station",
    )
    op.create_index(
        op.f("ix_hfi_request_create_timestamp"), "hfi_request", ["create_timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_hfi_request_fire_centre_id"), "hfi_request", ["fire_centre_id"], unique=False
    )
    op.create_index(
        op.f("ix_hfi_request_prep_end_day"), "hfi_request", ["prep_end_day"], unique=False
    )
    op.create_index(
        op.f("ix_hfi_request_prep_start_day"), "hfi_request", ["prep_start_day"], unique=False
    )
    op.create_table(
        "model_run_for_sfms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_model_id", sa.Integer(), nullable=False),
        sa.Column("model_run_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("create_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("update_date", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_model_id"],
            ["prediction_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Record to indicate numerical weather model data for SFMS has been downloaded and stored in S3.",
    )
    op.create_index(op.f("ix_model_run_for_sfms_id"), "model_run_for_sfms", ["id"], unique=False)
    op.create_index(
        op.f("ix_model_run_for_sfms_model_run_timestamp"),
        "model_run_for_sfms",
        ["model_run_timestamp"],
        unique=False,
    )
    op.create_table(
        "planning_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fire_centre_id", sa.Integer(), nullable=False),
        sa.Column("order_of_appearance_in_list", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fire_centre_id"],
            ["fire_centres.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_of_appearance_in_list",
            "fire_centre_id",
            name="unique_list_order_for_fire_centre_constraint",
        ),
        comment="Only one planning area can be assigned a position in the list for a fire centre",
    )
    op.create_index(
        op.f("ix_planning_areas_fire_centre_id"), "planning_areas", ["fire_centre_id"], unique=False
    )
    op.create_index(op.f("ix_planning_areas_id"), "planning_areas", ["id"], unique=False)
    op.create_index(op.f("ix_planning_areas_name"), "planning_areas", ["name"], unique=False)
    op.create_table(
        "prediction_model_grid_subsets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_model_id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prediction_model_id"],
            ["prediction_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prediction_model_id", "geom"),
        comment="Identify the vertices surrounding the area of interest",
    )
    op.create_index(
        "idx_prediction_model_grid_subsets_geom",
        "prediction_model_grid_subsets",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_prediction_model_grid_subsets_id"),
        "prediction_model_grid_subsets",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_model_grid_subsets_prediction_model_id"),
        "prediction_model_grid_subsets",
        ["prediction_model_id"],
        unique=False,
    )
    op.create_table(
        "prediction_model_run_timestamps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_model_id", sa.Integer(), nullable=False),
        sa.Column(
            "prediction_run_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False
        ),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("interpolated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_model_id"],
            ["prediction_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prediction_model_id", "prediction_run_timestamp"),
        comment="Identify which prediction model run (e.g.  2020 07 07 12:00).",
    )
    op.create_index(
        op.f("ix_prediction_model_run_timestamps_id"),
        "prediction_model_run_timestamps",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_model_run_timestamps_prediction_model_id"),
        "prediction_model_run_timestamps",
        ["prediction_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_model_run_timestamps_prediction_run_timestamp"),
        "prediction_model_run_timestamps",
        ["prediction_run_timestamp"],
        unique=False,
    )
    op.create_table(
        "advisory_elevation_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("minimum", sa.Float(), nullable=False),
        sa.Column("quartile_25", sa.Float(), nullable=False),
        sa.Column("median", sa.Float(), nullable=False),
        sa.Column("quartile_75", sa.Float(), nullable=False),
        sa.Column("maximum", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["threshold"],
            ["advisory_hfi_classification_threshold.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Elevation stats per fire shape by advisory threshold",
    )
    op.create_index(
        op.f("ix_advisory_elevation_stats_advisory_shape_id"),
        "advisory_elevation_stats",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_elevation_stats_id"), "advisory_elevation_stats", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_elevation_stats_run_parameters"),
        "advisory_elevation_stats",
        ["run_parameters"],
        unique=False,
    )
    op.create_table(
        "advisory_fuel_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("fuel_type", sa.Integer(), nullable=False),
        sa.Column("area", sa.Float(), nullable=False),
        sa.Column("fuel_type_raster_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type"],
            ["sfms_fuel_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type_raster_id"],
            ["fuel_type_raster.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["threshold"],
            ["advisory_hfi_classification_threshold.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("advisory_shape_id", "threshold", "run_parameters", "fuel_type"),
        comment="Fuel type stats per fire shape by advisory threshold",
    )
    op.create_index(
        op.f("ix_advisory_fuel_stats_advisory_shape_id"),
        "advisory_fuel_stats",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_fuel_stats_fuel_type"), "advisory_fuel_stats", ["fuel_type"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_fuel_stats_fuel_type_raster_id"),
        "advisory_fuel_stats",
        ["fuel_type_raster_id"],
        unique=False,
    )
    op.create_index(op.f("ix_advisory_fuel_stats_id"), "advisory_fuel_stats", ["id"], unique=False)
    op.create_index(
        op.f("ix_advisory_fuel_stats_run_parameters"),
        "advisory_fuel_stats",
        ["run_parameters"],
        unique=False,
    )
    op.create_table(
        "advisory_hfi_percent_conifer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("fuel_type", sa.Integer(), nullable=False),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("min_percent_conifer", sa.Integer(), nullable=True),
        sa.Column("fuel_type_raster_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type"],
            ["sfms_fuel_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type_raster_id"],
            ["fuel_type_raster.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Minimum percent conifer for HFI above advisory level, per fire zone. min_percent_conifer refers to the minimum percent of conifer trees in a fire zone that coincides with hfi pixels exceeding an HFI value of 4000.",
    )
    op.create_index(
        op.f("ix_advisory_hfi_percent_conifer_advisory_shape_id"),
        "advisory_hfi_percent_conifer",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_hfi_percent_conifer_fuel_type_raster_id"),
        "advisory_hfi_percent_conifer",
        ["fuel_type_raster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_hfi_percent_conifer_id"),
        "advisory_hfi_percent_conifer",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_hfi_percent_conifer_run_parameters"),
        "advisory_hfi_percent_conifer",
        ["run_parameters"],
        unique=False,
    )
    op.create_table(
        "advisory_hfi_wind_speed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("min_wind_speed", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["threshold"],
            ["advisory_hfi_classification_threshold.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Minimum wind speed for each HFI class, per fire zone. hfi_wind_speed refers to the minimum wind speed in a fire zone that coincides with hfi pixels meeting or exceeding a certain threshold.",
    )
    op.create_index(
        op.f("ix_advisory_hfi_wind_speed_advisory_shape_id"),
        "advisory_hfi_wind_speed",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_hfi_wind_speed_id"), "advisory_hfi_wind_speed", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_hfi_wind_speed_run_parameters"),
        "advisory_hfi_wind_speed",
        ["run_parameters"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_hfi_wind_speed_threshold"),
        "advisory_hfi_wind_speed",
        ["threshold"],
        unique=False,
    )
    op.create_table(
        "advisory_shape_fuels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("fuel_type", sa.Integer(), nullable=False),
        sa.Column("fuel_area", sa.Float(), nullable=False),
        sa.Column("fuel_type_raster_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type"],
            ["sfms_fuel_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type_raster_id"],
            ["fuel_type_raster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Fuel types and their areas in fire zone units.",
    )
    op.create_index(
        op.f("ix_advisory_shape_fuels_advisory_shape_id"),
        "advisory_shape_fuels",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_shape_fuels_fuel_type"),
        "advisory_shape_fuels",
        ["fuel_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_shape_fuels_fuel_type_raster_id"),
        "advisory_shape_fuels",
        ["fuel_type_raster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_shape_fuels_id"), "advisory_shape_fuels", ["id"], unique=False
    )
    op.create_table(
        "advisory_tpi_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("valley_bottom", sa.Integer(), nullable=False),
        sa.Column("mid_slope", sa.Integer(), nullable=False),
        sa.Column("upper_slope", sa.Integer(), nullable=False),
        sa.Column("pixel_size_metres", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Elevation TPI stats per fire shape",
    )
    op.create_index(
        op.f("ix_advisory_tpi_stats_advisory_shape_id"),
        "advisory_tpi_stats",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(op.f("ix_advisory_tpi_stats_id"), "advisory_tpi_stats", ["id"], unique=False)
    op.create_index(
        op.f("ix_advisory_tpi_stats_run_parameters"),
        "advisory_tpi_stats",
        ["run_parameters"],
        unique=False,
    )
    op.create_table(
        "advisory_zone_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("advisory_percentage", sa.Float(), nullable=True),
        sa.Column("warning_percentage", sa.Float(), nullable=True),
        sa.Column("fuel_type_raster_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type_raster_id"],
            ["fuel_type_raster.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_parameters", "advisory_shape_id", "fuel_type_raster_id"),
        comment="Status of zones (advisory/warning) for a given run parameter.",
    )
    op.create_index(
        op.f("ix_advisory_zone_status_advisory_shape_id"),
        "advisory_zone_status",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_zone_status_fuel_type_raster_id"),
        "advisory_zone_status",
        ["fuel_type_raster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_advisory_zone_status_id"), "advisory_zone_status", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_zone_status_run_parameters"),
        "advisory_zone_status",
        ["run_parameters"],
        unique=False,
    )
    op.create_table(
        "combustible_area",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("combustible_area", sa.Float(), nullable=False),
        sa.Column("fuel_type_raster_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type_raster_id"],
            ["fuel_type_raster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="The combustible area of advisory shapes for each unique fuel grid.",
    )
    op.create_index(
        op.f("ix_combustible_area_advisory_shape_id"),
        "combustible_area",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_combustible_area_fuel_type_raster_id"),
        "combustible_area",
        ["fuel_type_raster_id"],
        unique=False,
    )
    op.create_index(op.f("ix_combustible_area_id"), "combustible_area", ["id"], unique=False)
    op.create_table(
        "critical_hours",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column(
            "threshold",
            postgresql.ENUM("advisory", "warning", name="hficlassificationthresholdenum"),
            nullable=False,
        ),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("fuel_type", sa.Integer(), nullable=False),
        sa.Column("start_hour", sa.Integer(), nullable=False),
        sa.Column("end_hour", sa.Integer(), nullable=False),
        sa.Column("fuel_type_raster_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type"],
            ["sfms_fuel_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type_raster_id"],
            ["fuel_type_raster.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Critical hours by firezone unit, fuel type and sfms run parameters.",
    )
    op.create_index(
        op.f("ix_critical_hours_advisory_shape_id"),
        "critical_hours",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_critical_hours_fuel_type"), "critical_hours", ["fuel_type"], unique=False
    )
    op.create_index(
        op.f("ix_critical_hours_fuel_type_raster_id"),
        "critical_hours",
        ["fuel_type_raster_id"],
        unique=False,
    )
    op.create_index(op.f("ix_critical_hours_id"), "critical_hours", ["id"], unique=False)
    op.create_index(
        op.f("ix_critical_hours_run_parameters"), "critical_hours", ["run_parameters"], unique=False
    )
    op.create_table(
        "fire_watch_weather",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fire_watch_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("prediction_model_run_timestamp_id", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("relative_humidity", sa.Float(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("precip_24hr", sa.Float(), nullable=False),
        sa.Column("ffmc", sa.Float(), nullable=False),
        sa.Column("dmc", sa.Float(), nullable=False),
        sa.Column("dc", sa.Float(), nullable=False),
        sa.Column("isi", sa.Float(), nullable=False),
        sa.Column("bui", sa.Float(), nullable=False),
        sa.Column("hfi", sa.Float(), nullable=False),
        sa.Column("in_prescription", sa.Integer(), nullable=False),
        sa.Column("created_at", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fire_watch_id"],
            ["fire_watch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["in_prescription"],
            ["prescription_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prediction_model_run_timestamp_id"],
            ["prediction_model_run_timestamps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Contains weather forecasts and FWI/FBP indices related to a fire watch prescribed burn.",
    )
    op.create_index(
        op.f("ix_fire_watch_weather_date"), "fire_watch_weather", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_fire_watch_weather_fire_watch_id"),
        "fire_watch_weather",
        ["fire_watch_id"],
        unique=False,
    )
    op.create_index(op.f("ix_fire_watch_weather_id"), "fire_watch_weather", ["id"], unique=False)
    op.create_index(
        op.f("ix_fire_watch_weather_in_prescription"),
        "fire_watch_weather",
        ["in_prescription"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fire_watch_weather_prediction_model_run_timestamp_id"),
        "fire_watch_weather",
        ["prediction_model_run_timestamp_id"],
        unique=False,
    )
    op.create_table(
        "hfi_ready",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hfi_request_id", sa.Integer(), nullable=False),
        sa.Column("planning_area_id", sa.Integer(), nullable=False),
        sa.Column("ready", sa.Boolean(), nullable=False),
        sa.Column("create_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("create_user", sa.String(), nullable=False),
        sa.Column("update_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("update_user", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hfi_request_id"],
            ["hfi_request.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planning_area_id"],
            ["planning_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Marks whether a planning area is ready for a particular HFI Request",
    )
    op.create_index(
        op.f("ix_hfi_ready_create_timestamp"), "hfi_ready", ["create_timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_hfi_ready_hfi_request_id"), "hfi_ready", ["hfi_request_id"], unique=False
    )
    op.create_index(
        op.f("ix_hfi_ready_planning_area_id"), "hfi_ready", ["planning_area_id"], unique=False
    )
    op.create_index(op.f("ix_hfi_ready_ready"), "hfi_ready", ["ready"], unique=False)
    op.create_index(
        op.f("ix_hfi_ready_update_timestamp"), "hfi_ready", ["update_timestamp"], unique=False
    )
    op.create_table(
        "high_hfi_area",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("run_parameters", sa.Integer(), nullable=False),
        sa.Column("area", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_parameters"],
            ["run_parameters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["threshold"],
            ["advisory_hfi_classification_threshold.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Area under advisory/warning per fire zone. advisory_area refers to the total area in a fire zone with HFI values between 4000 - 10000 and warn_area refers to the total area in a fire zone with HFI values exceeding 10000.",
    )
    op.create_index(op.f("ix_high_hfi_area_id"), "high_hfi_area", ["id"], unique=False)
    op.create_index(
        op.f("ix_high_hfi_area_run_parameters"), "high_hfi_area", ["run_parameters"], unique=False
    )
    op.create_table(
        "model_run_grid_subset_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_model_run_timestamp_id", sa.Integer(), nullable=False),
        sa.Column("prediction_model_grid_subset_id", sa.Integer(), nullable=False),
        sa.Column(
            "prediction_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False
        ),
        sa.Column("tmp_tgl_2", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("rh_tgl_2", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("apcp_sfc_0", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("wdir_tgl_10", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("wind_tgl_10", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.ForeignKeyConstraint(
            ["prediction_model_grid_subset_id"],
            ["prediction_model_grid_subsets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prediction_model_run_timestamp_id"],
            ["prediction_model_run_timestamps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "prediction_model_run_timestamp_id",
            "prediction_model_grid_subset_id",
            "prediction_timestamp",
        ),
        comment="The prediction for a grid subset of a particular model run.",
    )
    op.create_index(
        op.f("ix_model_run_grid_subset_predictions_id"),
        "model_run_grid_subset_predictions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_run_grid_subset_predictions_prediction_model_grid_subset_id"),
        "model_run_grid_subset_predictions",
        ["prediction_model_grid_subset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_run_grid_subset_predictions_prediction_model_run_timestamp_id"),
        "model_run_grid_subset_predictions",
        ["prediction_model_run_timestamp_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_run_grid_subset_predictions_prediction_timestamp"),
        "model_run_grid_subset_predictions",
        ["prediction_timestamp"],
        unique=False,
    )
    op.create_table(
        "model_run_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_model_run_timestamp_id", sa.Integer(), nullable=False),
        sa.Column(
            "prediction_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False
        ),
        sa.Column("station_code", sa.Integer(), nullable=False),
        sa.Column("tmp_tgl_2", sa.Float(), nullable=True),
        sa.Column("rh_tgl_2", sa.Float(), nullable=True),
        sa.Column("apcp_sfc_0", sa.Float(), nullable=True),
        sa.Column("wdir_tgl_10", sa.Float(), nullable=True),
        sa.Column("wind_tgl_10", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prediction_model_run_timestamp_id"],
            ["prediction_model_run_timestamps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "prediction_model_run_timestamp_id", "prediction_timestamp", "station_code"
        ),
        comment="The prediction values of a particular model run.",
    )
    op.create_index(
        op.f("ix_model_run_predictions_id"), "model_run_predictions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_model_run_predictions_prediction_model_run_timestamp_id"),
        "model_run_predictions",
        ["prediction_model_run_timestamp_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_run_predictions_prediction_timestamp"),
        "model_run_predictions",
        ["prediction_timestamp"],
        unique=False,
    )
    op.create_table(
        "planning_weather_stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_code", sa.Integer(), nullable=False),
        sa.Column("fuel_type_id", sa.Integer(), nullable=False),
        sa.Column("planning_area_id", sa.Integer(), nullable=False),
        sa.Column("order_of_appearance_in_planning_area_list", sa.Integer(), nullable=True),
        sa.Column("create_user", sa.String(), nullable=False),
        sa.Column("create_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("update_user", sa.String(), nullable=False),
        sa.Column("update_timestamp", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fuel_type_id"],
            ["fuel_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planning_area_id"],
            ["planning_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_of_appearance_in_planning_area_list",
            "planning_area_id",
            name="unique_order_for_planning_area",
        ),
        comment="Identifies the unique code used to identify the station",
    )
    op.create_index(
        op.f("ix_planning_weather_stations_fuel_type_id"),
        "planning_weather_stations",
        ["fuel_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_planning_weather_stations_is_deleted"),
        "planning_weather_stations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_planning_weather_stations_planning_area_id"),
        "planning_weather_stations",
        ["planning_area_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_planning_weather_stations_station_code"),
        "planning_weather_stations",
        ["station_code"],
        unique=False,
    )
    op.create_index(
        "unique_non_deleted_station_per_planning_area",
        "planning_weather_stations",
        ["is_deleted", "station_code", "planning_area_id"],
        unique=True,
        postgresql_where="not is_deleted",
    )
    op.create_table(
        "tpi_fuel_area",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advisory_shape_id", sa.Integer(), nullable=False),
        sa.Column(
            "tpi_class",
            sa.Enum("valley_bottom", "mid_slope", "upper_slope", name="tpiclassenum"),
            nullable=False,
        ),
        sa.Column("fuel_area", sa.Float(), nullable=False),
        sa.Column("fuel_type_raster_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisory_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fuel_type_raster_id"],
            ["fuel_type_raster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Combustible area in each TPI class per fire zone unit.",
    )
    op.create_index(
        op.f("ix_tpi_fuel_area_advisory_shape_id"),
        "tpi_fuel_area",
        ["advisory_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tpi_fuel_area_fuel_type_raster_id"),
        "tpi_fuel_area",
        ["fuel_type_raster_id"],
        unique=False,
    )
    op.create_index(op.f("ix_tpi_fuel_area_id"), "tpi_fuel_area", ["id"], unique=False)
    # Create partitioned table for weather_station_model_predictions
    op.execute("""
        CREATE TABLE weather_station_model_predictions (
            id INTEGER NOT NULL,
            station_code INTEGER NOT NULL,
            prediction_model_run_timestamp_id INTEGER NOT NULL,
            prediction_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
            tmp_tgl_2 DOUBLE PRECISION,
            bias_adjusted_temperature DOUBLE PRECISION,
            rh_tgl_2 DOUBLE PRECISION,
            bias_adjusted_rh DOUBLE PRECISION,
            apcp_sfc_0 DOUBLE PRECISION,
            delta_precip DOUBLE PRECISION,
            wdir_tgl_10 DOUBLE PRECISION,
            bias_adjusted_wdir DOUBLE PRECISION,
            wind_tgl_10 DOUBLE PRECISION,
            bias_adjusted_wind_speed DOUBLE PRECISION,
            create_date TIMESTAMP WITH TIME ZONE NOT NULL,
            update_date TIMESTAMP WITH TIME ZONE NOT NULL,
            precip_24h DOUBLE PRECISION,
            bias_adjusted_precip_24h DOUBLE PRECISION,
            PRIMARY KEY (id, prediction_timestamp),
            FOREIGN KEY (prediction_model_run_timestamp_id) REFERENCES prediction_model_run_timestamps(id),
            UNIQUE (station_code, prediction_model_run_timestamp_id, prediction_timestamp)
        ) PARTITION BY RANGE (prediction_timestamp);
    """)

    op.execute("""
        COMMENT ON TABLE weather_station_model_predictions IS
        'The interpolated weather values for a weather station, weather date, and model run';
    """)

    # Create partitions
    op.execute("""
        CREATE TABLE weather_station_model_predictions_202405
        PARTITION OF weather_station_model_predictions
        FOR VALUES FROM ('2024-04-30 17:00:00-07') TO ('2024-05-31 17:00:00-07');
    """)

    op.execute("""
        CREATE TABLE weather_station_model_predictions_202510
        PARTITION OF weather_station_model_predictions
        FOR VALUES FROM ('2025-09-30 17:00:00-07') TO ('2025-10-31 17:00:00-07');
    """)

    op.execute("""
        CREATE TABLE weather_station_model_predictions_202511
        PARTITION OF weather_station_model_predictions
        FOR VALUES FROM ('2025-10-31 17:00:00-07') TO ('2025-11-30 16:00:00-08');
    """)

    op.execute("""
        CREATE TABLE weather_station_model_predictions_202512
        PARTITION OF weather_station_model_predictions
        FOR VALUES FROM ('2025-11-30 16:00:00-08') TO ('2025-12-31 16:00:00-08');
    """)

    op.execute("""
        CREATE TABLE weather_station_model_predictions_202601
        PARTITION OF weather_station_model_predictions
        FOR VALUES FROM ('2025-12-31 16:00:00-08') TO ('2026-01-31 16:00:00-08');
    """)

    # Create indexes (these apply to all partitions automatically)
    op.create_index(
        op.f("ix_weather_station_model_predictions_id"),
        "weather_station_model_predictions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_station_model_predictions_prediction_model_run_timestamp_id"),
        "weather_station_model_predictions",
        ["prediction_model_run_timestamp_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_station_model_predictions_prediction_timestamp"),
        "weather_station_model_predictions",
        ["prediction_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_station_model_predictions_station_code"),
        "weather_station_model_predictions",
        ["station_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_station_model_predictions_update_date"),
        "weather_station_model_predictions",
        ["update_date"],
        unique=False,
    )
    # NOTE: spatial_ref_sys is created and managed by PostGIS extension, don't drop it
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: spatial_ref_sys is managed by PostGIS extension, don't recreate it
    op.drop_index(
        op.f("ix_weather_station_model_predictions_update_date"),
        table_name="weather_station_model_predictions",
    )
    op.drop_index(
        op.f("ix_weather_station_model_predictions_station_code"),
        table_name="weather_station_model_predictions",
    )
    op.drop_index(
        op.f("ix_weather_station_model_predictions_prediction_timestamp"),
        table_name="weather_station_model_predictions",
    )
    op.drop_index(
        op.f("ix_weather_station_model_predictions_prediction_model_run_timestamp_id"),
        table_name="weather_station_model_predictions",
    )
    op.drop_index(
        op.f("ix_weather_station_model_predictions_id"),
        table_name="weather_station_model_predictions",
    )
    op.drop_table("weather_station_model_predictions")
    op.drop_index(op.f("ix_tpi_fuel_area_id"), table_name="tpi_fuel_area")
    op.drop_index(op.f("ix_tpi_fuel_area_fuel_type_raster_id"), table_name="tpi_fuel_area")
    op.drop_index(op.f("ix_tpi_fuel_area_advisory_shape_id"), table_name="tpi_fuel_area")
    op.drop_table("tpi_fuel_area")
    op.drop_index(
        "unique_non_deleted_station_per_planning_area",
        table_name="planning_weather_stations",
        postgresql_where="not is_deleted",
    )
    op.drop_index(
        op.f("ix_planning_weather_stations_station_code"), table_name="planning_weather_stations"
    )
    op.drop_index(
        op.f("ix_planning_weather_stations_planning_area_id"),
        table_name="planning_weather_stations",
    )
    op.drop_index(
        op.f("ix_planning_weather_stations_is_deleted"), table_name="planning_weather_stations"
    )
    op.drop_index(
        op.f("ix_planning_weather_stations_fuel_type_id"), table_name="planning_weather_stations"
    )
    op.drop_table("planning_weather_stations")
    op.drop_index(
        op.f("ix_model_run_predictions_prediction_timestamp"), table_name="model_run_predictions"
    )
    op.drop_index(
        op.f("ix_model_run_predictions_prediction_model_run_timestamp_id"),
        table_name="model_run_predictions",
    )
    op.drop_index(op.f("ix_model_run_predictions_id"), table_name="model_run_predictions")
    op.drop_table("model_run_predictions")
    op.drop_index(
        op.f("ix_model_run_grid_subset_predictions_prediction_timestamp"),
        table_name="model_run_grid_subset_predictions",
    )
    op.drop_index(
        op.f("ix_model_run_grid_subset_predictions_prediction_model_run_timestamp_id"),
        table_name="model_run_grid_subset_predictions",
    )
    op.drop_index(
        op.f("ix_model_run_grid_subset_predictions_prediction_model_grid_subset_id"),
        table_name="model_run_grid_subset_predictions",
    )
    op.drop_index(
        op.f("ix_model_run_grid_subset_predictions_id"),
        table_name="model_run_grid_subset_predictions",
    )
    op.drop_table("model_run_grid_subset_predictions")
    op.drop_index(op.f("ix_high_hfi_area_run_parameters"), table_name="high_hfi_area")
    op.drop_index(op.f("ix_high_hfi_area_id"), table_name="high_hfi_area")
    op.drop_table("high_hfi_area")
    op.drop_index(op.f("ix_hfi_ready_update_timestamp"), table_name="hfi_ready")
    op.drop_index(op.f("ix_hfi_ready_ready"), table_name="hfi_ready")
    op.drop_index(op.f("ix_hfi_ready_planning_area_id"), table_name="hfi_ready")
    op.drop_index(op.f("ix_hfi_ready_hfi_request_id"), table_name="hfi_ready")
    op.drop_index(op.f("ix_hfi_ready_create_timestamp"), table_name="hfi_ready")
    op.drop_table("hfi_ready")
    op.drop_index(
        op.f("ix_fire_watch_weather_prediction_model_run_timestamp_id"),
        table_name="fire_watch_weather",
    )
    op.drop_index(op.f("ix_fire_watch_weather_in_prescription"), table_name="fire_watch_weather")
    op.drop_index(op.f("ix_fire_watch_weather_id"), table_name="fire_watch_weather")
    op.drop_index(op.f("ix_fire_watch_weather_fire_watch_id"), table_name="fire_watch_weather")
    op.drop_index(op.f("ix_fire_watch_weather_date"), table_name="fire_watch_weather")
    op.drop_table("fire_watch_weather")
    op.drop_index(op.f("ix_critical_hours_run_parameters"), table_name="critical_hours")
    op.drop_index(op.f("ix_critical_hours_id"), table_name="critical_hours")
    op.drop_index(op.f("ix_critical_hours_fuel_type_raster_id"), table_name="critical_hours")
    op.drop_index(op.f("ix_critical_hours_fuel_type"), table_name="critical_hours")
    op.drop_index(op.f("ix_critical_hours_advisory_shape_id"), table_name="critical_hours")
    op.drop_table("critical_hours")
    op.drop_index(op.f("ix_combustible_area_id"), table_name="combustible_area")
    op.drop_index(op.f("ix_combustible_area_fuel_type_raster_id"), table_name="combustible_area")
    op.drop_index(op.f("ix_combustible_area_advisory_shape_id"), table_name="combustible_area")
    op.drop_table("combustible_area")
    op.drop_index(op.f("ix_advisory_zone_status_run_parameters"), table_name="advisory_zone_status")
    op.drop_index(op.f("ix_advisory_zone_status_id"), table_name="advisory_zone_status")
    op.drop_index(
        op.f("ix_advisory_zone_status_fuel_type_raster_id"), table_name="advisory_zone_status"
    )
    op.drop_index(
        op.f("ix_advisory_zone_status_advisory_shape_id"), table_name="advisory_zone_status"
    )
    op.drop_table("advisory_zone_status")
    op.drop_index(op.f("ix_advisory_tpi_stats_run_parameters"), table_name="advisory_tpi_stats")
    op.drop_index(op.f("ix_advisory_tpi_stats_id"), table_name="advisory_tpi_stats")
    op.drop_index(op.f("ix_advisory_tpi_stats_advisory_shape_id"), table_name="advisory_tpi_stats")
    op.drop_table("advisory_tpi_stats")
    op.drop_index(op.f("ix_advisory_shape_fuels_id"), table_name="advisory_shape_fuels")
    op.drop_index(
        op.f("ix_advisory_shape_fuels_fuel_type_raster_id"), table_name="advisory_shape_fuels"
    )
    op.drop_index(op.f("ix_advisory_shape_fuels_fuel_type"), table_name="advisory_shape_fuels")
    op.drop_index(
        op.f("ix_advisory_shape_fuels_advisory_shape_id"), table_name="advisory_shape_fuels"
    )
    op.drop_table("advisory_shape_fuels")
    op.drop_index(
        op.f("ix_advisory_hfi_wind_speed_threshold"), table_name="advisory_hfi_wind_speed"
    )
    op.drop_index(
        op.f("ix_advisory_hfi_wind_speed_run_parameters"), table_name="advisory_hfi_wind_speed"
    )
    op.drop_index(op.f("ix_advisory_hfi_wind_speed_id"), table_name="advisory_hfi_wind_speed")
    op.drop_index(
        op.f("ix_advisory_hfi_wind_speed_advisory_shape_id"), table_name="advisory_hfi_wind_speed"
    )
    op.drop_table("advisory_hfi_wind_speed")
    op.drop_index(
        op.f("ix_advisory_hfi_percent_conifer_run_parameters"),
        table_name="advisory_hfi_percent_conifer",
    )
    op.drop_index(
        op.f("ix_advisory_hfi_percent_conifer_id"), table_name="advisory_hfi_percent_conifer"
    )
    op.drop_index(
        op.f("ix_advisory_hfi_percent_conifer_fuel_type_raster_id"),
        table_name="advisory_hfi_percent_conifer",
    )
    op.drop_index(
        op.f("ix_advisory_hfi_percent_conifer_advisory_shape_id"),
        table_name="advisory_hfi_percent_conifer",
    )
    op.drop_table("advisory_hfi_percent_conifer")
    op.drop_index(op.f("ix_advisory_fuel_stats_run_parameters"), table_name="advisory_fuel_stats")
    op.drop_index(op.f("ix_advisory_fuel_stats_id"), table_name="advisory_fuel_stats")
    op.drop_index(
        op.f("ix_advisory_fuel_stats_fuel_type_raster_id"), table_name="advisory_fuel_stats"
    )
    op.drop_index(op.f("ix_advisory_fuel_stats_fuel_type"), table_name="advisory_fuel_stats")
    op.drop_index(
        op.f("ix_advisory_fuel_stats_advisory_shape_id"), table_name="advisory_fuel_stats"
    )
    op.drop_table("advisory_fuel_stats")
    op.drop_index(
        op.f("ix_advisory_elevation_stats_run_parameters"), table_name="advisory_elevation_stats"
    )
    op.drop_index(op.f("ix_advisory_elevation_stats_id"), table_name="advisory_elevation_stats")
    op.drop_index(
        op.f("ix_advisory_elevation_stats_advisory_shape_id"), table_name="advisory_elevation_stats"
    )
    op.drop_table("advisory_elevation_stats")
    op.drop_index(
        op.f("ix_prediction_model_run_timestamps_prediction_run_timestamp"),
        table_name="prediction_model_run_timestamps",
    )
    op.drop_index(
        op.f("ix_prediction_model_run_timestamps_prediction_model_id"),
        table_name="prediction_model_run_timestamps",
    )
    op.drop_index(
        op.f("ix_prediction_model_run_timestamps_id"), table_name="prediction_model_run_timestamps"
    )
    op.drop_table("prediction_model_run_timestamps")
    op.drop_index(
        op.f("ix_prediction_model_grid_subsets_prediction_model_id"),
        table_name="prediction_model_grid_subsets",
    )
    op.drop_index(
        op.f("ix_prediction_model_grid_subsets_id"), table_name="prediction_model_grid_subsets"
    )
    op.drop_index(
        "idx_prediction_model_grid_subsets_geom",
        table_name="prediction_model_grid_subsets",
        postgresql_using="gist",
    )
    op.drop_table("prediction_model_grid_subsets")
    op.drop_index(op.f("ix_planning_areas_name"), table_name="planning_areas")
    op.drop_index(op.f("ix_planning_areas_id"), table_name="planning_areas")
    op.drop_index(op.f("ix_planning_areas_fire_centre_id"), table_name="planning_areas")
    op.drop_table("planning_areas")
    op.drop_index(
        op.f("ix_model_run_for_sfms_model_run_timestamp"), table_name="model_run_for_sfms"
    )
    op.drop_index(op.f("ix_model_run_for_sfms_id"), table_name="model_run_for_sfms")
    op.drop_table("model_run_for_sfms")
    op.drop_index(op.f("ix_hfi_request_prep_start_day"), table_name="hfi_request")
    op.drop_index(op.f("ix_hfi_request_prep_end_day"), table_name="hfi_request")
    op.drop_index(op.f("ix_hfi_request_fire_centre_id"), table_name="hfi_request")
    op.drop_index(op.f("ix_hfi_request_create_timestamp"), table_name="hfi_request")
    op.drop_table("hfi_request")
    op.drop_index(
        op.f("ix_hfi_fire_start_lookup_fire_start_range_id"), table_name="hfi_fire_start_lookup"
    )
    op.drop_table("hfi_fire_start_lookup")
    op.drop_index(
        op.f("ix_hfi_fire_centre_fire_start_range_fire_start_range_id"),
        table_name="hfi_fire_centre_fire_start_range",
    )
    op.drop_index(
        op.f("ix_hfi_fire_centre_fire_start_range_fire_centre_id"),
        table_name="hfi_fire_centre_fire_start_range",
    )
    op.drop_table("hfi_fire_centre_fire_start_range")
    op.drop_index(op.f("ix_fire_watch_status"), table_name="fire_watch")
    op.drop_index(op.f("ix_fire_watch_id"), table_name="fire_watch")
    op.drop_index("idx_fire_watch_burn_location", table_name="fire_watch", postgresql_using="gist")
    op.drop_table("fire_watch")
    op.drop_index(op.f("ix_advisory_shapes_source_identifier"), table_name="advisory_shapes")
    op.drop_index(op.f("ix_advisory_shapes_shape_type"), table_name="advisory_shapes")
    op.drop_index(op.f("ix_advisory_shapes_fire_centre"), table_name="advisory_shapes")
    op.drop_index("idx_advisory_shapes_geom", table_name="advisory_shapes", postgresql_using="gist")
    op.drop_table("advisory_shapes")
    op.drop_index(op.f("ix_advisory_fuel_types_id"), table_name="advisory_fuel_types")
    op.drop_index(
        op.f("ix_advisory_fuel_types_fuel_type_raster_id"), table_name="advisory_fuel_types"
    )
    op.drop_index(op.f("ix_advisory_fuel_types_fuel_type_id"), table_name="advisory_fuel_types")
    op.drop_index(
        "idx_advisory_fuel_types_geom", table_name="advisory_fuel_types", postgresql_using="gist"
    )
    op.drop_table("advisory_fuel_types")
    op.drop_index(
        op.f("ix_advisory_classified_hfi_threshold"), table_name="advisory_classified_hfi"
    )
    op.drop_index(op.f("ix_advisory_classified_hfi_run_type"), table_name="advisory_classified_hfi")
    op.drop_index(op.f("ix_advisory_classified_hfi_id"), table_name="advisory_classified_hfi")
    op.drop_index(
        "idx_advisory_classified_hfi_geom",
        table_name="advisory_classified_hfi",
        postgresql_using="gist",
    )
    op.drop_table("advisory_classified_hfi")
    op.drop_index(op.f("ix_sfms_fuel_types_id"), table_name="sfms_fuel_types")
    op.drop_index(op.f("ix_sfms_fuel_types_fuel_type_id"), table_name="sfms_fuel_types")
    op.drop_table("sfms_fuel_types")
    op.drop_index(
        op.f("ix_saved_model_run_for_sfms_urls_url"), table_name="saved_model_run_for_sfms_urls"
    )
    op.drop_index(
        op.f("ix_saved_model_run_for_sfms_urls_s3_key"), table_name="saved_model_run_for_sfms_urls"
    )
    op.drop_index(
        op.f("ix_saved_model_run_for_sfms_urls_id"), table_name="saved_model_run_for_sfms_urls"
    )
    op.drop_table("saved_model_run_for_sfms_urls")
    op.drop_index(op.f("ix_run_parameters_run_type"), table_name="run_parameters")
    op.drop_index(op.f("ix_run_parameters_run_datetime"), table_name="run_parameters")
    op.drop_index(op.f("ix_run_parameters_id"), table_name="run_parameters")
    op.drop_index(op.f("ix_run_parameters_for_date"), table_name="run_parameters")
    op.drop_table("run_parameters")
    op.drop_index(op.f("ix_processed_snow_snow_source"), table_name="processed_snow")
    op.drop_index(op.f("ix_processed_snow_processed_date"), table_name="processed_snow")
    op.drop_index(op.f("ix_processed_snow_id"), table_name="processed_snow")
    op.drop_index(op.f("ix_processed_snow_for_date"), table_name="processed_snow")
    op.drop_table("processed_snow")
    op.drop_index(op.f("ix_processed_model_run_urls_url"), table_name="processed_model_run_urls")
    op.drop_index(op.f("ix_processed_model_run_urls_id"), table_name="processed_model_run_urls")
    op.drop_table("processed_model_run_urls")
    op.drop_index(op.f("ix_prescription_status_id"), table_name="prescription_status")
    op.drop_table("prescription_status")
    op.drop_index(op.f("ix_prediction_models_id"), table_name="prediction_models")
    op.drop_index(op.f("ix_prediction_models_abbreviation"), table_name="prediction_models")
    op.drop_table("prediction_models")
    op.drop_index(op.f("ix_percent_grass_curing_station_code"), table_name="percent_grass_curing")
    op.drop_index(op.f("ix_percent_grass_curing_id"), table_name="percent_grass_curing")
    op.drop_index(op.f("ix_percent_grass_curing_for_date"), table_name="percent_grass_curing")
    op.drop_table("percent_grass_curing")
    op.drop_index(op.f("ix_noon_forecasts_wfwx_update_date"), table_name="noon_forecasts")
    op.drop_index(op.f("ix_noon_forecasts_weather_date"), table_name="noon_forecasts")
    op.drop_index(op.f("ix_noon_forecasts_station_code"), table_name="noon_forecasts")
    op.drop_index(op.f("ix_noon_forecasts_created_at"), table_name="noon_forecasts")
    op.drop_table("noon_forecasts")
    op.drop_index(op.f("ix_morecast_forecast_wind_speed"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_wind_direction"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_update_timestamp"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_temp"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_station_code"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_rh"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_precip"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_id"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_grass_curing"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_for_date"), table_name="morecast_forecast")
    op.drop_index(op.f("ix_morecast_forecast_create_timestamp"), table_name="morecast_forecast")
    op.drop_table("morecast_forecast")
    op.drop_index(
        op.f("ix_morecast_2_materialized_view_update_date"),
        table_name="morecast_2_materialized_view",
    )
    op.drop_index(
        op.f("ix_morecast_2_materialized_view_station_code"),
        table_name="morecast_2_materialized_view",
    )
    op.drop_index(
        op.f("ix_morecast_2_materialized_view_prediction_timestamp"),
        table_name="morecast_2_materialized_view",
    )
    op.drop_index(
        op.f("ix_morecast_2_materialized_view_id"), table_name="morecast_2_materialized_view"
    )
    op.drop_table("morecast_2_materialized_view")
    op.drop_index(op.f("ix_hourly_actuals_weather_date"), table_name="hourly_actuals")
    op.drop_index(op.f("ix_hourly_actuals_temp_valid"), table_name="hourly_actuals")
    op.drop_index(op.f("ix_hourly_actuals_station_code"), table_name="hourly_actuals")
    op.drop_index(op.f("ix_hourly_actuals_rh_valid"), table_name="hourly_actuals")
    op.drop_table("hourly_actuals")
    op.drop_table("hfi_fire_start_range")
    op.drop_index(op.f("ix_fuel_types_id"), table_name="fuel_types")
    op.drop_index(op.f("ix_fuel_types_abbrev"), table_name="fuel_types")
    op.drop_table("fuel_types")
    op.drop_table("fuel_type_raster")
    op.drop_index(op.f("ix_fire_centres_name"), table_name="fire_centres")
    op.drop_index(op.f("ix_fire_centres_id"), table_name="fire_centres")
    op.drop_table("fire_centres")
    op.drop_index(op.f("ix_api_access_audits_path"), table_name="api_access_audits")
    op.drop_index(op.f("ix_api_access_audits_create_user"), table_name="api_access_audits")
    op.drop_index(op.f("ix_api_access_audits_create_timestamp"), table_name="api_access_audits")
    op.drop_table("api_access_audits")
    op.drop_index(op.f("ix_advisory_shape_types_name"), table_name="advisory_shape_types")
    op.drop_table("advisory_shape_types")
    op.drop_index(
        op.f("ix_advisory_hfi_classification_threshold_id"),
        table_name="advisory_hfi_classification_threshold",
    )
    op.drop_table("advisory_hfi_classification_threshold")
    op.drop_table("application_data_tables")
    # ### end Alembic commands ###
