"""notification_settings

Revision ID: e2d8fc626235
Revises: 7d2194c5051e
Create Date: 2026-03-12 10:43:08.127704

"""

import sqlalchemy as sa
import wps_shared.db.models.common
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2d8fc626235"
down_revision = "7d2194c5051e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_token_id", sa.Integer(), nullable=False),
        sa.Column("fire_shape_id", sa.Integer(), nullable=False),
        sa.Column("created_at", wps_shared.db.models.common.TZTimeStamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_token_id"],
            ["device_token.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fire_shape_id"],
            ["advisory_shapes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_token_id", "fire_shape_id"),
        comment="Zone-level notification subscriptions per device.",
    )
    op.create_index(
        op.f("ix_notification_settings_device_token_id"),
        "notification_settings",
        ["device_token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_settings_fire_shape_id"),
        "notification_settings",
        ["fire_shape_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_settings_id"), "notification_settings", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_settings_id"), table_name="notification_settings")
    op.drop_index(
        op.f("ix_notification_settings_fire_shape_id"), table_name="notification_settings"
    )
    op.drop_index(
        op.f("ix_notification_settings_device_token_id"), table_name="notification_settings"
    )
    op.drop_table("notification_settings")
    # ### end Alembic commands ###
