"""Add bias adj wind cols to mat view

Revision ID: f6400f2140b9
Revises: b8aa2d38e9e1
Create Date: 2023-08-11 15:13:36.038941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6400f2140b9'
down_revision = 'b8aa2d38e9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.execute("DROP MATERIALIZED VIEW morecast_2_materialized_view;")
    op.execute("""
               CREATE MATERIALIZED VIEW morecast_2_materialized_view AS
            SELECT weather_station_model_predictions.prediction_timestamp, prediction_models.abbreviation, weather_station_model_predictions.station_code, 
                weather_station_model_predictions.rh_tgl_2, weather_station_model_predictions.tmp_tgl_2, weather_station_model_predictions.bias_adjusted_temperature,
                weather_station_model_predictions.bias_adjusted_rh, weather_station_model_predictions.apcp_sfc_0, weather_station_model_predictions.wdir_tgl_10, 
                weather_station_model_predictions.wind_tgl_10, weather_station_model_predictions.bias_adjusted_wind_speed, weather_station_model_predictions.bias_adjusted_wdir,
                weather_station_model_predictions.update_date
            FROM weather_station_model_predictions
            JOIN prediction_model_run_timestamps
            ON weather_station_model_predictions.prediction_model_run_timestamp_id = prediction_model_run_timestamps.id JOIN prediction_models
            ON prediction_model_run_timestamps.prediction_model_id = prediction_models.id
            JOIN (
            SELECT max(weather_station_model_predictions.prediction_timestamp) AS latest_prediction, weather_station_model_predictions.station_code AS station_code,
            date(weather_station_model_predictions.prediction_timestamp) AS unique_day
            FROM weather_station_model_predictions
            WHERE date_part('hour', weather_station_model_predictions.prediction_timestamp) = 20
            GROUP BY weather_station_model_predictions.station_code, date(weather_station_model_predictions.prediction_timestamp)
            ) AS latest
            ON weather_station_model_predictions.prediction_timestamp = latest.latest_prediction AND weather_station_model_predictions.station_code = latest.station_code
            ORDER BY weather_station_model_predictions.update_date DESC;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP MATERIALIZED VIEW morecast_2_materialized_view;")
    op.execute("""CREATE MATERIALIZED VIEW morecast_2_materialized_view AS 
               SELECT weather_station_model_predictions.prediction_timestamp, prediction_models.abbreviation, weather_station_model_predictions.station_code, weather_station_model_predictions.rh_tgl_2, weather_station_model_predictions.tmp_tgl_2, weather_station_model_predictions.bias_adjusted_temperature, weather_station_model_predictions.bias_adjusted_rh, weather_station_model_predictions.apcp_sfc_0, weather_station_model_predictions.wdir_tgl_10, weather_station_model_predictions.wind_tgl_10, weather_station_model_predictions.update_date 
               FROM weather_station_model_predictions 
               JOIN prediction_model_run_timestamps 
               ON weather_station_model_predictions.prediction_model_run_timestamp_id = prediction_model_run_timestamps.id JOIN prediction_models 
               ON prediction_model_run_timestamps.prediction_model_id = prediction_models.id 
               JOIN ( 
               SELECT max(weather_station_model_predictions.prediction_timestamp) AS latest_prediction, weather_station_model_predictions.station_code AS station_code, 
               date(weather_station_model_predictions.prediction_timestamp) AS unique_day 
               FROM weather_station_model_predictions 
               WHERE date_part('hour', weather_station_model_predictions.prediction_timestamp) = 20 
               GROUP BY weather_station_model_predictions.station_code, date(weather_station_model_predictions.prediction_timestamp) 
               ) AS latest 
               ON weather_station_model_predictions.prediction_timestamp = latest.latest_prediction AND weather_station_model_predictions.station_code = latest.station_code 
               ORDER BY weather_station_model_predictions.update_date DESC;""")
    # ### end Alembic commands ###
