apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    openshift.io/display-name: "wps-web" 
    description: "Wildfire Predictive Services - Fire Weather Index"  
    openshift.io/long-description: "Wildfire Predictive Services - Fire Weather Index" 
    tags: "wps,wps-web" 
    iconClass: icon-js 
    openshift.io/provider-display-name: "Government of British Columbia" 
    openshift.io/documentation-url: "https://github.com/bcgov/wps-web" 
    openshift.io/support-url: "https://github.com/bcgov/wps-web"
labels:
  app.kubernetes.io/part-of: "${NAME}"
parameters:
- name: NAME
  description: Module name
  value: wps-web
- name: SUFFIX
  description: Deployment suffix, e.g. pr-###
  required: true
- name: GIT_URL
  value: https://github.com/bcgov/wps-web.git
- name: GIT_BRANCH
  description: PR branch
  required: true
- name: API_BASE_URL
  value: "https://wps-api-prod.pathfinder.gov.bc.ca"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ${NAME}-${SUFFIX}
        common: "true"
      name: ${NAME}-${SUFFIX}-s2i
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}-source
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}-source
    spec:
      runPolicy: Parallel
      completionDeadlineSeconds: 1200 # 20 minutes
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-${SUFFIX}-source:latest
      resources:
        limits:
          cpu: "2"
          memory: 5Gi
        requests:
          cpu: "1"
          memory: 1Gi
      source:
        git:
          uri: ${GIT_URL}
          ref: ${GIT_BRANCH}
        type: Git
      strategy:
        sourceStrategy:
          env:
            - name: PORT
              value: "8080"
            - name: REACT_APP_API_BASE_URL
              value: ${API_BASE_URL}
            - name: BUILD_LOGLEVEL
              value: "5"
          from:
            kind: ImageStreamTag
            name: nodejs:10
            namespace: openshift
        type: Source
      triggers:
        - type: ConfigChange
        - type: ImageChange
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}-s2i
    spec:
      runPolicy: SerialLatestOnly
      completionDeadlineSeconds: 600 # 10 minutes
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-${SUFFIX}-s2i:latest
      resources:
        limits:
          cpu: "2"
          memory: 5Gi
        requests:
          cpu: "1"
          memory: 1Gi
      source:
        dockerfile: |-
          FROM bcgov-s2i-caddy
          COPY build /var/www/html/
        images:
          - from:
              kind: ImageStreamTag
              name: ${NAME}-${SUFFIX}-source:latest
            paths:
              - destinationDir: "./"
                sourcePath: /opt/app-root/src/build
        type: Dockerfile
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: bcgov-s2i-caddy:latest
            namespace: openshift
        type: Docker
      triggers:
        - type: ConfigChange
        - type: ImageChange
