apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    openshift.io/display-name: "wps"
    description: "Wildfire Predictive Services - API"
    openshift.io/long-description: "Wildfire Predictive Services - API"
    tags: "wps"
    iconClass: icon-js
    openshift.io/provider-display-name: "Government of British Columbia"
    openshift.io/documentation-url: "https://github.com/bcgov/wps"
    openshift.io/support-url: "https://github.com/bcgov/wps"
labels:
  app.kubernetes.io/part-of: "${NAME}"
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Module name
    value: ${NAME}
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-### or prod
    required: true
  - name: GIT_URL
    value: https://github.com/bcgov/wps.git
  - name: GIT_BRANCH
    description: PR branch
    required: true
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ${NAME}-${SUFFIX}
        common: "true"
      name: ${NAME}-${SUFFIX}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      completionDeadlineSeconds: 1200 # 20 minutes
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-${SUFFIX}:${SUFFIX}
      resources:
        limits:
          cpu: "4"
          memory: 5Gi
        requests:
          cpu: "2"
          memory: 1Gi
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: origin/${GIT_BRANCH}
        contextDir: ./
      strategy:
        dockerStrategy:
          # when npm run build executes, it will replace node tags with
          # python jinja tags using these environment variables.
          env:
            - name: "REACT_APP_KEYCLOAK_AUTH_URL"
              value: "{{REACT_APP_KEYCLOAK_AUTH_URL}}"
            - name: "REACT_APP_KEYCLOAK_REALM"
              value: "{{REACT_APP_KEYCLOAK_REALM}}"
            - name: "REACT_APP_KEYCLOAK_CLIENT"
              value: "{{REACT_APP_KEYCLOAK_CLIENT}}"
            - name: "REACT_APP_MATOMO_URL"
              value: "{{REACT_APP_MATOMO_URL}}"
            - name: "REACT_APP_MATOMO_SITE_ID"
              value: "{{REACT_APP_MATOMO_SITE_ID}}"
            - name: "REACT_APP_MATOMO_CONTAINER"
              value: "{{REACT_APP_MATOMO_CONTAINER}}"
      triggers: []
