kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${JOB_NAME}-cronjob-template
  annotations:
    description: "Scheduled task to run c-haines."
    tags: "cronjob,c-haines"
labels:
  app.kubernetes.io/part-of: "${NAME}"
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Module name
    value: wps
  - name: IMAGE_REGISTRY
    description: Image registry for imagestream.
    value: image-registry.openshift-image-registry.svc:5000
    required: true
  - name: IMAGE_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: GLOBAL_NAME
    description: Name of global Module
    value: wps-global
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: PROJ_TOOLS
    required: true
  - name: JOB_NAME
    value: c-haines
  - name: SCHEDULE
    value: "27 * * * *"
    required: true
  - name: POSTGRES_USER
    required: true
  - name: POSTGRES_DATABASE
    required: true
  - name: CRUNCHYDB_USER
    required: true
  - name: APP_LABEL
    required: true
objects:
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      name: ${JOB_NAME}
      labels:
        cronjob: ${JOB_NAME}
    spec:
      schedule: ${SCHEDULE}
      concurrencyPolicy: "Replace"
      jobTemplate:
        metadata:
          labels:
            cronjob: ${JOB_NAME}
            app: ${APP_LABEL}
        spec:
          template:
            spec:
              containers:
                - name: ${JOB_NAME}
                  resources:
                    limits:
                      cpu: "250m"
                      memory: 2Gi
                    requests:
                      cpu: "75m"
                      memory: 1Gi
                  image: ${IMAGE_REGISTRY}/${PROJ_TOOLS}/${NAME}-api-${SUFFIX}:${SUFFIX}
                  imagePullPolicy: "Always"
                  command:
                    [
                      "uv",
                      "run",
                      "--package",
                      "wps-api",
                      "--no-sync",
                      "python",
                      "-m",
                      "app.c_haines.worker",
                    ]
                  env:
                    - name: UV_NO_CACHE
                      value: "1"
                    - name: POSTGRES_READ_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: user
                    - name: POSTGRES_WRITE_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: user
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: password
                    - name: POSTGRES_WRITE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-host
                    - name: POSTGRES_READ_HOST
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-host
                    - name: POSTGRES_PORT
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-port
                    - name: POSTGRES_DATABASE
                      value: ${POSTGRES_DATABASE}
                    - name: MAX_WEEKS_C_HAINES
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.max-weeks-c-haines
                    - name: ROCKET_URL_POST_MESSAGE
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-url-post-message
                    - name: ROCKET_CHANNEL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-channel
                    - name: ROCKET_USER_ID
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-user-id-secret
                    - name: ROCKET_AUTH_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-auth-token-secret
                    - name: OBJECT_STORE_SERVER
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: object-store-server
                    - name: OBJECT_STORE_USER_ID
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: object-store-user-id
                    - name: OBJECT_STORE_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: object-store-secret
                    - name: OBJECT_STORE_BUCKET
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: object-store-bucket
                    - name: REDIS_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-host
                    - name: REDIS_PORT
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-port
                    - name: REDIS_USE
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-use
                    - name: REDIS_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: wps-redis
                          key: database-password
                    - name: REDIS_STATION_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-station-cache-expiry
                    - name: REDIS_AUTH_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-auth-cache-expiry
                    - name: REDIS_DAILIES_BY_STATION_CODE_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-dailies-by-station-code-expiry
                    - name: REDIS_CACHE_ENV_CANADA
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-cache-env-canada
              restartPolicy: OnFailure
