apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APP_NAME}-${SUFFIX}
  annotations:
    "openshift.io/display-name": ${APP_NAME}-${SUFFIX}
labels:
  app.kubernetes.io/part-of: "${APP_NAME}"
  app: ${APP_NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: |
      The name of the application for labelling all artifacts.
    displayName: Application Name
    required: true
  - name: PARENT_NAME
    description: |
      The name of the primary application that uses this database.
    displayName: Parent Application Name
    required: true
  - name: APP_USER
    description: Username for database.
    displayName: Username for database.
    required: true
  - description: Namespace in which database resides
    displayName: Target Namespace
    name: TARGET_NAMESPACE
    required: true
  - name: APP_NAME
    description: Application name (wps - wildfire predictive services)
    value: wps-crunchydb
    required: true
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: IMAGE_REGISTRY
    value: image-registry.apps.silver.devops.gov.bc.ca
  - name: IMAGE_NAMESPACE
    value: e1e498-tools
objects:
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    kind: PostgresCluster
    metadata:
      name: ${APP_NAME}-${SUFFIX}
    spec:
      image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres-gis:ubi8-14.7-3.2-0
      metadata:
        name: ${APP_NAME}-${SUFFIX}
        labels:
          app: ${APP_NAME}-${SUFFIX}
      customTLSSecret:
        name: custom.tls
      customReplicationTLSSecret:
        name: custom.tls
      standby:
        enabled: true
        host: "patroni-wps-test-leader.e1e498-dev.svc.cluster.local"
        port: 5432
      users:
        - name: ${APP_NAME}-${SUFFIX}
          databases:
            - postgres
          options: "SUPERUSER"
      postgresVersion: 14
      instances:
        - name: crunchy
          dataVolumeClaimSpec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
            storageClassName: netapp-block-standard
          walVolumeClaimSpec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
            storageClassName: netapp-block-standard
      backups:
        pgbackrest:
          image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbackrest:ubi8-2.41-4
          repos:
            - name: repo1
              volume:
                volumeClaimSpec:
                  accessModes:
                    - "ReadWriteOnce"
                  resources:
                    requests:
                      storage: 1Gi
