apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    openshift.io/display-name: "wps"
    description: "Wildfire Predictive Services - API"
    openshift.io/long-description: "Wildfire Predictive Services - API"
    tags: "wps"
    iconClass: icon-js
    openshift.io/provider-display-name: "Government of British Columbia"
    openshift.io/documentation-url: "https://github.com/bcgov/wps"
    openshift.io/support-url: "https://github.com/bcgov/wps"
labels:
  app.kubernetes.io/part-of: "${NAME}"
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Module name
    value: wps
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: PROJ_TOOLS
    value: e1e498-tools
  - name: CPU_REQUEST
    description: Requested CPU
    value: 50m
  - name: CPU_LIMIT
    description: CPU upper limit
    value: 500m
  - name: MEMORY_REQUEST
    description: Requested memory
    value: 1Gi
  - name: MEMORY_LIMIT
    description: Memory upper limit
    value: 1Gi
  - name: REPLICAS
    description: Number of replicas (pods)
    value: "2"
  - name: ALLOWED_ORIGINS
    value: wps-*.apps.silver.devops.gov.bc.ca
  - name: WFWX_MAX_PAGE_SIZE
    description: Maximum number of entities to request at a time from the WFWX API
    value: "1000"
  - name: PROJECT_NAMESPACE
    description: Openshift project namespace. Used for /health check
    required: true
  - name: IMAGE_REGISTRY
    description: Location where images are to be pulled
    value: image-registry.openshift-image-registry.svc:5000
    required: true
  - name: POSTGRES_USER
    description: Postgres DB username
    required: True
  - name: POSTGRES_DATABASE
    description: Postgres DB name
    required: True
  - name: SECOND_LEVEL_DOMAIN
    description: The domain of which this application hangs.
    required: True
    value: apps.silver.devops.gov.bc.ca
  - name: POSTGRES_WRITE_HOST
    required: True
  - name: POSTGRES_READ_HOST
    required: True
  - name: ENVIRONMENT
    description: Can be used to modify route (e.g. when deploying to test)
    value: ""
  - name: USE_WFWX
    value: "False"
  - name: VANITY_DOMAIN
    requests: True
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        name: ${NAME}-${SUFFIX}
      strategy:
        type: Rolling
      triggers: []
      template:
        metadata:
          labels:
            name: ${NAME}-${SUFFIX}
        spec:
          volumes:
            - name: html
          automountServiceAccountToken: false
          containers:
            - image: ${IMAGE_REGISTRY}/${PROJ_TOOLS}/${NAME}-${SUFFIX}-html:${SUFFIX}-html
              name: ${NAME}-html
              imagePullPolicy: Always
              volumeMounts:
                - name: html
                  mountPath: app/static
              command: ["/bin/sh"]
              args:
                - "-c"
                - >-
                  cp -R /opt/app-root/src/build/* /app/static &&
                  while true; do
                    sleep 1;
                  done
            - image: ${IMAGE_REGISTRY}/${PROJ_TOOLS}/${NAME}-${SUFFIX}:${SUFFIX}
              imagePullPolicy: Always
              name: ${NAME}
              volumeMounts:
                - name: html
                  mountPath: /app/static
                  readOnly: true
              env:
                - name: ORIGINS
                  value: ${ALLOWED_ORIGINS}
                - name: BASE_URI
                  value: https://${NAME}-${SUFFIX}.${SECOND_LEVEL_DOMAIN}
                - name: PORT # The port that the API will run on (used by fastapi docker image)
                  value: "8080"
                - name: WORKERS_PER_CORE # The number of worker per code (used by fastapi docker image)
                  value: "0.25"
                - name: USE_WFWX
                  value: ${USE_WFWX}
                - name: WFWX_MAX_PAGE_SIZE
                  value: ${WFWX_MAX_PAGE_SIZE}
                - name: WFWX_AUTH_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.wfwx-auth-url
                - name: WFWX_BASE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.wfwx-base-url
                - name: WFWX_USER
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.wfwx-user
                - name: WFWX_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-global
                      key: wfwx-secret
                - name: KEYCLOAK_PUBLIC_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.keycloak-public-key
                - name: POSTGRES_READ_USER
                  value: ${POSTGRES_USER}
                - name: POSTGRES_WRITE_USER
                  value: ${POSTGRES_USER}
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-global
                      key: app-db-password
                - name: POSTGRES_WRITE_HOST
                  value: ${POSTGRES_WRITE_HOST}
                - name: POSTGRES_READ_HOST
                  value: ${POSTGRES_READ_HOST}
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_DATABASE
                  value: ${POSTGRES_DATABASE}
                - name: STATUS_CHECKER_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-global
                      key: status-checker-sa-secret
                - name: OPENSHIFT_BASE_URI
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.openshift-base-uri
                - name: OPENSHIFT_NAMESPACE_API
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.openshift-namespace-api
                - name: PATRONI_CLUSTER_NAME
                  value: patroni-wps-${SUFFIX}
                - name: PROJECT_NAMESPACE
                  value: ${PROJECT_NAMESPACE}
                - name: ROCKET_URL_POST_MESSAGE
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: rocket.chat-url-post-message
                - name: ROCKET_CHANNEL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: rocket.chat-channel
                - name: ROCKET_USER_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-global
                      key: rocket.chat-user-id-secret
                - name: ROCKET_AUTH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-global
                      key: rocket.chat-auth-token-secret
                - name: REACT_APP_KEYCLOAK_AUTH_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.keycloak-auth-url
                - name: REACT_APP_KEYCLOAK_REALM
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.keycloak-realm
                - name: REACT_APP_KEYCLOAK_CLIENT
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.keycloak-client
                - name: REACT_APP_MATOMO_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.matomo-url
                - name: REACT_APP_MATOMO_SITE_ID
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.matomo-site-id
                - name: REACT_APP_MATOMO_CONTAINER
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-global
                      key: env.matomo-container
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                httpGet:
                  path: /api/ready
                  port: 8080
                  scheme: HTTP
                # first probe will fire some time between:
                # initialDelaySeconds and initialDelaySeconds + periodSeconds
                initialDelaySeconds: 30
                periodSeconds: 120
                timeoutSeconds: 1
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /api/health
                  port: 8080
                  scheme: HTTP
                # first probe will fire some time between:
                # initialDelaySeconds and initialDelaySeconds + periodSeconds
                initialDelaySeconds: 30
                periodSeconds: 120
                timeoutSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 80
          targetPort: 8080
      selector:
        name: ${NAME}-${SUFFIX}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
      annotations:
        # Enable HTTP Strict Transport Security:
        haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
    spec:
      host: ${NAME}-${SUFFIX}${ENVIRONMENT}.${SECOND_LEVEL_DOMAIN}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}-${SUFFIX}
      tls:
        termination: edge
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
        certbot-managed: "true"
      name: ${NAME}-${SUFFIX}-vanity
      annotations:
        # Enable HTTP Strict Transport Security:
        haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
    spec:
      host: ${VANITY_DOMAIN}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}-${SUFFIX}
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
