apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    openshift.io/display-name: "wps-web" 
    description: "Wildfire Predictive Services - Web Client"  
    openshift.io/long-description: "Wildfire Predictive Services - Web Client" 
    tags: "wps,wps-web" 
    iconClass: icon-js 
    openshift.io/provider-display-name: "Government of British Columbia" 
    openshift.io/documentation-url: "https://github.com/bcgov/wps-web" 
    openshift.io/support-url: "https://github.com/bcgov/wps-web"
labels:
  app.kubernetes.io/part-of: "${NAME}"
parameters:
  - name: NAME
    description: Module name
    value: wps-web
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: DOCKER_REGISTRY
    value: docker-registry.default.svc:5000
  - name: PROJECT_TOOLS
    value: auzhsi-tools
  - name: CPU_REQUEST
    description: Requested CPU
    value: 1000m
  - name: CPU_LIMIT
    description: CPU upper limit
    value: 1000m
  - name: MEMORY_REQUEST
    description: Requested memory
    value: 2Gi
  - name: MEMORY_LIMIT
    description: Memory upper limit
    value: 2Gi
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      replicas: 1
      selector:
        name: ${NAME}-${SUFFIX}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            name: ${NAME}-${SUFFIX}
        spec:
          automountServiceAccountToken: false
          triggers:
            - type: "ConfigChange"
              type: "ImageChange"
              imageChangeParams:
                automatic: true
                from:
                  kind: "ImageStreamTag"
                  name: "${NAME}:${SUFFIX}"
                  namespace: "${PROJECT_TOOLS}"
          containers:
            - image: ${DOCKER_REGISTRY}/${PROJECT_TOOLS}/${NAME}:${SUFFIX}
              name: ${NAME}
              ports:
                - containerPort: 3000
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      ports:
        - name: 3000-tcp
          protocol: TCP
          port: 3000
          targetPort: 3000
      selector:
        name: ${NAME}-${SUFFIX}
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      host: ${NAME}-${SUFFIX}.pathfinder.gov.bc.ca
      port:
        targetPort: 3000-tcp
      to:
        kind: Service
        name: ${NAME}-${SUFFIX}
      tls:
        termination: edge
