apiVersion: v1
kind: Template
metadata:
  name: ec-subscriber
  annotations:
    description: "Service that retrieves data from the MSC Datamart using Advanced Message Queuing Protocol(AMQP) protocol."
    iconClass: icon-pod
    openshift.io/display-name: "Env Canada Model Data Subscriber"
    openshift.io/long-description: This template deploys a python container that subscribes to Meteorological Service of Canada (MSC) HTTP data server and download weather models.
    tags: python
labels:
  app.kubernetes.io/part-of: "${NAME}"
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Module name
    value: wps-api
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: PROJECT_TOOLS
    value: auzhsi-tools
  - name: APPLICATION_NAME
    value: ec-subscriber
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}-${NAME}-${SUFFIX}
    spec:
      replicas: 1
      selector:
        name: ${APPLICATION_NAME}
      template:
        metadata:
          labels:
            name: ${APPLICATION_NAME}
        spec:
          containers:
            - image: docker-registry.default.svc:5000/${PROJECT_TOOLS}/ec-subscriber:latest
              imagePullPolicy: Always
              name: ${NAME}
              resources:
                limits:
                  cpu: 300m
                  memory: 1Gi
                requests:
                  cpu: 300m
                  memory: 1Gi
