apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APP_NAME}-eccc-consumer
  annotations:
    description: "AMQP consumer for ECCC GRIB files."
    tags: "env-canada,rdps,gdps,hrdps,grib"
labels:
  app.kubernetes.io/part-of: "${APP_NAME}"
  app: ${APP_NAME}-${SUFFIX}
parameters:
  - name: APP_NAME
    description: Application name (wps - wildfire predictive services)
    value: wps
  - name: GLOBAL_NAME
    description: Name of global Module
    value: wps-global
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: PROJ_TOOLS
    value: e1e498-tools
  - name: IMAGE_REGISTRY
    description: Location where images are to be pulled
    value: image-registry.openshift-image-registry.svc:5000
    required: true
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${APP_NAME}-eccc-consumer-${SUFFIX}
      labels:
        app: ${APP_NAME}-${SUFFIX}
    spec:
      replicas: 1
      strategy: Recreate

      selector:
        matchLabels:
          app: ${APP_NAME}-${SUFFIX}
      template:
        metadata:
          labels:
            app: ${APP_NAME}-${SUFFIX}

        spec:
          containers:
            - name: ${APP_NAME}-eccc-consumer-${SUFFIX}
              image: ${IMAGE_REGISTRY}/${PROJ_TOOLS}/wps-api-${SUFFIX}:${SUFFIX}
              command:
                - uv
                - run
                - --no-sync
                - python
                - "-m"
                - wps_weather.eccc_consumer_job

              env:
                - name: UV_NO_CACHE
                  value: "1"
                - name: OBJECT_STORE_SERVER
                  valueFrom:
                    secretKeyRef:
                      name: ${GLOBAL_NAME}
                      key: object-store-server
                - name: OBJECT_STORE_USER_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${GLOBAL_NAME}
                      key: object-store-user-id
                - name: OBJECT_STORE_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${GLOBAL_NAME}
                      key: object-store-secret
                - name: OBJECT_STORE_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: ${GLOBAL_NAME}
                      key: object-store-bucket
              resources:
                limits:
                  memory: 512Mi
                requests:
                  cpu: 200m
                  memory: 256Mi

              # Liveness probe - restart if process hangs
              livenessProbe:
                exec:
                  command:
                    - pgrep
                    - -f
                    - "wps_weather.eccc_consumer_job"
                initialDelaySeconds: 30
                periodSeconds: 60
                failureThreshold: 3
