kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-postgres-clusters
rules:
  - verbs:
      - get
    apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - postgresclusters
