kind: Template
apiVersion: v1
metadata:
  name: wps-global
parameters:
  - name: WFWX_AUTH_URL
    description: Wildfire One API authentication URL
    required: true
  - name: WFWX_BASE_URL
    description: Wildfire One API URL
    required: true
  - name: WFWX_USER
    description: The username to be used for authentication to the Wildfire One API
    required: true
  - name: WFWX_SECRET
    description: Password for authentication to access Wildfire One API
    required: true
  - name: KEYCLOAK_PUBLIC_KEY
    description: Keycloak public key for validating the access token
    required: true
  - name: APP_DB_PASSWORD
    description: Password for the application database
    required: true
  - description: Password of the superuser account for initialization.
    displayName: Superuser Passsword
    name: PATRONI_SUPERUSER_PASSWORD
    required: true
  - description: Password of the replication account for initialization.
    displayName: Repication Passsword
    name: PATRONI_REPLICATION_PASSWORD
    required: true
  - name: BC_FIRE_WEATHER_USER
    description: Username (idir) to be used for authentication to access BC FireWeather Phase 1
    required: true
  - name: BC_FIRE_WEATHER_SECRET
    description: Password for the BC_FIRE_WEATHER_USER account
    required: true
  - name: BC_FIRE_WEATHER_FILTER_ID
    description: ID of custom-made filter associated with BC_FIRE_WEATHER_USER account, used for querying forecast data for all stations
    required: true
  - name: STATUS_CHECKER_SECRET
    description: Token for status-checker Openshift service account. Used for /health check
  - name: OPENSHIFT_BASE_URI
    description: Base URI for connecting to Pathfinder console in Openshift. Used for /health check
  - name: ROCKET_AUTH_TOKEN
    description: Authentication token for rocket.chat notifications
    required: true
  - name: ROCKET_USER_ID
    description: User id for rocket.chat notifications
    required: true
  - name: ROCKET_URL_POST_MESSAGE
    description: Url to Rocketchat API for posting a message
    required: true
  - name: ROCKET_CHANNEL
    description: The name of the Rocketchat channel to post automated notifications to
    required: true
  - name: MATOMO_URL
    description: URL for matomo (analytics) site.
  - name: MATOMO_SITE_ID
    description: ID of application for matomo (analytics) tracking.
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: wps-global
      labels:
        app.kubernetes.io/part-of: wps
    data:
      env.origins: wps-*.pathfinder.gov.bc.ca
      env.wfwx-auth-url: ${WFWX_AUTH_URL}
      env.wfwx-base-url: ${WFWX_BASE_URL}
      env.wfwx-user: ${WFWX_USER}
      env.keycloak-public-key: ${KEYCLOAK_PUBLIC_KEY}
      bc-fire-weather-user: ${BC_FIRE_WEATHER_USER}
      bc-fire-weather-filter-id: ${BC_FIRE_WEATHER_FILTER_ID}
      env.openshift-base-uri: ${OPENSHIFT_BASE_URI}
      env.matomo-url: ${MATOMO_URL}
      env.matomo-site-id: ${MATOMO_SITE_ID}
      rocket.chat-channel: ${ROCKET_CHANNEL}
      rocket.chat-url-post-message: ${ROCKET_URL_POST_MESSAGE}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: wps-global
    type: Opaque
    stringData:
      wfwx-secret: ${WFWX_SECRET}
      app-db-password: ${APP_DB_PASSWORD}
      patroni-replication-password: ${PATRONI_REPLICATION_PASSWORD}
      patroni-superuser-password: ${PATRONI_SUPERUSER_PASSWORD}
      bc-fire-weather-secret: ${BC_FIRE_WEATHER_SECRET}
      status-checker-sa-secret: ${STATUS_CHECKER_SECRET}
      rocket.chat-auth-token-secret: ${ROCKET_AUTH_TOKEN}
      rocket.chat-user-id-secret: ${ROCKET_USER_ID}
