kind: Template
apiVersion: v1
metadata:
  name: wps-api-global
parameters:
  - name: WFWX_AUTH_URL
    description: Wildfire One API authentication URL
    required: true
  - name: WFWX_BASE_URL
    description: Wildfire One API URL
    required: true
  - name: WFWX_USER
    description: The username to be used for authentication to the Wildfire One API
    required: true
  - name: SPOTWX_API_KEY
    description: Token used for authentication to access SpotWX API
    required: true
  - name: WFWX_SECRET
    description: Password for authentication to access Wildfire One API
    required: true
  - name: KEYCLOAK_PUBLIC_KEY
    description: Keycloak public key for validating the access token
    required: true
  - name: APP_DB_PASSWORD
    description: Password for the application database
    required: true
  - description: Password of the superuser account for initialization.
    displayName: Superuser Passsword
    name: PATRONI_SUPERUSER_PASSWORD
    required: true
  - description: Password of the replication account for initialization.
    displayName: Repication Passsword
    name: PATRONI_REPLICATION_PASSWORD
    required: true
  - name: BC_FIRE_WEATHER_BASE_URL
    description: BC FireWeather Phase1 URL
    required: true
  - name: BC_FIRE_WEATHER_USER
    description: Username (idir) to be used for authentication to access BC FireWeather Phase 1
    required: true
  - name: BC_FIRE_WEATHER_SECRET
    description: Password for the BC_FIRE_WEATHER_USER account
    required: true
  - name: BC_FIRE_WEATHER_FILTER_ID
    description: ID of custom-made filter associated with BC_FIRE_WEATHER_USER account, used for querying forecast data for all stations
    required: true
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: wps-api-global
      labels:
        app.kubernetes.io/part-of: wps-api
    data:
      env.origins: wps-web-*.pathfinder.gov.bc.ca
      env.spotwx-url: "https://spotwx.com/services/api.php"
      env.wfwx-auth-url: ${WFWX_AUTH_URL}
      env.wfwx-base-url: ${WFWX_BASE_URL}
      env.wfwx-user: ${WFWX_USER}
      env.keycloak-public-key: ${KEYCLOAK_PUBLIC_KEY}
      bc-fire-weather-base-url: ${BC_FIRE_WEATHER_BASE_URL}
      bc-fire-weather-user: ${BC_FIRE_WEATHER_USER}
      bc-fire-weather-filter-id: ${BC_FIRE_WEATHER_FILTER_ID}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: wps-api-global
    type: Opaque
    stringData:
      spotwx-api-key: ${SPOTWX_API_KEY}
      wfwx-secret: ${WFWX_SECRET}
      app-db-password: ${APP_DB_PASSWORD}
      patroni-replication-password: ${PATRONI_REPLICATION_PASSWORD}
      patroni-superuser-password: ${PATRONI_SUPERUSER_PASSWORD}
      bc-fire-weather-secret: ${BC_FIRE_WEATHER_SECRET}