kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${JOB_NAME}-cronjob-template
  annotations:
    description: "Scheduled task to download and process percent grass curing data from the Canadian Wildland Fire Information System."
    tags: "cronjob,grass curing"
labels:
  app.kubernetes.io/part-of: "${NAME}"
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Module name
    value: wps
  - name: GLOBAL_NAME
    description: Name of global Module
    value: wps-global
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: PROJ_TOOLS
    value: e1e498-tools
  - name: JOB_NAME
    value: grass-curing
  - name: IMAGE_REGISTRY
    required: true
    value: image-registry.openshift-image-registry.svc:5000
  - name: POSTGRES_DATABASE
    required: true
  - name: CRUNCHYDB_USER
    required: true
  - name: SCHEDULE
    required: true
  - name: APP_LABEL
    required: true
objects:
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      name: ${JOB_NAME}
    spec:
      schedule: ${SCHEDULE}
      # We use the "Replace" policy, because we never want the cronjobs to run concurrently,
      # and if for whatever reason a cronjob gets stuck, we want the next run to proceed.
      # If we were to use Forbid, and a cronjob gets stuck, then we'd stop gathering data until someone
      # noticed. We don't want that.
      concurrencyPolicy: "Replace"
      jobTemplate:
        metadata:
          labels:
            cronjob: ${JOB_NAME}
            app: ${APP_LABEL}
        spec:
          template:
            spec:
              containers:
                - name: ${JOB_NAME}
                  image: ${IMAGE_REGISTRY}/${PROJ_TOOLS}/${NAME}-api-${SUFFIX}:${SUFFIX}
                  imagePullPolicy: "Always"
                  command:
                    ["uv", "run", "python", "-m", "app.jobs.grass_curing"]
                  env:
                    - name: POSTGRES_READ_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: user
                    - name: POSTGRES_WRITE_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: user
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: password
                    - name: POSTGRES_WRITE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-host
                    - name: POSTGRES_READ_HOST
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-host
                    - name: POSTGRES_PORT
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-port
                    - name: POSTGRES_DATABASE
                      value: ${POSTGRES_DATABASE}
                    - name: ROCKET_URL_POST_MESSAGE
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-url-post-message
                    - name: ROCKET_CHANNEL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-channel
                    - name: ROCKET_USER_ID
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-user-id-secret
                    - name: ROCKET_AUTH_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-auth-token-secret
                    - name: WFWX_BASE_URL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-base-url
                    - name: WFWX_AUTH_URL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-auth-url
                    - name: WFWX_USER
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-user
                    - name: WFWX_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: wfwx-secret
                    - name: REDIS_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-host
                    - name: REDIS_PORT
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-port
                    - name: REDIS_STATION_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-station-cache-expiry
                    - name: REDIS_AUTH_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-auth-cache-expiry
                    - name: REDIS_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: wps-redis
                          key: database-password
                    - name: REDIS_USE
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-use
                  resources:
                    limits:
                      memory: 1024Mi
                    requests:
                      cpu: "500m"
                      memory: 512Mi
              restartPolicy: OnFailure
