apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: metabase-postgresql-template
message: |-
  The following service(s) have been created in your project:
    1. ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}

metadata:
  name: metabase
  annotations:
    openshift.io/display-name: "Metabase backed by PostgreSQL"
    openshift.io/long-description: >
      This template provides a Metabase instance backed by a standalone PostgreSQL
      server. The database is stored on persistent storage.
    description: >
      This is a PostgreSQL backed Metabase (http://www.metabase.com/) deployment. Metabase is the
      easy, open source way for everyone in your company to ask questions and learn from data.
    iconClass: "pficon-trend-up"
    tags: analytics,database,metabase
parameters:
  - name: NAME
    description: Module name
    value: wps
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: METABASE_SERVICE_NAME
    displayName: Metabase Service Name
    value: metabase
    required: true
  - name: METABASE_ROUTE_HOST
    displayName: Metabase Route Host (FQDN)
    description: The hostname to use when creating an OpenShift Route (Leave blank to use defaults.)
    value: ""
    required: false
  - name: METABASE_IMAGE
    displayName: Metabase Docker Image
    value: registry.hub.docker.com/metabase/metabase:latest
    description: The metabase docker image to use
    required: true
  - description: Version of PostgreSQL image to be used (9.4, 9.5, 9.6 or latest).
    displayName: Version of PostgreSQL Image
    name: POSTGRESQL_VERSION
    required: true
    value: "9.6"
  - name: POSTGRESQL_DATABASE
    displayName: PostgreSQL Database
    description: Database name to use
    value: wps
    required: true
  - name: CLUSTER_NAME
    displayName: OpenShift Cluster name
    description: OpenShift cluster that hosts the database
    value: "patroni-${NAME}-${SUFFIX}"
    required: true
  - name: POSTGRESQL_USER
    displayName: PostgreSQL Username
    description: Username for metabase database user
    value: metabase
    required: true
  - name: POSTGRESQL_PASSWORD
    displayName: PostgreSQL Password
    description: Password for metabase database user
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
  - name: POSTGRESQL_IMAGE_NAMESPACE
    displayName: PostgreSQL Image Namespace
    value: e1e498-tools
    description: The OpenShift namespace for the postgresql image to use
    required: true
  - name: POSTGRESQL_VOLUME_CAPACITY
    displayName: Database Data Volume Capacity
    description: Capacity required for the PostgreSQL database data volume
    value: 1Gi
    required: true
labels:
  app: "${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}"
  phase: deploy
  app.kubernetes.io/instance: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
  app.kubernetes.io/component: metabase
  app.kubernetes.io/name: metabase
  app.kubernetes.io/managed-by: template
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
      labels:
        app: metabase
        service: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}-postgresql-credentials
      labels:
        app: metabase
        service: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
    stringData:
      username: ${POSTGRESQL_USER}
      password: ${POSTGRESQL_PASSWORD}
      database: ${POSTGRESQL_DATABASE}
    type: Opaque
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: metabase
      name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
    spec:
      tags:
        - from:
            kind: DockerImage
            name: ${METABASE_IMAGE}
          generation: 2
          name: latest
          referencePolicy:
            type: Source
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        template.openshift.io/expose-uri: http://{.spec.clusterIP}:{.spec.ports[?(.name=="${METABASE_SERVICE_NAME}")].port}
      name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
      labels:
        app: metabase
        service: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
    spec:
      ports:
        - name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
          port: 3000
          protocol: TCP
          targetPort: 3000
      selector:
        app: metabase
        deploymentconfig: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
      labels:
        app: metabase
        service: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
    spec:
      host: ${METABASE_ROUTE_HOST}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
      labels:
        app: metabase
        service: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
    spec:
      replicas: 1
      selector:
        app: metabase
        deploymentconfig: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: metabase
            service: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
            deploymentconfig: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
            template: metabase
        spec:
          containers:
            - name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
              image: ${METABASE_IMAGE}
              imagePullPolicy: Always
              env:
                - name: MB_DB_TYPE
                  value: postgres
                - name: MB_DB_HOST
                  value: ${CLUSTER_NAME}-replica
                - name: MB_DB_PORT
                  value: "5432"
                - name: MB_DB_DBNAME
                  value: ${POSTGRESQL_DATABASE}
                - name: MB_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}-postgresql-credentials
                      key: username
                - name: MB_DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}-postgresql-credentials
                      key: password
              command:
                - java
              args:
                - "-Xmx300m"
                - "-Xss512k"
                - "-Dfile.encoding=UTF-8"
                - "-Dlogfile.path=target/log"
                - "-XX:+CMSClassUnloadingEnabled"
                - "-XX:+UseConcMarkSweepGC"
                - "-server"
                - "-jar"
                - "/app/metabase.jar"
              ports:
                - containerPort: 3000
                  name: ${METABASE_SERVICE_NAME}
                  protocol: TCP
              terminationMessagePath: /dev/termination-log
              livenessProbe:
                failureThreshold: 30
                httpGet:
                  path: /
                  port: 3000
                initialDelaySeconds: 240
                timeoutSeconds: 3
              readinessProbe:
                httpGet:
                  path: /
                  port: 3000
                initialDelaySeconds: 3
                timeoutSeconds: 3
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          serviceAccount: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
          serviceAccountName: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}
            from:
              kind: ImageStreamTag
              name: ${METABASE_SERVICE_NAME}-${NAME}-${SUFFIX}:latest
            lastTriggeredImage: ""

