apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nats-server-config
  annotations:
    "openshift.io/display-name": nats-server-config
parameters:
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: APP_NAME
    description: Application name (wps - wildfire predictive services)
    value: wps
    required: true
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${APP_NAME}-${SUFFIX}-nats-server
      labels:
        app: ${APP_NAME}-${SUFFIX}
    data:
      nats.server: ${APP_NAME}-${SUFFIX}-nats
