kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${JOB_NAME}-cronjob-template
  annotations:
    description: "Scheduled task to download and process weather data from NCEP-NOAA through https protocol."
    tags: "cronjob,noaa,gfs"
labels:
  app.kubernetes.io/part-of: "${NAME}"
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Module name
    value: wps
  - name: GLOBAL_NAME
    description: Name of global Module
    value: wps-global
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: PROJ_TOOLS
    value: e1e498-tools
  - name: JOB_NAME
    value: noaa
  - name: IMAGE_REGISTRY
    required: true
    value: image-registry.openshift-image-registry.svc:5000
  - name: POSTGRES_DATABASE
    required: true
  - name: CRUNCHYDB_USER
    required: true
  - name: SCHEDULE
    required: true
  - name: WFWX_MAX_PAGE_SIZE
    description: Maximum number of entities to request at a time from the WFWX API
    value: "1000"
  - name: APP_LABEL
    required: true
objects:
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      name: ${JOB_NAME}
    spec:
      # Don't run on the hour - as a courtesy to NOAA, pick a random
      # number so that not everyone hits NOAA at the same time.
      schedule: ${SCHEDULE}
      # We use the "Forbid" policy, because cronjobs can take a long time to run, and it's possible
      # that a job will still be running when the next one is scheduled. If one job is still running,
      # we don't want to start another one, so we use "Forbid" so the running job will not be replaced.
      concurrencyPolicy: "Forbid"
      jobTemplate:
        metadata:
          labels:
            cronjob: ${JOB_NAME}
            app: ${APP_LABEL}
        spec:
          template:
            spec:
              containers:
                - name: ${JOB_NAME}
                  image: ${IMAGE_REGISTRY}/${PROJ_TOOLS}/${NAME}-jobs-${SUFFIX}:${SUFFIX}
                  imagePullPolicy: "Always"
                  command:
                    [
                      "uv",
                      "run",
                      "--no-sync",
                      "python",
                      "-m",
                      "weather_model_jobs.noaa",
                      "GFS",
                    ]
                  env:
                    - name: UV_NO_CACHE
                      value: "1"
                    - name: POSTGRES_READ_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: user
                    - name: POSTGRES_WRITE_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: user
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: password
                    - name: POSTGRES_WRITE_HOST
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-host
                    - name: POSTGRES_READ_HOST
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-host
                    - name: POSTGRES_PORT
                      valueFrom:
                        secretKeyRef:
                          name: ${CRUNCHYDB_USER}
                          key: pgbouncer-port
                    - name: POSTGRES_DATABASE
                      value: ${POSTGRES_DATABASE}
                    - name: ROCKET_URL_POST_MESSAGE
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-url-post-message
                    - name: ROCKET_CHANNEL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-channel
                    - name: ROCKET_USER_ID
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-user-id-secret
                    - name: ROCKET_AUTH_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-auth-token-secret
                    - name: WFWX_MAX_PAGE_SIZE
                      value: ${WFWX_MAX_PAGE_SIZE}
                    - name: WFWX_AUTH_URL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-auth-url
                    - name: WFWX_BASE_URL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-base-url
                    - name: WFWX_USER
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-user
                    - name: WFWX_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: wfwx-secret
                    - name: REDIS_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-host
                    - name: REDIS_PORT
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-port
                    - name: REDIS_USE
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-use
                    - name: REDIS_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: wps-redis
                          key: database-password
                    - name: REDIS_STATION_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-station-cache-expiry
                    - name: REDIS_AUTH_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-auth-cache-expiry
                    - name: REDIS_DAILIES_BY_STATION_CODE_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-dailies-by-station-code-expiry
                    - name: REDIS_CACHE_NOAA
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-cache-noaa
                    - name: DATA_RETENTION_THRESHOLD
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.data_retention_threshold
                  resources:
                    limits:
                      memory: 1024Mi
                    requests:
                      cpu: "500m"
                      memory: 512Mi
              restartPolicy: OnFailure
