kind: Template
apiVersion: v1
metadata:
  annotations:
    description: |-
      Secret for application database.
parameters:
  - name: NAME
    description: Module name
    value: wps-api
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: APP_DB_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${SUFFIX}
    type: Opaque
    stringData:
      app-db-name: ${NAME}-${SUFFIX}
      app-db-username: ${NAME}-${SUFFIX}
      app-db-password: ${APP_DB_PASSWORD}
