kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: status-checker-role-binding
subjects:
  - kind: ServiceAccount
    name: status-checker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-postgres-clusters
