kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${JOB_NAME}-cronjob-template
  annotations:
    description: "Scheduled task to download noon-time weather forecasts for all weather stations from the WFWX API."
    tags: "cronjob,wfwx-noon-forecasts"
labels:
  app.kubernetes.io/part-of: "${NAME}"
  app: ${APP_LABEL}
parameters:
  - name: NAME
    description: Module name
    value: wps
  - name: GLOBAL_NAME
    description: Name of global Module
    value: wps-global
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: PROJ_TOOLS
    value: e1e498-tools
  - name: IMAGE_REGISTRY
    value: image-registry.openshift-image-registry.svc:5000
  - name: JOB_NAME
    value: wfwx-noon-forecasts
  - name: SCHEDULE
    # run before and after local noon (8h30 PDT and 16h30 PDT)
    value: "30 15,23 * * *"
    required: true
  - name: POSTGRES_WRITE_HOST
    required: true
    value: patroni-${NAME}-${SUFFIX}-leader
  - name: POSTGRES_READ_HOST
    value: patroni-${NAME}-${SUFFIX}-replica
  - name: POSTGRES_USER
    required: true
    value: ${NAME}-${SUFFIX}
  - name: POSTGRES_DATABASE
    required: true
    value: ${NAME}-${SUFFIX}
  - name: APP_LABEL
    required: true
    value: wps-${SUFFIX}
objects:
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      name: ${JOB_NAME}
      labels:
        cronjob: ${JOB_NAME}
    spec:
      schedule: ${SCHEDULE}
      concurrencyPolicy: "Replace"
      jobTemplate:
        metadata:
          labels:
            cronjob: ${JOB_NAME}
            app: ${APP_LABEL}
        spec:
          template:
            spec:
              containers:
                - name: ${JOB_NAME}
                  image: ${IMAGE_REGISTRY}/${PROJ_TOOLS}/${NAME}-${SUFFIX}:${SUFFIX}
                  imagePullPolicy: "Always"
                  command: ["python", "-m", "app.jobs.noon_forecasts"]
                  env:
                    - name: WFWX_MAX_PAGE_SIZE
                      value: ${WFWX_MAX_PAGE_SIZE}
                    - name: WFWX_AUTH_URL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-auth-url
                    - name: WFWX_BASE_URL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-base-url
                    - name: WFWX_USER
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.wfwx-user
                    - name: WFWX_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: wfwx-secret
                    - name: POSTGRES_READ_USER
                      value: ${POSTGRES_USER}
                    - name: POSTGRES_WRITE_USER
                      value: ${POSTGRES_USER}
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: app-db-password
                    - name: POSTGRES_WRITE_HOST
                      value: ${POSTGRES_WRITE_HOST}
                    - name: POSTGRES_READ_HOST
                      value: ${POSTGRES_READ_HOST}
                    - name: POSTGRES_PORT
                      value: "5432"
                    - name: POSTGRES_DATABASE
                      value: ${POSTGRES_DATABASE}
                    - name: ROCKET_URL_POST_MESSAGE
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-url-post-message
                    - name: ROCKET_CHANNEL
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-channel
                    - name: ROCKET_USER_ID
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-user-id-secret
                    - name: ROCKET_AUTH_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${GLOBAL_NAME}
                          key: rocket.chat-auth-token-secret
                    - name: REDIS_HOST
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-host
                    - name: REDIS_PORT
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-port
                    - name: REDIS_USE
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-use
                    - name: REDIS_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: wps-redis
                          key: database-password
                    - name: REDIS_STATION_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-station-cache-expiry
                    - name: REDIS_AUTH_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-auth-cache-expiry
                    - name: REDIS_DAILIES_BY_STATION_CODE_CACHE_EXPIRY
                      valueFrom:
                        configMapKeyRef:
                          name: ${GLOBAL_NAME}
                          key: env.redis-dailies-by-station-code-expiry

              restartPolicy: OnFailure
