FROM python:3.6
WORKDIR /usr/src/app

RUN useradd wally -M -G root -u 1021 && chmod -R 775 /app \
&& chown -R wally:root /app \
&& apt-get -y install ca-certificates

RUN pip install pipenv
COPY Pipfile* /tmp/
RUN cd /tmp && pipenv lock --requirements > requirements.txt
RUN pip install -r /tmp/requirements.txt
COPY . .
ENV APP_FILE=/usr/src/app
EXPOSE 80
USER 1021
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]