apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx-tileserv
spec:
  runPolicy: Serial
  source:
    dockerfile: |
      FROM ubuntu:22.04
      RUN apt-get update -y && apt-get install -y nginx

      COPY nginx.conf /etc/nginx/nginx.conf

      CMD /usr/sbin/nginx -g 'daemon off;'

  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
  output:
    to:
      kind: ImageStreamTag
      name: "nginx-tileserv:latest"
