name: Python Setup
description: Install uv, cache venv, and install Python dependencies

inputs:
  install-jdk:
    description: Whether to install JDK
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.10.0"

    - name: Cache .venv
      id: cache-venv
      uses: actions/cache@v5
      with:
        path: ~/work/wps/wps/backend/.venv
        key: ${{ runner.os }}-venv-uv-0.9.11-${{ hashFiles('**/uv.lock') }}

    - name: Install JDK
      if: inputs.install-jdk == 'true' && steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        apt-get update --fix-missing
        apt-get -y install default-jdk

    - name: Install python dependencies using uv
      if: steps.cache-venv.outputs.cache-hit != 'true'
      working-directory: ./backend
      shell: bash
      run: |
        uv sync --all-extras
        uv pip install setuptools
        uv pip install --no-build-isolation gdal==$(gdal-config --version)
