apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: "true"
    name: ${NAME}-slave-${SLAVE_NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-slave-${SLAVE_NAME}${SUFFIX}
  spec:
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-slave-${SLAVE_NAME}:${VERSION}
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: SerialLatestOnly
    source:
#      contextDir: ${SOURCE_CONTEXT_DIR}
#      git:
#        ref: ${SOURCE_GIT_REF}
#        uri: ${SOURCE_GIT_URL}
#      type: Git
      dockerfile: |
        FROM BuildConfig
        USER 0
        RUN fix_permission(){ while [[ $# > 0 ]] ; do chgrp -R 0 "$1" && chmod -R g=u "$1"; shift; done } && \
            set -x && \
            mkdir /opt/flywaydb && \
            curl -sSL https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-linux-x64.tar.gz | tar xvz --strip-components=1 -C /opt/flywaydb && \
            ln -s /opt/flywaydb/flyway /usr/local/bin && \
            mkdir /opt/liquibase && \
            curl -sSL https://github.com/liquibase/liquibase/releases/download/liquibase-parent-3.6.3/liquibase-3.6.3-bin.tar.gz | tar xvz -C /opt/liquibase --exclude=sdk --exclude=liquibase.bat && \
            ln -s /opt/liquibase/liquibase /usr/local/bin && \
            curl -sSL -o /tmp/sonnar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip && \
            unzip /tmp/sonnar-scanner-cli.zip -d /tmp/sonnar-scanner-cli && \
            mv /tmp/sonnar-scanner-cli/sonar-scanner-3.3.0.1492-linux /opt/sonnar-scanner && \
            ln -s /opt/sonnar-scanner/bin/sonar-scanner /usr/local/bin && \
            rm -rf /tmp/sonnar-scanner-cli.zip && \
            rm -rf /tmp/sonnar-scanner-cli && \
            fix_permission '/opt/flywaydb' '/opt/liquibase' '/opt/sonnar-scanner'
        USER 1001
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_STREAM_TAG}
          namespace: ${SOURCE_IMAGE_STREAM_NAMESPACE}
      type: Docker
    successfulBuildsHistoryLimit: 2
    triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_STREAM_TAG}
          namespace: ${SOURCE_IMAGE_STREAM_NAMESPACE}
      type: ImageChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: jenkins
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: "-0"
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: latest
- name: SLAVE_NAME
  value: build
- name: SOURCE_IMAGE_STREAM_NAMESPACE
  value: ""
- name: SOURCE_IMAGE_STREAM_TAG
  required: true
  value: "jenkins:build-v2.0-0"
- name: SOURCE_GIT_URL
  required: true
  value: https://github.com/cvarjao-o/hello-world.git
- name: SOURCE_GIT_REF
  required: true
  value: master
- name: SOURCE_CONTEXT_DIR
  required: true
  value: .jenkins/docker-slave