import React from 'react'

import { ModelValue } from 'api/modelAPI'
import { MODEL_VALUE_DECIMAL } from 'utils/constants'
import SortableTableByDatetime, {
  Column
} from 'features/fireWeather/components/tables/SortableTableByDatetime'

/**
 * Reusable component used to display noon forecasts (issued by forecasters)
 * and/or model forecasts (generated by computer-run models) in table format
 */

const columns: Column[] = [
  {
    id: 'datetime',
    label: 'Date (PDT)',
    align: 'left',
    formatDt: (value: string) => value.slice(0, 10)
  },
  {
    id: 'temperature',
    label: 'Temp (°C)',
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  },
  {
    id: 'relative_humidity',
    label: 'RH (%)',
    align: 'right',
    format: (value: number) => Math.round(value)
  },
  {
    id: 'wind_direction',
    label: 'Wind Dir',
    align: 'right',
    format: (value: number) => Math.round(value)
  },
  {
    id: 'wind_speed',
    label: 'Wind Spd (km/h)',
    minWidth: 70,
    maxWidth: 100,
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  },
  {
    id: 'delta_precipitation',
    label: 'Precip (mm/cm)',
    minWidth: 70,
    maxWidth: 100,
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  }
]

interface Props {
  testId: string
  title: string
  rows: ModelValue[] | undefined
}

const NoonModelTable = (props: Props) => {
  return <SortableTableByDatetime {...props} columns={columns} />
}

export default React.memo(NoonModelTable)
