import React from 'react'

import { ModelValue } from 'api/modelAPI'
import { NoonForecastValue } from 'api/forecastAPI'
import { MODEL_VALUE_DECIMAL } from 'utils/constants'
import SortableTableByDatetime, {
  Column
} from 'features/fireWeather/components/tables/SortableTableByDatetime'

/**
 * Reusable component used to display noon forecasts (issued by forecasters)
 * and/or model forecasts (generated by computer-run models) in table format
 */

const sharedColumns: Column[] = [
  {
    id: 'datetime',
    label: 'Date (PDT)',
    align: 'left',
    formatDt: (value: string) => value.slice(0, 10)
  },
  {
    id: 'temperature',
    label: 'Temp (°C)',
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  },
  {
    id: 'relative_humidity',
    label: 'RH (%)',
    align: 'right',
    format: (value: number) => Math.round(value)
  },
  {
    id: 'wind_direction',
    label: 'Wind Dir (10m)',
    align: 'right',
    format: (value: number) => Math.round(value)
  },
  {
    id: 'wind_speed',
    label: 'Wind Spd (10m) (km/h)',
    minWidth: 70,
    maxWidth: 120,
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  }
]

interface NoonModelTableProps {
  testId: string
  title: string
  rows: ModelValue[] | undefined
}

export const NoonModelTable = React.memo(function _(props: NoonModelTableProps) {
  const precipColumn: Column = {
    id: 'delta_precipitation',
    label: 'Precip (mm/cm)',
    minWidth: 70,
    maxWidth: 100,
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  }
  const modelRunColumn: Column = {
    id: 'model_run_datetime',
    label: 'Model Run (UTC)',
    minWidth: 70,
    maxWidth: 100,
    align: 'left',
    formatDt: (value: string) => value.slice(0, 13)
  }

  return (
    <SortableTableByDatetime
      {...props}
      columns={[...sharedColumns, precipColumn, modelRunColumn]}
    />
  )
})

interface NoonForecastTableProps {
  testId: string
  title: string
  rows: NoonForecastValue[] | undefined
}

export const NoonForecastTable = React.memo(function _(props: NoonForecastTableProps) {
  const precipColumn: Column = {
    id: 'total_precipitation',
    label: 'Precip (mm/cm)',
    minWidth: 70,
    maxWidth: 100,
    align: 'right',
    format: (value: number) => value.toFixed(MODEL_VALUE_DECIMAL)
  }

  return <SortableTableByDatetime {...props} columns={[...sharedColumns, precipColumn]} />
})
