"""
Shared loading/computation logic for the GLC-X-10 (Wotton et al. 2009) published FBP System test
cases, used by test_fbp_glc_x_10.py (reads the vendored CSVs directly) and
test_fbp_glc_x_10_rasters.py (reads the equivalent GeoTIFF fixtures generated by
generate_glc_x_10_rasters.py from those same CSVs), both parametrized over both sources. See
https://github.com/bcgov/wps/issues/4893.

The cffdrs_r_test_fbp_*.csv files in data/ are the CFFDRS working group's own digitized
transcription of the paper's Tables 4/5. They're copied from the R cffdrs package
(github.com/cffdrs/cffdrs_r: data/test_fbp.csv, tests/testthat/data/fbp_01.csv, fbp_04.csv),
by way of cffdrs_py's own copy of those same files (cffdrs/tests/data/test_fbp.csv, fbp_01.csv, fbp_04.csv,
not included in the installed cffdrs_py package, hence vendored here rather than depended on at runtime).

The glc_x_10_paper_*.csv files are a second, independent transcription: extracted directly from
Tables 4-6 of the published PDF (Fo123-2-10-2009-eng.pdf) via `pdftotext -layout`, without going
through the R package at all. They exist to cross-validate the R-sourced CSVs above against the
actual paper rather than trusting that chain of custody; see PaperSource.

"""

import csv
import math
from abc import ABC, abstractmethod
from pathlib import Path
from typing import NamedTuple

import numpy as np
from cffdrs.constants import D1, FUEL_TYPE_CODES, O1A, O1B, S1, S2, S3
from osgeo import osr
from wps_shared.geospatial.wps_dataset import WPSDataset

from cffdrs_vec import fbp
from cffdrs_vec.fwi import vectorized_isi

DATA_DIR = Path(__file__).parent / "data"

SFMS_NO_DATA = -3.4028235e38
# 1 row x 20 columns, one pixel per case, in an arbitrary-but-valid location/resolution - the
# geospatial placement is meaningless here (LAT/LONG are separate data layers, not implied by
# pixel position), it just needs to be internally consistent across all rasters.
RASTER_GEOTRANSFORM = (-140.0, 1.0, 0.0, 60.0, 0.0, -1.0)

# Fuel types with no crown to burn - _fire_behaviour_prediction always zeroes FMC for these.
NO_CROWN_FUEL_TYPE_CODES = (D1, S1, S2, S3, O1A, O1B)

FIRE_TYPE_BY_FD_CODE = {"S": "SUR", "I": "IC", "C": "CC"}

# Table 7 (FCFDG 1992) CBH/CFL defaults, used because the GLC-X-10 dataset leaves CBH/CFL blank
# for every case (relying on cffdrs's own per-fuel-type defaults). Matches
# wps_shared.fuel_types.FUEL_TYPE_DEFAULTS exactly.
CBH_DEFAULT = {
    "C1": 2,
    "C2": 3,
    "C3": 8,
    "C4": 4,
    "C5": 18,
    "C6": 7,
    "C7": 10,
    "D1": 0,
    "M1": 6,
    "M2": 6,
    "M3": 6,
    "M4": 6,
    "S1": 0,
    "S2": 0,
    "S3": 0,
    "O1A": 0,
    "O1B": 0,
}
CFL_DEFAULT = {
    "C1": 0.75,
    "C2": 0.8,
    "C3": 1.15,
    "C4": 1.2,
    "C5": 1.2,
    "C6": 1.8,
    "C7": 0.5,
    "D1": 0,
    "M1": 0.8,
    "M2": 0.8,
    "M3": 0.8,
    "M4": 0.8,
    "S1": 0,
    "S2": 0,
    "S3": 0,
    "O1A": 0,
    "O1B": 0,
}
PC_DEFAULT = {
    "C1": 100,
    "C2": 100,
    "C3": 100,
    "C4": 100,
    "C5": 100,
    "C6": 100,
    "C7": 100,
    "D1": 0,
    "M1": 50,
    "M2": 50,
    "M3": 0,
    "M4": 0,
    "S1": 0,
    "S2": 0,
    "S3": 0,
    "O1A": 0,
    "O1B": 0,
}
PDF_DEFAULT = {
    "C1": 0,
    "C2": 0,
    "C3": 0,
    "C4": 0,
    "C5": 0,
    "C6": 0,
    "C7": 0,
    "D1": 0,
    "M1": 0,
    "M2": 0,
    "M3": 30,
    "M4": 30,
    "S1": 0,
    "S2": 0,
    "S3": 0,
    "O1A": 0,
    "O1B": 0,
}

# Raster fixture variable names, in the order generate_glc_x_10_rasters.py writes them - shared so
# the generator and the raster-reading test can't drift apart on file naming.
INPUT_RASTER_NAMES = [
    "fuel_type_code",
    "lat",
    "lon",
    "elv",
    "ffmc",
    "bui",
    "ws",
    "wd",
    "gs",
    "dj",
    "d0",
    "aspect",
    "pc",
    "pdf",
    "cc",
    "gfl",
    "cbh",
    "cfl",
]
OUTPUT_RASTER_NAMES = ["ros", "hfi", "cfb", "sfc", "tfc", "raz"]


def parse_float(value: str) -> float:
    value = value.strip()
    if value == "" or value.upper() == "NA":
        return math.nan
    return float(value)


def normalize_fuel_type(value: str) -> str:
    return value.strip().upper().replace("-", "")


def with_default(values: np.ndarray, fuel_types: list, defaults: dict) -> np.ndarray:
    fallback = np.array([defaults[ft] for ft in fuel_types], dtype=np.float64)
    return np.where(np.isnan(values), fallback, values)


def load_rows(filename: str) -> list[dict]:
    with open(DATA_DIR / filename) as f:
        return list(csv.DictReader(f))


def read_raster(raster_dir: Path, name: str) -> np.ndarray:
    """Returns the raster's full 2-D (row, column) array, same shape a real production raster
    would have - calculate_primary_output()'s vectorized functions are shape-preserving, so
    nothing downstream needs to flatten this the way a real 2-D SFMS grid wouldn't be flattened
    either. Our fixtures happen to be 1 row x 20 columns (one column per GLC-X-10 case), but
    nothing here assumes that.
    """
    with WPSDataset(str(raster_dir / f"{name}.tif")) as ds:
        array, _nodata = ds.replace_nodata_with(np.nan)
    return array


def raster_projection_wkt() -> str:
    srs = osr.SpatialReference()
    srs.ImportFromEPSG(4326)
    return srs.ExportToWkt()


def write_raster(raster_dir: Path, name: str, values: list) -> None:
    array = np.array([values], dtype=np.float32)  # shape (1, 20)
    array = np.where(np.isnan(array), SFMS_NO_DATA, array)
    with WPSDataset.from_array(
        array, RASTER_GEOTRANSFORM, raster_projection_wkt(), SFMS_NO_DATA
    ) as ds:
        ds.export_to_geotiff(str(raster_dir / f"{name}.tif"))


class GLCX10Inputs(NamedTuple):
    """One field per array calculate_primary_output() needs - GLCX10Source.load_raster_inputs()
    builds the same shape from GeoTIFFs instead of the CSVs.
    """

    fuel_type_codes: np.ndarray
    lat: np.ndarray
    lon: np.ndarray
    elv: np.ndarray
    ffmc: np.ndarray
    bui: np.ndarray
    ws: np.ndarray
    wd_rad: np.ndarray
    gs: np.ndarray
    dj: np.ndarray
    d0: np.ndarray
    aspect_rad: np.ndarray
    gfl: np.ndarray
    pc: np.ndarray
    pdf: np.ndarray
    cc: np.ndarray
    cbh: np.ndarray
    cfl: np.ndarray


class GLCX10ExpectedOutputs(NamedTuple):
    """The published Table 5 outputs, in the same case order as the GLCX10Inputs they go with."""

    ros: np.ndarray
    hfi: np.ndarray
    cfb: np.ndarray
    sfc: np.ndarray
    tfc: np.ndarray
    raz: np.ndarray
    fire_type: list


class PrimaryOutput(NamedTuple):
    """calculate_primary_output()'s result - the Primary output fields _fire_behaviour_prediction
    itself returns (ros, hfi, cfb, sfc, tfc, raz, fire_type), plus the intermediate values its
    composition passes from one step to the next (fmc, wsv, isi, csi, rso) that Table 5 also
    happens to publish, so tests can check each step against the paper rather than only the
    final result.
    """

    ros: np.ndarray
    hfi: np.ndarray
    cfb: np.ndarray
    sfc: np.ndarray
    tfc: np.ndarray
    raz: np.ndarray
    fire_type: np.ndarray
    fmc: np.ndarray
    wsv: np.ndarray
    isi: np.ndarray
    csi: np.ndarray
    rso: np.ndarray


class GLCX10Source(ABC):
    """One of the two independent GLC-X-10 data sources - knows how to load its own CSV-sourced
    inputs/expected-outputs and its own GeoTIFF-sourced inputs, and how loose a tolerance its
    ROS/HFI/CFB comparisons need (see test_fbp_glc_x_10.py for why "paper" needs a looser one
    than "r_package"). RPackageSource and PaperSource below are the two concrete sources; nothing
    else should subclass this.

    Parametrize tests on the GLCX10Source instance itself (`@pytest.mark.parametrize("source",
    GLC_X_10_SOURCES, ...)`), not on its individual fields/methods - a test only ever reads the
    one or two it actually needs, so nothing forces every test to declare ones it doesn't use
    (unlike exploding a source into separate parametrize columns would).
    """

    name: str
    input_csv: str
    output_csv: str
    id_input_col: str
    id_output_col: str
    raster_dir: Path
    columns: dict
    # ROS/HFI/CFB tolerances - looser for "paper" to absorb the small, known drift between the
    # paper's 2009-vintage published values and what the current FBP equations compute (see
    # test_fbp_glc_x_10.py).
    rtol_ros_hfi: float
    atol_cfb: float

    @abstractmethod
    def _aspect_rad_cbh_cfl(
        self, input_rows: list[dict], fuel_types: list[str]
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Returns (aspect_rad, cbh, cfl) - the 3 fields that aren't just a column rename between
        sources (see RPackageSource/PaperSource for why each has to override this).
        """

    @abstractmethod
    def _raster_aspect_cbh_cfl(
        self, input_rows: list[dict]
    ) -> tuple[list[float], list[float], list[float]]:
        """Returns (aspect_deg, cbh, cfl) as raw per-case value lists ready to write straight to
        a raster - unlike _aspect_rad_cbh_cfl() above, missing values stay NaN here rather than
        being filled with a default, so the raster round-trip (write here, then default-fill on
        read in load_raster_inputs()) can prove that same default-filling logic actually works
        when driven by a raster read, not just a CSV read.
        """

    def load(self) -> tuple[GLCX10Inputs, GLCX10ExpectedOutputs]:
        """Loads all 20 GLC-X-10 cases as batched arrays, plus the published Table 5 outputs."""
        input_rows = load_rows(self.input_csv)
        output_by_id = {row[self.id_output_col]: row for row in load_rows(self.output_csv)}

        ids = [row[self.id_input_col] for row in input_rows]
        fuel_types = [normalize_fuel_type(row["FuelType"]) for row in input_rows]
        fuel_type_codes = np.array([FUEL_TYPE_CODES[ft] for ft in fuel_types], dtype=np.int64)

        columns = self.columns
        lat = np.array([parse_float(row[columns["lat"]]) for row in input_rows])
        lon = np.array([parse_float(row[columns["lon"]]) for row in input_rows])
        elv = np.nan_to_num(np.array([parse_float(row[columns["elv"]]) for row in input_rows]))
        ffmc = np.array([parse_float(row[columns["ffmc"]]) for row in input_rows])
        bui = np.array([parse_float(row[columns["bui"]]) for row in input_rows])
        ws = np.array([parse_float(row[columns["ws"]]) for row in input_rows])
        # Blank only for case 4 (both sources), where WS=0 makes wind direction physically
        # irrelevant.
        wd_rad = np.radians(
            np.nan_to_num(np.array([parse_float(row[columns["wd"]]) for row in input_rows]))
        )
        gs = np.array([parse_float(row[columns["gs"]]) for row in input_rows])
        dj = np.array([parse_float(row[columns["dj"]]) for row in input_rows])
        d0 = np.nan_to_num(np.array([parse_float(row[columns["d0"]]) for row in input_rows]))
        gfl = np.nan_to_num(np.array([parse_float(row[columns["gfl"]]) for row in input_rows]))
        pc = with_default(
            np.array([parse_float(row[columns["pc"]]) for row in input_rows]),
            fuel_types,
            PC_DEFAULT,
        )
        pdf = with_default(
            np.array([parse_float(row[columns["pdf"]]) for row in input_rows]),
            fuel_types,
            PDF_DEFAULT,
        )
        cc = np.nan_to_num(np.array([parse_float(row[columns["cc"]]) for row in input_rows]))

        aspect_rad, cbh, cfl = self._aspect_rad_cbh_cfl(input_rows, fuel_types)

        inputs = GLCX10Inputs(
            fuel_type_codes=fuel_type_codes,
            lat=lat,
            lon=lon,
            elv=elv,
            ffmc=ffmc,
            bui=bui,
            ws=ws,
            wd_rad=wd_rad,
            gs=gs,
            dj=dj,
            d0=d0,
            aspect_rad=aspect_rad,
            gfl=gfl,
            pc=pc,
            pdf=pdf,
            cc=cc,
            cbh=cbh,
            cfl=cfl,
        )
        expected = GLCX10ExpectedOutputs(
            ros=np.array([float(output_by_id[i]["ROS"]) for i in ids]),
            hfi=np.array([float(output_by_id[i]["HFI"]) for i in ids]),
            cfb=np.array([float(output_by_id[i]["CFB"]) for i in ids]),
            sfc=np.array([float(output_by_id[i]["SFC"]) for i in ids]),
            tfc=np.array([float(output_by_id[i]["TFC"]) for i in ids]),
            raz=np.array([float(output_by_id[i]["RAZ"]) for i in ids]),
            fire_type=[FIRE_TYPE_BY_FD_CODE[output_by_id[i]["FD"]] for i in ids],
        )
        return inputs, expected

    def load_raster_inputs(self) -> GLCX10Inputs:
        """Same GLCX10Inputs shape load() returns, but read from `self.raster_dir`'s GeoTIFF
        fixtures instead of `self.input_csv` - the raster-reading logic itself doesn't differ
        between sources, only which directory/CSV it points at, so there's nothing for
        RPackageSource/PaperSource to override here.
        """
        raster = {name: read_raster(self.raster_dir, name) for name in INPUT_RASTER_NAMES}

        # fuel type names aren't stored in the rasters (only the numeric code is) - needed here
        # only to look up PC/PDF/CBH/CFL defaults, same as load() does from the CSV directly.
        input_rows = load_rows(self.input_csv)
        fuel_types = [normalize_fuel_type(row["FuelType"]) for row in input_rows]

        return GLCX10Inputs(
            fuel_type_codes=raster["fuel_type_code"].astype(np.int64),
            lat=raster["lat"],
            lon=raster["lon"],
            elv=np.nan_to_num(raster["elv"]),
            ffmc=raster["ffmc"],
            bui=raster["bui"],
            ws=raster["ws"],
            wd_rad=np.radians(np.nan_to_num(raster["wd"])),
            gs=raster["gs"],
            dj=raster["dj"],
            d0=np.nan_to_num(raster["d0"]),
            aspect_rad=np.radians(np.nan_to_num(raster["aspect"])),
            gfl=np.nan_to_num(raster["gfl"]),
            pc=with_default(raster["pc"], fuel_types, PC_DEFAULT),
            pdf=with_default(raster["pdf"], fuel_types, PDF_DEFAULT),
            cc=np.nan_to_num(raster["cc"]),
            cbh=with_default(raster["cbh"], fuel_types, CBH_DEFAULT),
            cfl=with_default(raster["cfl"], fuel_types, CFL_DEFAULT),
        )

    def read_raster_output(self, name: str) -> np.ndarray:
        return read_raster(self.raster_dir, name)

    def generate_rasters(self) -> None:
        """Writes this source's GeoTIFF fixtures under self.raster_dir - one small (1 row x 20
        case) raster per input/output variable, in case order (column 0 = case 1, ..., column 19
        = case 20). Same one-raster-per-variable layout as the existing
        bui20240528.tif/dc20240528.tif/dmc20240528.tif FWI fixtures.

        Blank CSV cells (eg. CBH/CFL/PC, left for cffdrs to default) are written as SFMS_NO_DATA,
        not 0 or NaN, so reading them back through WPSDataset.replace_nodata_with(np.nan)
        round-trips to exactly the same "missing" signal parse_float() gives when reading the CSV
        directly - see load_raster_inputs().

        Run via generate_glc_x_10_rasters.py; the output is committed to the repo like the other
        raster fixtures, so this only needs re-running if the source CSVs change.
        """
        input_rows = load_rows(self.input_csv)
        output_by_id = {row[self.id_output_col]: row for row in load_rows(self.output_csv)}
        ids = [row[self.id_input_col] for row in input_rows]
        fuel_types = [normalize_fuel_type(row["FuelType"]) for row in input_rows]
        columns = self.columns

        aspect_deg, cbh, cfl = self._raster_aspect_cbh_cfl(input_rows)

        input_columns = {
            "fuel_type_code": [float(FUEL_TYPE_CODES[ft]) for ft in fuel_types],
            "lat": [parse_float(row[columns["lat"]]) for row in input_rows],
            "lon": [parse_float(row[columns["lon"]]) for row in input_rows],
            "elv": [parse_float(row[columns["elv"]]) for row in input_rows],
            "ffmc": [parse_float(row[columns["ffmc"]]) for row in input_rows],
            "bui": [parse_float(row[columns["bui"]]) for row in input_rows],
            "ws": [parse_float(row[columns["ws"]]) for row in input_rows],
            "wd": [parse_float(row[columns["wd"]]) for row in input_rows],
            "gs": [parse_float(row[columns["gs"]]) for row in input_rows],
            "dj": [parse_float(row[columns["dj"]]) for row in input_rows],
            "d0": [parse_float(row[columns["d0"]]) for row in input_rows],
            "aspect": aspect_deg,
            "pc": [parse_float(row[columns["pc"]]) for row in input_rows],
            "pdf": [parse_float(row[columns["pdf"]]) for row in input_rows],
            "cc": [parse_float(row[columns["cc"]]) for row in input_rows],
            "gfl": [parse_float(row[columns["gfl"]]) for row in input_rows],
            "cbh": cbh,
            "cfl": cfl,
        }
        assert list(input_columns) == INPUT_RASTER_NAMES

        output_columns = {
            "ros": [float(output_by_id[i]["ROS"]) for i in ids],
            "hfi": [float(output_by_id[i]["HFI"]) for i in ids],
            "cfb": [float(output_by_id[i]["CFB"]) for i in ids],
            "sfc": [float(output_by_id[i]["SFC"]) for i in ids],
            "tfc": [float(output_by_id[i]["TFC"]) for i in ids],
            "raz": [float(output_by_id[i]["RAZ"]) for i in ids],
        }
        assert list(output_columns) == OUTPUT_RASTER_NAMES

        self.raster_dir.mkdir(parents=True, exist_ok=True)
        for name, values in {**input_columns, **output_columns}.items():
            write_raster(self.raster_dir, name, values)
            print(f"wrote {self.raster_dir / f'{name}.tif'}")


class RPackageSource(GLCX10Source):
    """The CFFDRS working group's own digitized transcription of the paper's Tables 4/5. Copied
    from the R cffdrs package (github.com/cffdrs/cffdrs_r: data/test_fbp.csv,
    tests/testthat/data/fbp_01.csv, fbp_04.csv), by way of cffdrs_py's own copy of those same
    files (not included in the installed cffdrs_py package, hence vendored here rather than
    depended on at runtime).
    """

    name = "r_package"
    input_csv = "cffdrs_r_test_fbp_inputs.csv"
    output_csv = "cffdrs_r_test_fbp_primary_outputs.csv"
    id_input_col = "id"
    id_output_col = "ID"
    raster_dir = Path(__file__).parent / "fixtures" / "glc_x_10"
    # Column names differ from PaperSource's (and one field is fully renamed - see
    # _aspect_rad_cbh_cfl below), but every other CSV shape is the same for both sources: an
    # input CSV with a "FuelType" column, and an output CSV with ROS/HFI/CFB/SFC/TFC/RAZ/FD
    # columns keyed by the same id.
    columns = {
        "lat": "LAT",
        "lon": "LONG",
        "elv": "ELV",
        "ffmc": "FFMC",
        "bui": "BUI",
        "ws": "WS",
        "wd": "WD",
        "gs": "GS",
        "dj": "Dj",
        "d0": "D0",
        "gfl": "GFL",
        "pc": "PC",
        "pdf": "PDF",
        "cc": "cc",
    }
    rtol_ros_hfi = 1e-3
    atol_cfb = 1e-3

    def _aspect_rad_cbh_cfl(self, input_rows, fuel_types):
        aspect_rad = np.radians(
            np.nan_to_num(np.array([parse_float(row["Aspect"]) for row in input_rows]))
        )
        cbh = with_default(
            np.array([parse_float(row["CBH"]) for row in input_rows]), fuel_types, CBH_DEFAULT
        )
        cfl = with_default(
            np.array([parse_float(row["CFL"]) for row in input_rows]), fuel_types, CFL_DEFAULT
        )
        return aspect_rad, cbh, cfl

    def _raster_aspect_cbh_cfl(self, input_rows):
        aspect_deg = [parse_float(row["Aspect"]) for row in input_rows]
        cbh = [parse_float(row["CBH"]) for row in input_rows]
        cfl = [parse_float(row["CFL"]) for row in input_rows]
        return aspect_deg, cbh, cfl


class PaperSource(GLCX10Source):
    """A second, independent transcription: extracted directly from Tables 4-6 of the published
    PDF (Fo123-2-10-2009-eng.pdf) via `pdftotext -layout`, without going through the R package at
    all. Exists to cross-validate RPackageSource's CSVs against the actual paper rather than
    trusting that chain of custody.
    """

    name = "paper"
    input_csv = "glc_x_10_paper_inputs.csv"
    output_csv = "glc_x_10_paper_primary_outputs.csv"
    id_input_col = "TestCase"
    id_output_col = "TestCase"
    raster_dir = Path(__file__).parent / "fixtures" / "glc_x_10_paper"
    columns = {
        "lat": "Lat",
        "lon": "Long",
        "elv": "Elev",
        "ffmc": "FFMC",
        "bui": "BUI",
        "ws": "WS",
        "wd": "WDIR",
        "gs": "GS",
        "dj": "Dj",
        "d0": "D0",
        "gfl": "GFL",
        "pc": "PC",
        "pdf": "PDF",
        "cc": "C",
    }
    rtol_ros_hfi = 1e-2
    atol_cfb = 3e-3

    def _aspect_rad_cbh_cfl(self, input_rows, fuel_types):
        # The paper gives SAZ (upslope azimuth) directly rather than cffdrs's own Aspect
        # (downslope-facing direction) input convention; SAZ = Aspect + 180 deg (see fbp.r
        # comments), so invert that here. Blank only for case 14, where GS=0 makes slope
        # direction physically irrelevant.
        saz_deg = np.nan_to_num(np.array([parse_float(row["SAZ"]) for row in input_rows]))
        aspect_rad = np.radians((saz_deg - 180) % 360)
        # Table 4 (the paper's own table) has no CBH/CFL columns at all - cffdrs's own
        # per-fuel-type defaults always apply, there's no column to read.
        cbh = np.array([CBH_DEFAULT[ft] for ft in fuel_types])
        cfl = np.array([CFL_DEFAULT[ft] for ft in fuel_types])
        return aspect_rad, cbh, cfl

    def _raster_aspect_cbh_cfl(self, input_rows):
        # Same nan_to_num-before-subtracting-180 order of operations as _aspect_rad_cbh_cfl
        # above, so the CSV-direct and raster-sourced paths resolve to the exact same aspect
        # value for case 14 (blank SAZ) even though it doesn't affect any result (case 14 has
        # GS=0, so slope direction is never actually used).
        saz_deg = np.nan_to_num(np.array([parse_float(row["SAZ"]) for row in input_rows]))
        aspect_deg = list((saz_deg - 180) % 360)
        # Table 4 has no CBH/CFL columns at all - always missing, always defaulted on read.
        cbh = [float("nan")] * len(input_rows)
        cfl = [float("nan")] * len(input_rows)
        return aspect_deg, cbh, cfl


R_PACKAGE = RPackageSource()
PAPER = PaperSource()
GLC_X_10_SOURCES = [R_PACKAGE, PAPER]


def foliar_moisture_content(inputs: GLCX10Inputs) -> np.ndarray:
    fmc = fbp.vectorized_foliar_moisture_content(
        inputs.lat, inputs.lon, inputs.elv, inputs.dj, inputs.d0
    )
    no_crown = np.isin(inputs.fuel_type_codes, NO_CROWN_FUEL_TYPE_CODES)
    return np.where(no_crown, 0.0, fmc)


def surface_fuel_consumption(inputs: GLCX10Inputs) -> np.ndarray:
    return fbp.vectorized_surface_fuel_consumption(
        inputs.fuel_type_codes, inputs.ffmc, inputs.bui, inputs.pc, inputs.gfl
    )


def slope_adjustment(
    inputs: GLCX10Inputs, fmc: np.ndarray, sfc: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """Returns (wsv, raz) - the net effective wind speed and direction (radians), once slope is
    accounted for.
    """
    # Corrections to reorient Wind Azimuth (WAZ) and Uphill slope azimuth (SAZ) - Eq. matches
    # _fire_behaviour_prediction exactly.
    waz = inputs.wd_rad + math.pi
    waz = np.where(waz > 2 * math.pi, waz - 2 * math.pi, waz)
    saz = inputs.aspect_rad + math.pi
    saz = np.where(saz > 2 * math.pi, saz - 2 * math.pi, saz)

    # slope_adjustment()'s isi parameter is unused by the underlying formula (it derives its own
    # zero-wind ISI internally), so any placeholder value works here.
    wsv0, raz0 = fbp.vectorized_slope_adjustment(
        inputs.fuel_type_codes,
        inputs.ffmc,
        inputs.bui,
        inputs.ws,
        waz,
        inputs.gs,
        saz,
        fmc,
        sfc,
        inputs.pc,
        inputs.pdf,
        inputs.cc,
        inputs.cbh,
        np.zeros(inputs.fuel_type_codes.shape),
    )
    slope_active = (inputs.gs > 0) & (inputs.ffmc > 0)
    wsv = np.where(slope_active, wsv0, inputs.ws)
    raz = np.where(slope_active, raz0, waz)
    return wsv, raz


def initial_spread_index(inputs: GLCX10Inputs, wsv: np.ndarray) -> np.ndarray:
    """All 20 published cases leave ISI as "not observed" (0), so it's always derived from the
    slope-adjusted wind speed here, same as _fire_behaviour_prediction does.
    """
    return vectorized_isi(inputs.ffmc, wsv, True)


def rate_of_spread_extended(
    inputs: GLCX10Inputs, isi: np.ndarray, fmc: np.ndarray, sfc: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Returns (ros, cfb, csi, rso)."""
    ros, cfb, csi, rso = fbp.vectorized_rate_of_spread_extended(
        inputs.fuel_type_codes,
        isi,
        inputs.bui,
        fmc,
        sfc,
        inputs.pc,
        inputs.pdf,
        inputs.cc,
        inputs.cbh,
    )
    cfb = np.where(inputs.cfl > 0, cfb, 0.0)
    return ros, cfb, csi, rso


def total_fuel_consumption(inputs: GLCX10Inputs, cfb: np.ndarray, sfc: np.ndarray) -> np.ndarray:
    return fbp.vectorized_total_fuel_consumption(
        inputs.fuel_type_codes, inputs.cfl, cfb, sfc, inputs.pc, inputs.pdf
    )


def fire_intensity(tfc: np.ndarray, ros: np.ndarray) -> np.ndarray:
    return fbp.vectorized_fire_intensity(tfc, ros)


def classify_fire_type(cfb: np.ndarray) -> np.ndarray:
    fire_type = np.full(cfb.shape, "IC", dtype=object)
    fire_type[cfb < 0.1] = "SUR"
    fire_type[cfb >= 0.9] = "CC"
    return fire_type


def calculate_primary_output(inputs: GLCX10Inputs) -> PrimaryOutput:
    """Mirrors cffdrs.fire_behaviour_prediction._fire_behaviour_prediction's Primary output,
    composed from the step functions above (each mirroring one piece of that same orchestration)
    over the whole batch/grid at once - the call graph below *is* the dependency graph, no
    separate graph structure needed for a chain this shallow.

    `inputs` just needs GLCX10Inputs's fields, GLCX10Source.load_raster_inputs() builds the same
    shape from GeoTIFFs instead of the CSVs. Every step is shape-preserving, 1-D or 2-D alike (a
    real production raster grid would stay 2-D end to end, same as SFMS's own FWI job does).
    """
    fmc = foliar_moisture_content(inputs)
    sfc = surface_fuel_consumption(inputs)
    wsv, raz = slope_adjustment(inputs, fmc, sfc)
    isi = initial_spread_index(inputs, wsv)
    ros, cfb, csi, rso = rate_of_spread_extended(inputs, isi, fmc, sfc)
    tfc = total_fuel_consumption(inputs, cfb, sfc)
    hfi = fire_intensity(tfc, ros)

    raz_deg = np.degrees(raz)
    raz_deg = np.where(raz_deg == 360, 0.0, raz_deg)

    return PrimaryOutput(
        ros=ros,
        hfi=hfi,
        cfb=cfb,
        sfc=sfc,
        tfc=tfc,
        raz=raz_deg,
        fire_type=classify_fire_type(cfb),
        fmc=fmc,
        wsv=wsv,
        isi=isi,
        csi=csi,
        rso=rso,
    )
