"""
Shared loading/computation logic for the GLC-X-10 (Wotton et al. 2009) published FBP System test
cases, used by test_fbp_glc_x_10.py (reads the vendored CSVs directly) and
test_fbp_glc_x_10_rasters.py (reads the equivalent GeoTIFF fixtures generated by
generate_glc_x_10_rasters.py from those same CSVs), both parametrized over both sources. See
https://github.com/bcgov/wps/issues/4893.

The cffdrs_r_test_fbp_*.csv files in data/ are the CFFDRS working group's own digitized
transcription of the paper's Tables 4/5. They're copied from the R cffdrs package
(github.com/cffdrs/cffdrs_r: data/test_fbp.csv, tests/testthat/data/fbp_01.csv, fbp_04.csv),
by way of cffdrs_py's own copy of those same files (cffdrs/tests/data/test_fbp.csv, fbp_01.csv, fbp_04.csv,
not included in the installed cffdrs_py package, hence vendored here rather than depended on at runtime).

The glc_x_10_paper_*.csv files are a second, independent transcription: extracted directly from
Tables 4-6 of the published PDF (Fo123-2-10-2009-eng.pdf) via `pdftotext -layout`, without going
through the R package at all. They exist to cross-validate the R-sourced CSVs above against the
actual paper rather than trusting that chain of custody; see load_glc_x_10_cases.

"""

import csv
import functools
import math
from pathlib import Path
from typing import NamedTuple

import numpy as np
from cffdrs.constants import D1, FUEL_TYPE_CODES, O1A, O1B, S1, S2, S3

from cffdrs_vec import fbp
from cffdrs_vec.fwi import vectorized_isi

DATA_DIR = Path(__file__).parent / "data"
RASTER_DIR = Path(__file__).parent / "fixtures" / "glc_x_10"
PAPER_RASTER_DIR = Path(__file__).parent / "fixtures" / "glc_x_10_paper"

# Fuel types with no crown to burn - _fire_behaviour_prediction always zeroes FMC for these.
NO_CROWN_FUEL_TYPE_CODES = (D1, S1, S2, S3, O1A, O1B)

FIRE_TYPE_BY_FD_CODE = {"S": "SUR", "I": "IC", "C": "CC"}

# Table 7 (FCFDG 1992) CBH/CFL defaults, used because the GLC-X-10 dataset leaves CBH/CFL blank
# for every case (relying on cffdrs's own per-fuel-type defaults). Matches
# wps_shared.fuel_types.FUEL_TYPE_DEFAULTS exactly.
CBH_DEFAULT = {
    "C1": 2,
    "C2": 3,
    "C3": 8,
    "C4": 4,
    "C5": 18,
    "C6": 7,
    "C7": 10,
    "D1": 0,
    "M1": 6,
    "M2": 6,
    "M3": 6,
    "M4": 6,
    "S1": 0,
    "S2": 0,
    "S3": 0,
    "O1A": 0,
    "O1B": 0,
}
CFL_DEFAULT = {
    "C1": 0.75,
    "C2": 0.8,
    "C3": 1.15,
    "C4": 1.2,
    "C5": 1.2,
    "C6": 1.8,
    "C7": 0.5,
    "D1": 0,
    "M1": 0.8,
    "M2": 0.8,
    "M3": 0.8,
    "M4": 0.8,
    "S1": 0,
    "S2": 0,
    "S3": 0,
    "O1A": 0,
    "O1B": 0,
}
PC_DEFAULT = {
    "C1": 100,
    "C2": 100,
    "C3": 100,
    "C4": 100,
    "C5": 100,
    "C6": 100,
    "C7": 100,
    "D1": 0,
    "M1": 50,
    "M2": 50,
    "M3": 0,
    "M4": 0,
    "S1": 0,
    "S2": 0,
    "S3": 0,
    "O1A": 0,
    "O1B": 0,
}
PDF_DEFAULT = {
    "C1": 0,
    "C2": 0,
    "C3": 0,
    "C4": 0,
    "C5": 0,
    "C6": 0,
    "C7": 0,
    "D1": 0,
    "M1": 0,
    "M2": 0,
    "M3": 30,
    "M4": 30,
    "S1": 0,
    "S2": 0,
    "S3": 0,
    "O1A": 0,
    "O1B": 0,
}

# Raster fixture variable names, in the order generate_glc_x_10_rasters.py writes them - shared so
# the generator and the raster-reading test can't drift apart on file naming.
INPUT_RASTER_NAMES = [
    "fuel_type_code",
    "lat",
    "lon",
    "elv",
    "ffmc",
    "bui",
    "ws",
    "wd",
    "gs",
    "dj",
    "d0",
    "aspect",
    "pc",
    "pdf",
    "cc",
    "gfl",
    "cbh",
    "cfl",
]
OUTPUT_RASTER_NAMES = ["ros", "hfi", "cfb", "sfc", "tfc", "raz"]


def parse_float(value: str) -> float:
    value = value.strip()
    if value == "" or value.upper() == "NA":
        return math.nan
    return float(value)


def normalize_fuel_type(value: str) -> str:
    return value.strip().upper().replace("-", "")


def with_default(values: np.ndarray, fuel_types: list, defaults: dict) -> np.ndarray:
    fallback = np.array([defaults[ft] for ft in fuel_types], dtype=np.float64)
    return np.where(np.isnan(values), fallback, values)


def load_rows(filename: str) -> list[dict]:
    with open(DATA_DIR / filename) as f:
        return list(csv.DictReader(f))


# Column names differ (and one field is fully renamed - see below), but every other CSV shape is
# the same for both sources: an input CSV with a "FuelType" column, and an output CSV with
# ROS/HFI/CFB/SFC/TFC/RAZ/FD columns keyed by the same id.
R_PACKAGE_COLUMNS = {
    "lat": "LAT", "lon": "LONG", "elv": "ELV", "ffmc": "FFMC", "bui": "BUI", "ws": "WS",
    "wd": "WD", "gs": "GS", "dj": "Dj", "d0": "D0", "gfl": "GFL", "pc": "PC", "pdf": "PDF",
    "cc": "cc",
}
PAPER_COLUMNS = {
    "lat": "Lat", "lon": "Long", "elv": "Elev", "ffmc": "FFMC", "bui": "BUI", "ws": "WS",
    "wd": "WDIR", "gs": "GS", "dj": "Dj", "d0": "D0", "gfl": "GFL", "pc": "PC", "pdf": "PDF",
    "cc": "C",
}


class GLCX10Inputs(NamedTuple):
    """One field per array calculate_primary_output() needs - RasterCases in
    test_fbp_glc_x_10_rasters.py builds the same shape from GeoTIFFs instead of the CSVs.
    """

    fuel_type_codes: np.ndarray
    lat: np.ndarray
    lon: np.ndarray
    elv: np.ndarray
    ffmc: np.ndarray
    bui: np.ndarray
    ws: np.ndarray
    wd_rad: np.ndarray
    gs: np.ndarray
    dj: np.ndarray
    d0: np.ndarray
    aspect_rad: np.ndarray
    gfl: np.ndarray
    pc: np.ndarray
    pdf: np.ndarray
    cc: np.ndarray
    cbh: np.ndarray
    cfl: np.ndarray


class GLCX10ExpectedOutputs(NamedTuple):
    """The published Table 5 outputs, in the same case order as the GLCX10Inputs they go with."""

    ros: np.ndarray
    hfi: np.ndarray
    cfb: np.ndarray
    sfc: np.ndarray
    tfc: np.ndarray
    raz: np.ndarray
    fire_type: list


def load_glc_x_10_cases(
    source, input_csv, output_csv, id_input_col, id_output_col, columns
) -> tuple[GLCX10Inputs, GLCX10ExpectedOutputs]:
    """Loads all 20 GLC-X-10 cases as batched arrays, plus the published Table 5 outputs.

    Shared loader for both data sources (see R_PACKAGE_COLUMNS/PAPER_COLUMNS above for where
    they're just a column rename) - load_r_package_cases/load_paper_cases below bind `source` so
    each is still a plain zero-arg callable.

    Aspect and CBH/CFL are handled as an explicit `source` branch rather than folded into the
    column map, because they're not just differently-named columns:
    - the paper gives SAZ (upslope azimuth) directly rather than cffdrs's own Aspect
      (downslope-facing direction) input convention; SAZ = Aspect + 180 deg (see fbp.r comments),
      so the paper source has to invert it, not just rename it.
    - Table 4 (the paper's own table) has no CBH/CFL columns at all - cffdrs's own per-fuel-type
      defaults always apply, there's no column to read.
    """
    input_rows = load_rows(input_csv)
    output_by_id = {row[id_output_col]: row for row in load_rows(output_csv)}

    ids = [row[id_input_col] for row in input_rows]
    fuel_types = [normalize_fuel_type(row["FuelType"]) for row in input_rows]
    fuel_type_codes = np.array([FUEL_TYPE_CODES[ft] for ft in fuel_types], dtype=np.int64)

    lat = np.array([parse_float(row[columns["lat"]]) for row in input_rows])
    lon = np.array([parse_float(row[columns["lon"]]) for row in input_rows])
    elv = np.nan_to_num(np.array([parse_float(row[columns["elv"]]) for row in input_rows]))
    ffmc = np.array([parse_float(row[columns["ffmc"]]) for row in input_rows])
    bui = np.array([parse_float(row[columns["bui"]]) for row in input_rows])
    ws = np.array([parse_float(row[columns["ws"]]) for row in input_rows])
    # Blank only for case 4 (both sources), where WS=0 makes wind direction physically
    # irrelevant.
    wd_rad = np.radians(
        np.nan_to_num(np.array([parse_float(row[columns["wd"]]) for row in input_rows]))
    )
    gs = np.array([parse_float(row[columns["gs"]]) for row in input_rows])
    dj = np.array([parse_float(row[columns["dj"]]) for row in input_rows])
    d0 = np.nan_to_num(np.array([parse_float(row[columns["d0"]]) for row in input_rows]))
    gfl = np.nan_to_num(np.array([parse_float(row[columns["gfl"]]) for row in input_rows]))
    pc = with_default(
        np.array([parse_float(row[columns["pc"]]) for row in input_rows]), fuel_types, PC_DEFAULT
    )
    pdf = with_default(
        np.array([parse_float(row[columns["pdf"]]) for row in input_rows]),
        fuel_types,
        PDF_DEFAULT,
    )
    cc = np.nan_to_num(np.array([parse_float(row[columns["cc"]]) for row in input_rows]))

    if source == "r_package":
        aspect_rad = np.radians(
            np.nan_to_num(np.array([parse_float(row["Aspect"]) for row in input_rows]))
        )
        cbh = with_default(
            np.array([parse_float(row["CBH"]) for row in input_rows]), fuel_types, CBH_DEFAULT
        )
        cfl = with_default(
            np.array([parse_float(row["CFL"]) for row in input_rows]), fuel_types, CFL_DEFAULT
        )
    elif source == "paper":
        # Blank only for case 14, where GS=0 makes slope direction physically irrelevant.
        saz_deg = np.nan_to_num(np.array([parse_float(row["SAZ"]) for row in input_rows]))
        aspect_rad = np.radians((saz_deg - 180) % 360)
        cbh = np.array([CBH_DEFAULT[ft] for ft in fuel_types])
        cfl = np.array([CFL_DEFAULT[ft] for ft in fuel_types])
    else:
        raise ValueError(f"Unknown source: {source!r}")

    inputs = GLCX10Inputs(
        fuel_type_codes=fuel_type_codes,
        lat=lat,
        lon=lon,
        elv=elv,
        ffmc=ffmc,
        bui=bui,
        ws=ws,
        wd_rad=wd_rad,
        gs=gs,
        dj=dj,
        d0=d0,
        aspect_rad=aspect_rad,
        gfl=gfl,
        pc=pc,
        pdf=pdf,
        cc=cc,
        cbh=cbh,
        cfl=cfl,
    )
    expected = GLCX10ExpectedOutputs(
        ros=np.array([float(output_by_id[i]["ROS"]) for i in ids]),
        hfi=np.array([float(output_by_id[i]["HFI"]) for i in ids]),
        cfb=np.array([float(output_by_id[i]["CFB"]) for i in ids]),
        sfc=np.array([float(output_by_id[i]["SFC"]) for i in ids]),
        tfc=np.array([float(output_by_id[i]["TFC"]) for i in ids]),
        raz=np.array([float(output_by_id[i]["RAZ"]) for i in ids]),
        fire_type=[FIRE_TYPE_BY_FD_CODE[output_by_id[i]["FD"]] for i in ids],
    )
    return inputs, expected


load_r_package_cases = functools.partial(
    load_glc_x_10_cases,
    "r_package",
    "cffdrs_r_test_fbp_inputs.csv",
    "cffdrs_r_test_fbp_primary_outputs.csv",
    "id",
    "ID",
    R_PACKAGE_COLUMNS,
)
load_paper_cases = functools.partial(
    load_glc_x_10_cases,
    "paper",
    "glc_x_10_paper_inputs.csv",
    "glc_x_10_paper_primary_outputs.csv",
    "TestCase",
    "TestCase",
    PAPER_COLUMNS,
)


def calculate_primary_output(inputs: GLCX10Inputs):
    """Mirrors cffdrs.fire_behaviour_prediction._fire_behaviour_prediction's Primary output,
    composed from cffdrs_vec.fbp's vectorized functions over the whole batch at once.

    `inputs` just needs GLCX10Inputs's fields - RasterCases in test_fbp_glc_x_10_rasters.py builds
    the same shape from GeoTIFFs instead of the CSVs.
    """
    n = len(inputs.fuel_type_codes)

    # Corrections to reorient Wind Azimuth (WAZ) and Uphill slope azimuth (SAZ) - Eq. matches
    # _fire_behaviour_prediction exactly.
    waz = inputs.wd_rad + math.pi
    waz = np.where(waz > 2 * math.pi, waz - 2 * math.pi, waz)
    saz = inputs.aspect_rad + math.pi
    saz = np.where(saz > 2 * math.pi, saz - 2 * math.pi, saz)

    fmc = fbp.vectorized_foliar_moisture_content(
        inputs.lat, inputs.lon, inputs.elv, inputs.dj, inputs.d0
    )
    no_crown = np.isin(inputs.fuel_type_codes, NO_CROWN_FUEL_TYPE_CODES)
    fmc = np.where(no_crown, 0.0, fmc)

    sfc = fbp.vectorized_surface_fuel_consumption(
        inputs.fuel_type_codes, inputs.ffmc, inputs.bui, inputs.pc, inputs.gfl
    )

    # slope_adjustment()'s isi parameter is unused by the underlying formula (it derives its own
    # zero-wind ISI internally), so any placeholder value works here.
    wsv0, raz0 = fbp.vectorized_slope_adjustment(
        inputs.fuel_type_codes,
        inputs.ffmc,
        inputs.bui,
        inputs.ws,
        waz,
        inputs.gs,
        saz,
        fmc,
        sfc,
        inputs.pc,
        inputs.pdf,
        inputs.cc,
        inputs.cbh,
        np.zeros(n),
    )
    slope_active = (inputs.gs > 0) & (inputs.ffmc > 0)
    wsv = np.where(slope_active, wsv0, inputs.ws)
    raz = np.where(slope_active, raz0, waz)

    # All 20 published cases leave ISI as "not observed" (0), so it's always derived from the
    # slope-adjusted wind speed here, same as _fire_behaviour_prediction does.
    isi = vectorized_isi(inputs.ffmc, wsv, True)

    ros, cfb, _csi, _rso = fbp.vectorized_rate_of_spread_extended(
        inputs.fuel_type_codes,
        isi,
        inputs.bui,
        fmc,
        sfc,
        inputs.pc,
        inputs.pdf,
        inputs.cc,
        inputs.cbh,
    )
    cfb = np.where(inputs.cfl > 0, cfb, 0.0)

    tfc = fbp.vectorized_total_fuel_consumption(
        inputs.fuel_type_codes, inputs.cfl, cfb, sfc, inputs.pc, inputs.pdf
    )
    hfi = fbp.vectorized_fire_intensity(tfc, ros)

    raz_deg = np.degrees(raz)
    raz_deg = np.where(raz_deg == 360, 0.0, raz_deg)

    fire_type = np.full(n, "IC", dtype=object)
    fire_type[cfb < 0.1] = "SUR"
    fire_type[cfb >= 0.9] = "CC"

    return ros, hfi, cfb, sfc, tfc, raz_deg, fire_type
