"""
Shared loading/computation logic for the GLC-X-10 (Wotton et al. 2009) published FBP System test
cases, used by test_fbp_glc_x_10.py's test_fbp_glc_x_10 (reads the vendored CSVs directly) and
test_fbp_glc_x_10_rasters (reads the equivalent GeoTIFF fixtures generated by
generate_glc_x_10_rasters.py from those same CSVs), both parametrized over both sources. See
https://github.com/bcgov/wps/issues/4893.

The cffdrs_r_test_fbp_*.csv files in data/ are the CFFDRS working group's own digitized
transcription of the paper's Tables 4/5. They're copied from the R cffdrs package
(github.com/cffdrs/cffdrs_r: data/test_fbp.csv, tests/testthat/data/fbp_01.csv, fbp_04.csv),
by way of cffdrs_py's own copy of those same files (cffdrs/tests/data/test_fbp.csv, fbp_01.csv, fbp_04.csv,
not included in the installed cffdrs_py package, hence vendored here rather than depended on at runtime).

The glc_x_10_paper_*.csv files are a second, independent transcription: extracted directly from
Tables 4-6 of the published PDF (Fo123-2-10-2009-eng.pdf) via `pdftotext -layout`, without going
through the R package at all. They exist to cross-validate the R-sourced CSVs above against the
actual paper rather than trusting that chain of custody; see PaperSource.

"""

import csv
import math
from abc import ABC, abstractmethod
from pathlib import Path
from typing import NamedTuple

import numpy as np
from cffdrs.constants import FUEL_TYPE_CODES
from cffdrs.models import FBPInput
from wps_shared.fuel_types import FUEL_TYPE_DEFAULTS
from wps_shared.geospatial.wps_dataset import WPSDataset

DATA_DIR = Path(__file__).parent / "data"

FIRE_TYPE_BY_FD_CODE = {"S": "SUR", "I": "IC", "C": "CC"}
# vectorized_fire_behaviour_prediction's fd_code output uses cffdrs's own FD_SURFACE/
# FD_INTERMITTENT/FD_CROWN int constants (0/1/2) instead of the "S"/"I"/"C" letter codes above.
FIRE_TYPE_BY_FD_CODE_INT = {0: "SUR", 1: "IC", 2: "CC"}

# The fuel types covered by the GLC-X-10 paper - a subset of FUEL_TYPE_DEFAULTS (which also
# carries D2, C7B and the M2_25 variant, none of which appear in this dataset).
PAPER_FUEL_TYPE_CODES = (
    "C1",
    "C2",
    "C3",
    "C4",
    "C5",
    "C6",
    "C7",
    "D1",
    "M1",
    "M2",
    "M3",
    "M4",
    "S1",
    "S2",
    "S3",
    "O1A",
    "O1B",
)

# Table 7 (FCFDG 1992) CBH/CFL/PC/PDF defaults, used because the GLC-X-10 dataset leaves them
# blank for every case (relying on cffdrs's own per-fuel-type defaults).
CBH_DEFAULT = {ft: FUEL_TYPE_DEFAULTS[ft]["CBH"] for ft in PAPER_FUEL_TYPE_CODES}
CFL_DEFAULT = {ft: FUEL_TYPE_DEFAULTS[ft]["CFL"] for ft in PAPER_FUEL_TYPE_CODES}
PC_DEFAULT = {ft: FUEL_TYPE_DEFAULTS[ft]["PC"] for ft in PAPER_FUEL_TYPE_CODES}
PDF_DEFAULT = {ft: FUEL_TYPE_DEFAULTS[ft]["PDF"] for ft in PAPER_FUEL_TYPE_CODES}

# Raster fixture variable names, in the order generate_glc_x_10_rasters.py writes them - shared so
# the generator and the raster-reading test can't drift apart on file naming.
INPUT_RASTER_NAMES = [
    "fuel_type_code",
    "lat",
    "lon",
    "elv",
    "ffmc",
    "bui",
    "ws",
    "wd",
    "gs",
    "dj",
    "d0",
    "aspect",
    "pc",
    "pdf",
    "cc",
    "gfl",
    "cbh",
    "cfl",
]
OUTPUT_RASTER_NAMES = ["ros", "hfi", "cfb", "sfc", "tfc", "raz"]


def parse_float(value: str) -> float:
    value = value.strip()
    if value == "" or value.upper() == "NA":
        return math.nan
    return float(value)


def normalize_fuel_type(value: str) -> str:
    return value.strip().upper().replace("-", "")


def with_default(values: np.ndarray, fuel_types: list, defaults: dict) -> np.ndarray:
    fallback = np.array([defaults[ft] for ft in fuel_types], dtype=np.float64)
    return np.where(np.isnan(values), fallback, values)


def load_rows(filename: str) -> list[dict]:
    with open(DATA_DIR / filename) as f:
        return list(csv.DictReader(f))


def read_raster(raster_dir: Path, name: str) -> np.ndarray:
    """Returns the raster's full 2-D (row, column) array, same shape a real production raster
    would have - cffdrs_vec's vectorized functions are shape-preserving, so nothing downstream
    needs to flatten this the way a real 2-D SFMS grid wouldn't be flattened either. Our fixtures
    happen to be 1 row x 20 columns (one column per GLC-X-10 case), but nothing here assumes that.
    """
    with WPSDataset(str(raster_dir / f"{name}.tif")) as ds:
        array, _nodata = ds.replace_nodata_with(np.nan)
    return array


class GLCX10Inputs(NamedTuple):
    """One field per array fbp.vectorized_fire_behaviour_prediction needs - GLCX10Source.
    load_raster_inputs() builds the same shape from GeoTIFFs instead of the CSVs.

    The field names below are the CFFDRS system's own abbreviations (same ones cffdrs_vec.fbp and
    the R cffdrs package use), spelled out here so they don't have to be reverse-engineered:
      elv        - Elevation (m)
      ffmc       - Fine Fuel Moisture Code
      bui        - Buildup Index
      ws         - Wind Speed (km/h)
      wd_rad     - Wind Direction (radians)
      gs         - Ground Slope (%)
      dj         - Day of year (Julian date)
      d0         - Julian date of minimum Foliar Moisture Content (0 if unknown)
      aspect_rad - Slope Aspect (radians)
      gfl        - Grass Fuel Load (kg/m^2)
      pc         - Percent Conifer (%)
      pdf        - Percent Dead Balsam Fir (%)
      cc         - Degree of Curing, grass fuel types only (%)
      cbh        - Crown Base Height (m)
      cfl        - Crown Fuel Load (kg/m^2)
    """

    fuel_type_codes: np.ndarray
    lat: np.ndarray
    lon: np.ndarray
    elv: np.ndarray
    ffmc: np.ndarray
    bui: np.ndarray
    ws: np.ndarray
    wd_rad: np.ndarray
    gs: np.ndarray
    dj: np.ndarray
    d0: np.ndarray
    aspect_rad: np.ndarray
    gfl: np.ndarray
    pc: np.ndarray
    pdf: np.ndarray
    cc: np.ndarray
    cbh: np.ndarray
    cfl: np.ndarray


class GLCX10ExpectedOutputs(NamedTuple):
    """The published Table 5 outputs, in the same case order as the GLCX10Inputs they go with.

    ros        - Rate of Spread (m/min)
    hfi        - Head Fire Intensity (kW/m)
    cfb        - Crown Fraction Burned (0-1)
    sfc        - Surface Fuel Consumption (kg/m^2)
    tfc        - Total Fuel Consumption (kg/m^2)
    raz        - net effective spread direction after wind/slope adjustment (degrees)
    fire_type  - "S"/"I"/"C" for Surface/Intermittent-crown/Crowning
    """

    ros: np.ndarray
    hfi: np.ndarray
    cfb: np.ndarray
    sfc: np.ndarray
    tfc: np.ndarray
    raz: np.ndarray
    fire_type: list


class GLCX10Source(ABC):
    """Abstract base for the two independent GLC-X-10 data sources: RPackageSource and
    PaperSource below (the only two subclasses. A source knows how to load its own CSV-sourced
    inputs/expected-outputs (load()), its own GeoTIFF-sourced inputs (load_raster_inputs()),
    and how loose a tolerance its ROS/HFI/CFB comparisons need (rtol_ros_hfi/atol_cfb.
    See test_fbp_glc_x_10.py for why "paper" needs a looser one than "r_package").

    Tests should parametrize on the GLCX10Source instance itself (`@pytest.mark.parametrize(
    "source", GLC_X_10_SOURCES, ...)`) rather than on its individual fields/methods, so each test
    only has to read the one or two attributes it actually needs instead of every test being
    forced to declare all of them as separate parametrize columns.
    """

    name: str
    input_csv: str
    output_csv: str
    id_input_col: str
    id_output_col: str
    raster_dir: Path
    columns: dict
    # ROS/HFI/CFB tolerances - looser for "paper" to absorb the small, known drift between the
    # paper's 2009-vintage published values and what the current FBP equations compute (see
    # test_fbp_glc_x_10.py).
    rtol_ros_hfi: float
    atol_cfb: float

    @abstractmethod
    def _aspect_rad_cbh_cfl(
        self, input_rows: list[dict], fuel_types: list[str]
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Returns (aspect_rad, cbh, cfl) - the 3 fields that aren't just a column rename between
        sources (see RPackageSource/PaperSource for why each has to override this).
        """

    @abstractmethod
    def raster_aspect_cbh_cfl(
        self, input_rows: list[dict]
    ) -> tuple[list[float], list[float], list[float]]:
        """Returns (aspect_deg, cbh, cfl) as raw per-case value lists ready to write straight to
        a raster. Unlike _aspect_rad_cbh_cfl() above, missing values stay NaN here rather than
        being filled with a default, so the raster round-trip (write here, then default-fill on
        read in load_raster_inputs()) can prove that same default-filling logic actually works
        when driven by a raster read, not just a CSV read.
        """

    def load(self) -> tuple[GLCX10Inputs, GLCX10ExpectedOutputs]:
        """Loads all 20 GLC-X-10 cases as batched arrays, plus the published Table 5 outputs."""
        input_rows = load_rows(self.input_csv)
        output_by_id = {row[self.id_output_col]: row for row in load_rows(self.output_csv)}

        ids = [row[self.id_input_col] for row in input_rows]
        fuel_types = [normalize_fuel_type(row["FuelType"]) for row in input_rows]
        fuel_type_codes = np.array([FUEL_TYPE_CODES[ft] for ft in fuel_types], dtype=np.int64)

        columns = self.columns
        lat = np.array([parse_float(row[columns["lat"]]) for row in input_rows])
        lon = np.array([parse_float(row[columns["lon"]]) for row in input_rows])
        elv = np.nan_to_num(np.array([parse_float(row[columns["elv"]]) for row in input_rows]))
        ffmc = np.array([parse_float(row[columns["ffmc"]]) for row in input_rows])
        bui = np.array([parse_float(row[columns["bui"]]) for row in input_rows])
        ws = np.array([parse_float(row[columns["ws"]]) for row in input_rows])
        # Blank only for case 4 (both sources), where WS=0 makes wind direction physically
        # irrelevant.
        wd_rad = np.radians(
            np.nan_to_num(np.array([parse_float(row[columns["wd"]]) for row in input_rows]))
        )
        gs = np.array([parse_float(row[columns["gs"]]) for row in input_rows])
        dj = np.array([parse_float(row[columns["dj"]]) for row in input_rows])
        d0 = np.nan_to_num(np.array([parse_float(row[columns["d0"]]) for row in input_rows]))
        gfl = np.nan_to_num(np.array([parse_float(row[columns["gfl"]]) for row in input_rows]))
        pc = with_default(
            np.array([parse_float(row[columns["pc"]]) for row in input_rows]),
            fuel_types,
            PC_DEFAULT,
        )
        pdf = with_default(
            np.array([parse_float(row[columns["pdf"]]) for row in input_rows]),
            fuel_types,
            PDF_DEFAULT,
        )
        cc = np.nan_to_num(np.array([parse_float(row[columns["cc"]]) for row in input_rows]))

        aspect_rad, cbh, cfl = self._aspect_rad_cbh_cfl(input_rows, fuel_types)

        inputs = GLCX10Inputs(
            fuel_type_codes=fuel_type_codes,
            lat=lat,
            lon=lon,
            elv=elv,
            ffmc=ffmc,
            bui=bui,
            ws=ws,
            wd_rad=wd_rad,
            gs=gs,
            dj=dj,
            d0=d0,
            aspect_rad=aspect_rad,
            gfl=gfl,
            pc=pc,
            pdf=pdf,
            cc=cc,
            cbh=cbh,
            cfl=cfl,
        )
        expected = GLCX10ExpectedOutputs(
            ros=np.array([float(output_by_id[i]["ROS"]) for i in ids]),
            hfi=np.array([float(output_by_id[i]["HFI"]) for i in ids]),
            cfb=np.array([float(output_by_id[i]["CFB"]) for i in ids]),
            sfc=np.array([float(output_by_id[i]["SFC"]) for i in ids]),
            tfc=np.array([float(output_by_id[i]["TFC"]) for i in ids]),
            raz=np.array([float(output_by_id[i]["RAZ"]) for i in ids]),
            fire_type=[FIRE_TYPE_BY_FD_CODE[output_by_id[i]["FD"]] for i in ids],
        )
        return inputs, expected

    def load_raster_inputs(self) -> GLCX10Inputs:
        """Same GLCX10Inputs shape load() returns, but read from `self.raster_dir`'s GeoTIFF
        fixtures instead of `self.input_csv` - the raster-reading logic itself doesn't differ
        between sources, only which directory/CSV it points at, so there's nothing for
        RPackageSource/PaperSource to override here.
        """
        raster = {name: read_raster(self.raster_dir, name) for name in INPUT_RASTER_NAMES}

        # fuel type names aren't stored in the rasters (only the numeric code is) - needed here
        # only to look up PC/PDF/CBH/CFL defaults, same as load() does from the CSV directly.
        input_rows = load_rows(self.input_csv)
        fuel_types = [normalize_fuel_type(row["FuelType"]) for row in input_rows]

        return GLCX10Inputs(
            fuel_type_codes=raster["fuel_type_code"].astype(np.int64),
            lat=raster["lat"],
            lon=raster["lon"],
            elv=np.nan_to_num(raster["elv"]),
            ffmc=raster["ffmc"],
            bui=raster["bui"],
            ws=raster["ws"],
            wd_rad=np.radians(np.nan_to_num(raster["wd"])),
            gs=raster["gs"],
            dj=raster["dj"],
            d0=np.nan_to_num(raster["d0"]),
            aspect_rad=np.radians(np.nan_to_num(raster["aspect"])),
            gfl=np.nan_to_num(raster["gfl"]),
            pc=with_default(raster["pc"], fuel_types, PC_DEFAULT),
            pdf=with_default(raster["pdf"], fuel_types, PDF_DEFAULT),
            cc=np.nan_to_num(raster["cc"]),
            cbh=with_default(raster["cbh"], fuel_types, CBH_DEFAULT),
            cfl=with_default(raster["cfl"], fuel_types, CFL_DEFAULT),
        )

    def to_fbp_inputs(self) -> list[FBPInput]:
        """One FBPInput per case, in the same order as load()'s arrays used by
        test_fbp_matches_cffdrs.py to call cffdrs's own, real fire_behaviour_prediction() once per
        case, as the ground truth fbp.vectorized_fire_behaviour_prediction gets checked against.
        Doesn't go through any of cffdrs_vec's own vectorized/jitted code at all.

        Unlike load(), FBPInput takes wd/aspect in degrees, not radians (it converts internally),
        so this reads angles straight from the CSV rather than reusing load()'s wd_rad/aspect_rad.
        PC/PDF/CBH/CFL are defaulted here exactly like load() does, rather than left blank for
        FBPInput/_fire_behaviour_prediction's own internal defaulting: PC/PDF's built-in default
        is a flat 50/35 regardless of fuel type, not the fuel-type-specific values this test
        (and production code) actually uses, so leaving them blank would silently compare against
        the wrong PC/PDF for every case that omits them.
        """
        input_rows = load_rows(self.input_csv)
        ids = [row[self.id_input_col] for row in input_rows]
        fuel_types = [normalize_fuel_type(row["FuelType"]) for row in input_rows]
        columns = self.columns
        aspect_deg, raw_cbh, raw_cfl = self.raster_aspect_cbh_cfl(input_rows)
        pc = with_default(
            np.array([parse_float(row[columns["pc"]]) for row in input_rows]),
            fuel_types,
            PC_DEFAULT,
        )
        pdf = with_default(
            np.array([parse_float(row[columns["pdf"]]) for row in input_rows]),
            fuel_types,
            PDF_DEFAULT,
        )
        cbh = with_default(np.array(raw_cbh), fuel_types, CBH_DEFAULT)
        cfl = with_default(np.array(raw_cfl), fuel_types, CFL_DEFAULT)

        return [
            FBPInput(
                id=ids[i],
                fuel_type=fuel_types[i],
                ffmc=parse_float(input_rows[i][columns["ffmc"]]),
                bui=parse_float(input_rows[i][columns["bui"]]),
                ws=parse_float(input_rows[i][columns["ws"]]),
                wd=float(np.nan_to_num(parse_float(input_rows[i][columns["wd"]]))),
                gs=parse_float(input_rows[i][columns["gs"]]),
                aspect=float(np.nan_to_num(aspect_deg[i])),
                pc=pc[i],
                pdf=pdf[i],
                cc=float(np.nan_to_num(parse_float(input_rows[i][columns["cc"]]))),
                gfl=float(np.nan_to_num(parse_float(input_rows[i][columns["gfl"]]))),
                cbh=cbh[i],
                cfl=cfl[i],
                lat=parse_float(input_rows[i][columns["lat"]]),
                lon=parse_float(input_rows[i][columns["lon"]]),
                elv=float(np.nan_to_num(parse_float(input_rows[i][columns["elv"]]))),
                dj=parse_float(input_rows[i][columns["dj"]]),
                d0=float(np.nan_to_num(parse_float(input_rows[i][columns["d0"]]))),
            )
            for i in range(len(input_rows))
        ]

    def read_raster_output(self, name: str) -> np.ndarray:
        return read_raster(self.raster_dir, name)


class RPackageSource(GLCX10Source):
    """The CFFDRS working group's own digitized transcription of the paper's Tables 4/5. Copied
    from the R cffdrs package (github.com/cffdrs/cffdrs_r: data/test_fbp.csv,
    tests/testthat/data/fbp_01.csv, fbp_04.csv), by way of cffdrs_py's own copy of those same
    files (not included in the installed cffdrs_py package, hence vendored here rather than
    depended on at runtime).
    """

    name = "r_package"
    input_csv = "cffdrs_r_test_fbp_inputs.csv"
    output_csv = "cffdrs_r_test_fbp_primary_outputs.csv"
    id_input_col = "id"
    id_output_col = "ID"
    raster_dir = Path(__file__).parent / "fixtures" / "glc_x_10"
    # Column names differ from PaperSource's (and one field is fully renamed - see
    # _aspect_rad_cbh_cfl below), but every other CSV shape is the same for both sources: an
    # input CSV with a "FuelType" column, and an output CSV with ROS/HFI/CFB/SFC/TFC/RAZ/FD
    # columns keyed by the same id.
    columns = {
        "lat": "LAT",
        "lon": "LONG",
        "elv": "ELV",
        "ffmc": "FFMC",
        "bui": "BUI",
        "ws": "WS",
        "wd": "WD",
        "gs": "GS",
        "dj": "Dj",
        "d0": "D0",
        "gfl": "GFL",
        "pc": "PC",
        "pdf": "PDF",
        "cc": "cc",
    }
    rtol_ros_hfi = 1e-3
    atol_cfb = 1e-3

    def _aspect_rad_cbh_cfl(self, input_rows, fuel_types):
        aspect_rad = np.radians(
            np.nan_to_num(np.array([parse_float(row["Aspect"]) for row in input_rows]))
        )
        cbh = with_default(
            np.array([parse_float(row["CBH"]) for row in input_rows]), fuel_types, CBH_DEFAULT
        )
        cfl = with_default(
            np.array([parse_float(row["CFL"]) for row in input_rows]), fuel_types, CFL_DEFAULT
        )
        return aspect_rad, cbh, cfl

    def raster_aspect_cbh_cfl(self, input_rows):
        aspect_deg = [parse_float(row["Aspect"]) for row in input_rows]
        cbh = [parse_float(row["CBH"]) for row in input_rows]
        cfl = [parse_float(row["CFL"]) for row in input_rows]
        return aspect_deg, cbh, cfl


class PaperSource(GLCX10Source):
    """A second, independent transcription: extracted directly from Tables 4-6 of the published
    PDF (Fo123-2-10-2009-eng.pdf) via `pdftotext -layout`, without going through the R package at
    all. Exists to cross-validate RPackageSource's CSVs against the actual paper rather than
    trusting that chain of custody.
    """

    name = "paper"
    input_csv = "glc_x_10_paper_inputs.csv"
    output_csv = "glc_x_10_paper_primary_outputs.csv"
    id_input_col = "TestCase"
    id_output_col = "TestCase"
    raster_dir = Path(__file__).parent / "fixtures" / "glc_x_10_paper"
    columns = {
        "lat": "Lat",
        "lon": "Long",
        "elv": "Elev",
        "ffmc": "FFMC",
        "bui": "BUI",
        "ws": "WS",
        "wd": "WDIR",
        "gs": "GS",
        "dj": "Dj",
        "d0": "D0",
        "gfl": "GFL",
        "pc": "PC",
        "pdf": "PDF",
        "cc": "C",
    }
    rtol_ros_hfi = 1e-2
    atol_cfb = 3e-3

    def _aspect_rad_cbh_cfl(self, input_rows, fuel_types):
        # The paper gives SAZ (upslope azimuth) directly rather than cffdrs's own Aspect
        # (downslope-facing direction) input convention; SAZ = Aspect + 180 deg (see fbp.r
        # comments), so invert that here. Blank only for case 14, where GS=0 makes slope
        # direction physically irrelevant.
        saz_deg = np.nan_to_num(np.array([parse_float(row["SAZ"]) for row in input_rows]))
        aspect_rad = np.radians((saz_deg - 180) % 360)
        # Table 4 (the paper's own table) has no CBH/CFL columns at all - cffdrs's own
        # per-fuel-type defaults always apply, there's no column to read.
        cbh = np.array([CBH_DEFAULT[ft] for ft in fuel_types])
        cfl = np.array([CFL_DEFAULT[ft] for ft in fuel_types])
        return aspect_rad, cbh, cfl

    def raster_aspect_cbh_cfl(self, input_rows):
        # Same nan_to_num-before-subtracting-180 order of operations as _aspect_rad_cbh_cfl
        # above, so the CSV-direct and raster-sourced paths resolve to the exact same aspect
        # value for case 14 (blank SAZ) even though it doesn't affect any result (case 14 has
        # GS=0, so slope direction is never actually used).
        saz_deg = np.nan_to_num(np.array([parse_float(row["SAZ"]) for row in input_rows]))
        aspect_deg = list((saz_deg - 180) % 360)
        # Table 4 has no CBH/CFL columns at all - always missing, always defaulted on read.
        cbh = [float("nan")] * len(input_rows)
        cfl = [float("nan")] * len(input_rows)
        return aspect_deg, cbh, cfl


R_PACKAGE = RPackageSource()
PAPER = PaperSource()
GLC_X_10_SOURCES = [R_PACKAGE, PAPER]
