"""
Same 20 published GLC-X-10 FBP System test cases and the same calculate_primary_output() as
test_fbp_glc_x_10.py, but sourced from the GeoTIFF fixtures under fixtures/glc_x_10/ and
fixtures/glc_x_10_paper/ (generated by generate_glc_x_10_rasters.py) instead of the CSVs directly,
showing cffdrs_vec.fbp's vectorized functions also work correctly when driven by real GDAL raster
reads (float32 storage, WPSDataset's nodata handling) rather than plain float64 arrays parsed
straight from CSV.

Parametrized over both data sources (r_package/paper) rather than split into two files, so the
tolerance divergence between them (paper's ROS/HFI/CFB need looser tolerance, see
test_fbp_glc_x_10.py for why) sits next to the R-sourced value instead of two files that have to
be compared side by side.
"""

import numpy as np
import pytest
from wps_shared.geospatial.wps_dataset import WPSDataset

from cffdrs_vec.tests._glc_x_10_data import (
    CBH_DEFAULT,
    CFL_DEFAULT,
    FIRE_TYPE_BY_FD_CODE,
    INPUT_RASTER_NAMES,
    PAPER_RASTER_DIR,
    PC_DEFAULT,
    PDF_DEFAULT,
    RASTER_DIR,
    GLCX10Inputs,
    calculate_primary_output,
    load_paper_cases,
    load_r_package_cases,
    load_rows,
    normalize_fuel_type,
    with_default,
)


def _read_raster(raster_dir, name: str) -> np.ndarray:
    with WPSDataset(str(raster_dir / f"{name}.tif")) as ds:
        array, _nodata = ds.replace_nodata_with(np.nan)
    return array[0]  # single-row raster - drop back to a 1-D, one-value-per-case array


def load_raster_inputs(raster_dir, input_csv) -> GLCX10Inputs:
    """Same GLCX10Inputs shape load_glc_x_10_cases() returns, but read from `raster_dir`'s
    GeoTIFF fixtures instead of `input_csv`.
    """
    raster = {name: _read_raster(raster_dir, name) for name in INPUT_RASTER_NAMES}

    # fuel type names aren't stored in the rasters (only the numeric code is) - needed here
    # only to look up PC/PDF/CBH/CFL defaults, same as load_glc_x_10_cases() does from the CSV
    # directly.
    input_rows = load_rows(input_csv)
    fuel_types = [normalize_fuel_type(row["FuelType"]) for row in input_rows]

    return GLCX10Inputs(
        fuel_type_codes=raster["fuel_type_code"].astype(np.int64),
        lat=raster["lat"],
        lon=raster["lon"],
        elv=np.nan_to_num(raster["elv"]),
        ffmc=raster["ffmc"],
        bui=raster["bui"],
        ws=raster["ws"],
        wd_rad=np.radians(np.nan_to_num(raster["wd"])),
        gs=raster["gs"],
        dj=raster["dj"],
        d0=np.nan_to_num(raster["d0"]),
        aspect_rad=np.radians(np.nan_to_num(raster["aspect"])),
        gfl=np.nan_to_num(raster["gfl"]),
        pc=with_default(raster["pc"], fuel_types, PC_DEFAULT),
        pdf=with_default(raster["pdf"], fuel_types, PDF_DEFAULT),
        cc=np.nan_to_num(raster["cc"]),
        cbh=with_default(raster["cbh"], fuel_types, CBH_DEFAULT),
        cfl=with_default(raster["cfl"], fuel_types, CFL_DEFAULT),
    )


@pytest.mark.parametrize(
    "raster_dir,input_csv,load_cases",
    [
        (RASTER_DIR, "cffdrs_r_test_fbp_inputs.csv", load_r_package_cases),
        (PAPER_RASTER_DIR, "glc_x_10_paper_inputs.csv", load_paper_cases),
    ],
    ids=["r_package", "paper"],
)
def test_raster_inputs_match_csv_inputs(raster_dir, input_csv, load_cases):
    """Sanity check that generate_glc_x_10_rasters.py's output hasn't drifted from the CSVs it
    was generated from - this would fail if the CSVs were updated without regenerating rasters.
    """
    raster_inputs = load_raster_inputs(raster_dir, input_csv)
    csv_inputs, _expected = load_cases()
    np.testing.assert_allclose(raster_inputs.fuel_type_codes, csv_inputs.fuel_type_codes)
    np.testing.assert_allclose(raster_inputs.ffmc, csv_inputs.ffmc)
    np.testing.assert_allclose(raster_inputs.bui, csv_inputs.bui)
    np.testing.assert_allclose(raster_inputs.cbh, csv_inputs.cbh)
    np.testing.assert_allclose(raster_inputs.cfl, csv_inputs.cfl)


@pytest.mark.parametrize(
    "raster_dir,input_csv,rtol",
    [
        (RASTER_DIR, "cffdrs_r_test_fbp_inputs.csv", 1e-3),
        (PAPER_RASTER_DIR, "glc_x_10_paper_inputs.csv", 1e-2),
    ],
    ids=["r_package", "paper"],
)
def test_fbp_glc_x_10_rasters_ros(raster_dir, input_csv, rtol):
    inputs = load_raster_inputs(raster_dir, input_csv)
    expected = _read_raster(raster_dir, "ros")
    ros, _, _, _, _, _, _ = calculate_primary_output(inputs)
    np.testing.assert_allclose(ros, expected, rtol=rtol, err_msg="ROS")


@pytest.mark.parametrize(
    "raster_dir,input_csv,rtol",
    [
        (RASTER_DIR, "cffdrs_r_test_fbp_inputs.csv", 1e-3),
        (PAPER_RASTER_DIR, "glc_x_10_paper_inputs.csv", 1e-2),
    ],
    ids=["r_package", "paper"],
)
def test_fbp_glc_x_10_rasters_hfi(raster_dir, input_csv, rtol):
    inputs = load_raster_inputs(raster_dir, input_csv)
    expected = _read_raster(raster_dir, "hfi")
    _, hfi, _, _, _, _, _ = calculate_primary_output(inputs)
    np.testing.assert_allclose(hfi, expected, rtol=rtol, err_msg="HFI")


@pytest.mark.parametrize(
    "raster_dir,input_csv,atol",
    [
        (RASTER_DIR, "cffdrs_r_test_fbp_inputs.csv", 1e-3),
        (PAPER_RASTER_DIR, "glc_x_10_paper_inputs.csv", 3e-3),
    ],
    ids=["r_package", "paper"],
)
def test_fbp_glc_x_10_rasters_cfb(raster_dir, input_csv, atol):
    inputs = load_raster_inputs(raster_dir, input_csv)
    expected = _read_raster(raster_dir, "cfb")
    _, _, cfb, _, _, _, _ = calculate_primary_output(inputs)
    np.testing.assert_allclose(cfb, expected, atol=atol, err_msg="CFB")


@pytest.mark.parametrize(
    "raster_dir,input_csv",
    [
        (RASTER_DIR, "cffdrs_r_test_fbp_inputs.csv"),
        (PAPER_RASTER_DIR, "glc_x_10_paper_inputs.csv"),
    ],
    ids=["r_package", "paper"],
)
def test_fbp_glc_x_10_rasters_sfc(raster_dir, input_csv):
    inputs = load_raster_inputs(raster_dir, input_csv)
    expected = _read_raster(raster_dir, "sfc")
    _, _, _, sfc, _, _, _ = calculate_primary_output(inputs)
    np.testing.assert_allclose(sfc, expected, rtol=1e-3, err_msg="SFC")


@pytest.mark.parametrize(
    "raster_dir,input_csv",
    [
        (RASTER_DIR, "cffdrs_r_test_fbp_inputs.csv"),
        (PAPER_RASTER_DIR, "glc_x_10_paper_inputs.csv"),
    ],
    ids=["r_package", "paper"],
)
def test_fbp_glc_x_10_rasters_tfc(raster_dir, input_csv):
    inputs = load_raster_inputs(raster_dir, input_csv)
    expected = _read_raster(raster_dir, "tfc")
    _, _, _, _, tfc, _, _ = calculate_primary_output(inputs)
    np.testing.assert_allclose(tfc, expected, rtol=1e-3, err_msg="TFC")


@pytest.mark.parametrize(
    "raster_dir,input_csv",
    [
        (RASTER_DIR, "cffdrs_r_test_fbp_inputs.csv"),
        (PAPER_RASTER_DIR, "glc_x_10_paper_inputs.csv"),
    ],
    ids=["r_package", "paper"],
)
def test_fbp_glc_x_10_rasters_raz(raster_dir, input_csv):
    inputs = load_raster_inputs(raster_dir, input_csv)
    expected = _read_raster(raster_dir, "raz")
    _, _, _, _, _, raz, _ = calculate_primary_output(inputs)
    # _fire_behaviour_prediction wraps the angle with an exact `raz_deg == 360 -> 0` check. Float32
    # raster storage rounds just enough that one case can land on 360.00001 instead of 0 - the same
    # angle, but not an exact match - so compare the circular (mod-360) distance instead.
    circular_diff = np.abs((raz - expected + 180) % 360 - 180)
    np.testing.assert_allclose(circular_diff, np.zeros_like(circular_diff), atol=0.1, err_msg="RAZ")


@pytest.mark.parametrize(
    "raster_dir,input_csv,output_csv,id_input_col,id_output_col",
    [
        (
            RASTER_DIR,
            "cffdrs_r_test_fbp_inputs.csv",
            "cffdrs_r_test_fbp_primary_outputs.csv",
            "id",
            "ID",
        ),
        (
            PAPER_RASTER_DIR,
            "glc_x_10_paper_inputs.csv",
            "glc_x_10_paper_primary_outputs.csv",
            "TestCase",
            "TestCase",
        ),
    ],
    ids=["r_package", "paper"],
)
def test_fbp_glc_x_10_rasters_fire_type(
    raster_dir, input_csv, output_csv, id_input_col, id_output_col
):
    inputs = load_raster_inputs(raster_dir, input_csv)
    _, _, cfb, _, _, _, fire_type = calculate_primary_output(inputs)
    # Rasters are pixel-ordered by input row order, so look up FD the same way, by id, rather
    # than assuming the outputs CSV happens to already be in that same order.
    ids = [row[id_input_col] for row in load_rows(input_csv)]
    output_by_id = {row[id_output_col]: row for row in load_rows(output_csv)}
    expected_fire_type = [FIRE_TYPE_BY_FD_CODE[output_by_id[i]["FD"]] for i in ids]
    assert list(fire_type) == expected_fire_type
