name: Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Deploy to Dev & ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - name: Variables
        shell: bash
        run: |
          echo -e "\n\n--- Environment Variables ---\n"
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"

          echo -e "\n\n--- Workflow (Custom) Variables ---\n"
          echo "::set-env name=SUFFIX::pr-${{ github.event.number }}"
          echo "SUFFIX: pr-${{ github.event.number }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Builds
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.OC_TOOL_TOKEN_EDIT }}
          SCRIPT: GIT_BRANCH=${GITHUB_HEAD_REF} openshift/scripts/oc_build.sh ${SUFFIX} apply

      - name: Deploy
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.OC_DEV_TOKEN_EDIT }}
          SCRIPT: openshift/scripts/oc_deploy.sh ${SUFFIX} apply

      # f.y.i.: ZAP Scan must be able to log an issue or it will fail.
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://wps-web-pr-${{ github.event.number }}.pathfinder.gov.bc.ca'
          # Do not return failure on warnings - TODO: this has to be resolved!
          cmd_options: '-I'
