name: Static Analysis

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: SonarQube - (main)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
        with:
          # For sonar-scanner to work properly we can't use a shallow fetch.
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Test coverage
        run: npm run coverage:ci
      - name: Fix code coverage paths
        # Due to the way sonarscanner mounts thing when running in docker, we need to change the coverage file.
        working-directory: ./coverage
        run: |
          sed -i 's/\/home\/runner\/work\/wps-web\/wps-web\//\/github\/workspace\//g' lcov.info
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
