pex_binary(
    name="access_to_csv",
    entry_point="access_to_csv.py",
)

pex_binary(
    name="calculate_percentile_offline",
    entry_point="calculate_percentile_offline.py",
)

pex_binary(
    name="copy_db_from_pod_to_local",
    entry_point="copy_db_from_pod_to_local.py",
)

python_sources()
