apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps
    wps.bcgov/env-global: 'true'
    wps.bcgov/env-uv: 'true'
    wps.bcgov/env-postgres: 'true'
    wps.bcgov/env-redis: 'true'
    wps.bcgov/env-wfwx: 'true'
  name: fire-watch-weather-wps-__SUFFIX__
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: fire-watch-weather-wps-__SUFFIX__
    spec:
      template:
        spec:
          containers:
          - command:
            - uv
            - run
            - --no-sync
            - python
            - -m
            - app.jobs.fire_watch_calculations
            env:
            - name: PROJECT_NAMESPACE
              value: __NAMESPACE__
            - name: POSTGRES_DATABASE
              value: wps
            - name: WFWX_MAX_PAGE_SIZE
              value: ${WFWX_MAX_PAGE_SIZE}
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/wps-api-__SUFFIX__:__SUFFIX__
            imagePullPolicy: Always
            name: fire-watch-weather-wps-__SUFFIX__
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 0.5
                memory: 256Mi
          restartPolicy: OnFailure
  schedule: 4 * * * *
