apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps
    wps.bcgov/env-global: 'true'
    wps.bcgov/env-uv: 'true'
    wps.bcgov/env-postgres: 'true'
    wps.bcgov/env-redis: 'true'
    wps.bcgov/env-wfwx: 'true'
  name: grass-curing-wps-__SUFFIX__
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: grass-curing-wps-__SUFFIX__
    spec:
      template:
        spec:
          containers:
          - command:
            - uv
            - run
            - --package
            - wps-api
            - --no-sync
            - python
            - -m
            - app.jobs.grass_curing
            env: []
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/wps-api-__SUFFIX__:__SUFFIX__
            imagePullPolicy: Always
            name: grass-curing-wps-__SUFFIX__
            resources:
              limits:
                memory: 1024Mi
              requests:
                cpu: 500m
                memory: 512Mi
          restartPolicy: OnFailure
  schedule: 44 * * * *
