apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps
    wps.bcgov/env-aws: 'true'
  name: prune-hourlies-wps-__SUFFIX__
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: prune-hourlies-wps-__SUFFIX__
    spec:
      template:
        spec:
          containers:
          - command:
            - bash
            - prune_hourlies.sh
            env: []
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/hourlies-prune:prod
            imagePullPolicy: Always
            name: prune-hourlies-wps-__SUFFIX__
            resources:
              limits:
                memory: 1024Mi
              requests:
                cpu: 75m
                memory: 512Mi
          restartPolicy: OnFailure
  schedule: 0 2 * * *
