apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps
    app.wps/env-global: 'true'
    app.wps/env-uv: 'true'
    app.wps/env-postgres: 'true'
    app.wps/env-redis: 'true'
    app.wps/env-wfwx: 'true'
    app.wps/env-redis-dailies: 'true'
    app.wps/env-redis-cache-noaa: 'true'
    app.wps/env-data-retention: 'true'
  name: noaa-gfs-wps-__SUFFIX__
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: noaa-gfs-wps-__SUFFIX__
    spec:
      backoffLimit: 6
      template:
        spec:
          containers:
          - command:
            - uv
            - run
            - --no-sync
            - python
            - -m
            - weather_model_jobs.noaa
            - GFS
            env:
            - name: WFWX_MAX_PAGE_SIZE
              value: '1000'
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/wps-jobs-__SUFFIX__:__SUFFIX__
            imagePullPolicy: Always
            name: noaa-gfs-wps-__SUFFIX__
            resources:
              limits:
                memory: 1024Mi
              requests:
                cpu: 500m
                memory: 512Mi
          restartPolicy: OnFailure
  schedule: 24 */4 * * *
  successfulJobsHistoryLimit: 3
