apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps
    wps.bcgov/env-aws: 'true'
  name: partitioner-wps-__SUFFIX__
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: partitioner-wps-__SUFFIX__
    spec:
      template:
        spec:
          containers:
          - command:
            - bash
            - partition_and_archive.sh
            - wps
            env:
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: wps-crunchydb-16-__SUFFIX__-pguser-wps-crunchydb-16-__SUFFIX__
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: wps-crunchydb-16-__SUFFIX__-pguser-wps-crunchydb-16-__SUFFIX__
            - name: PG_HOSTNAME
              valueFrom:
                secretKeyRef:
                  key: pgbouncer-host
                  name: wps-crunchydb-16-__SUFFIX__-pguser-wps-crunchydb-16-__SUFFIX__
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  key: pgbouncer-port
                  name: wps-crunchydb-16-__SUFFIX__-pguser-wps-crunchydb-16-__SUFFIX__
            - name: PG_DATABASE
              value: wps
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/pgslice:prod
            imagePullPolicy: Always
            name: partitioner-wps-__SUFFIX__
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 256m
                memory: 128Mi
          restartPolicy: OnFailure
  schedule: 0 6 1 * *
