apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps
    wps.bcgov/env-global: 'true'
    wps.bcgov/env-uv: 'true'
    wps.bcgov/env-postgres: 'true'
    wps.bcgov/env-redis: 'true'
    wps.bcgov/env-wfwx: 'true'
    wps.bcgov/env-objectstore: 'true'
  name: sfms-forecast-wps-__SUFFIX__-545pm
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: sfms-forecast-wps-__SUFFIX__-545pm
    spec:
      template:
        spec:
          containers:
          - command:
            - uv
            - run
            - --package
            - wps-api
            - --no-sync
            - python
            - -m
            - app.jobs.sfms_daily_forecasts
            env: []
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/wps-api-__SUFFIX__:__SUFFIX__
            imagePullPolicy: Always
            name: sfms-forecast-wps-__SUFFIX__-545pm
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 1Gi
          restartPolicy: OnFailure
  schedule: 45 0 * * *
