apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps
    app.wps/env-global: 'true'
    app.wps/env-uv: 'true'
    app.wps/env-postgres: 'true'
    app.wps/env-objectstore: 'true'
  name: viirs-snow-wps-__SUFFIX__
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: viirs-snow-wps-__SUFFIX__
    spec:
      template:
        spec:
          containers:
          - command:
            - uv
            - run
            - --package
            - wps-api
            - --no-sync
            - python
            - -m
            - app.jobs.viirs_snow
            env:
            - name: EARTHDATA_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: env.earthdata-username
                  name: wps-global
            - name: EARTHDATA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: earthdata-password
                  name: wps-global
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/wps-api-__SUFFIX__:__SUFFIX__
            imagePullPolicy: Always
            name: viirs-snow-wps-__SUFFIX__
            resources:
              limits:
                memory: 2048Mi
              requests:
                cpu: 75m
                memory: 512Mi
          restartPolicy: OnFailure
  schedule: 39 * * * *
