apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps-api
    wps.bcgov/env-global: 'true'
    wps.bcgov/env-uv: 'true'
    wps.bcgov/env-postgres: 'true'
    wps.bcgov/env-redis: 'true'
    wps.bcgov/env-wfwx: 'true'
  name: wfwx-hourly-actuals-wps-__SUFFIX__
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: wfwx-hourly-actuals-wps-__SUFFIX__
    spec:
      template:
        spec:
          containers:
          - command:
            - uv
            - run
            - --package
            - wps-api
            - --no-sync
            - python
            - -m
            - app.jobs.hourly_actuals
            env:
            - name: WFWX_MAX_PAGE_SIZE
              value: ${WFWX_MAX_PAGE_SIZE}
            - name: POSTGRES_DATABASE
              value: wps
            - name: PROJECT_NAMESPACE
              value: __NAMESPACE__
            - name: REDIS_DAILIES_BY_STATION_CODE_CACHE_EXPIRY
              valueFrom:
                configMapKeyRef:
                  key: env.redis-dailies-by-station-code-expiry
                  name: wps-global
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/wps-api-__SUFFIX__:__SUFFIX__
            imagePullPolicy: Always
            name: wfwx-hourly-actuals-wps-__SUFFIX__
          restartPolicy: OnFailure
  schedule: 15 * * * *
