apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps-api
    cronjob: wfwx-noon-forecasts-wps-__SUFFIX__
    app.wps/env-global: 'true'
    app.wps/env-uv: 'true'
    app.wps/env-postgres: 'true'
    app.wps/env-redis: 'true'
    app.wps/env-wfwx: 'true'
    app.wps/env-redis-dailies: 'true'
  name: wfwx-noon-forecasts-wps-__SUFFIX__
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: wfwx-noon-forecasts-wps-__SUFFIX__
    spec:
      template:
        spec:
          containers:
          - command:
            - uv
            - run
            - --package
            - wps-api
            - --no-sync
            - python
            - -m
            - app.jobs.noon_forecasts
            env:
            - name: WFWX_MAX_PAGE_SIZE
              value: ${WFWX_MAX_PAGE_SIZE}
            image: image-registry.openshift-image-registry.svc:5000/e1e498-tools/wps-api-__SUFFIX__:__SUFFIX__
            imagePullPolicy: Always
            name: wfwx-noon-forecasts-wps-__SUFFIX__
          restartPolicy: OnFailure
  schedule: 30 * * * *
