apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: wps-__SUFFIX__
    app.kubernetes.io/part-of: wps
    app.wps/env-uv: 'true'
    app.wps/env-postgres: 'true'
    app.wps/env-wx-objectstore: 'true'
    app.wps/env-wx-cartopy: 'true'
  name: wx-4panel-charts-rdps-wps-__SUFFIX__
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: wps-__SUFFIX__
        cronjob: wx-4panel-charts-rdps-wps-__SUFFIX__
    spec:
      template:
        spec:
          containers:
          - command:
            - uv
            - run
            - --package
            - wps-weather
            - --no-sync
            - python
            - -m
            - wps_weather.wx_4panel_charts.wx_4panel_charts
            - --end_hour
            - '84'
            - --step
            - '3'
            - --model
            - RDPS
            env: []
            image: ghcr.io/bcgov/wps/wps-weather:prod
            imagePullPolicy: Always
            name: wx-4panel-charts-rdps-wps-__SUFFIX__
            resources:
              limits:
                memory: 4096Mi
              requests:
                cpu: 75m
                memory: 512Mi
          restartPolicy: OnFailure
  schedule: 9 * * * *
