"""The national FBP fuel lookup table that temporal fuel grid values refer to.

Temporal fuel grids store national lookup grid values, and primary FBP reads each value's CFFDRS
fuel type from this table. The table is append-only: add rows for new grid values, but never
change what an existing grid value means, since every stored temporal fuel grid is read with
the current table. A copy is uploaded manually for the frontend to label and colour fuel grids
(see ``docs/architecture/fbp-todo.md``).
"""

from wps_shared.schemas.sfms import FuelCode, FuelCodesLookup

from wps_sfms.fbp_fuel_types import CFFDRSFuelTypes

NATIONAL_FUEL_CODES = FuelCodesLookup(
    fuel_codes=[
        FuelCode(
            grid_value=1,
            export_value=1,
            descriptive_name="Spruce-Lichen Woodland",
            fuel_type="C-1",
            red=209,
            green=255,
            blue=115,
            hue=57,
            saturation=255,
            lightness=185,
        ),
        FuelCode(
            grid_value=2,
            export_value=2,
            descriptive_name="Boreal Spruce",
            fuel_type="C-2",
            red=34,
            green=102,
            blue=51,
            hue=95,
            saturation=128,
            lightness=68,
        ),
        FuelCode(
            grid_value=3,
            export_value=3,
            descriptive_name="Mature Jack or Lodgepole Pine",
            fuel_type="C-3",
            red=131,
            green=199,
            blue=149,
            hue=96,
            saturation=96,
            lightness=165,
        ),
        FuelCode(
            grid_value=4,
            export_value=4,
            descriptive_name="Immature Jack or Lodgepole Pine",
            fuel_type="C-4",
            red=112,
            green=168,
            blue=0,
            hue=57,
            saturation=255,
            lightness=84,
        ),
        FuelCode(
            grid_value=5,
            export_value=5,
            descriptive_name="Red and White Pine",
            fuel_type="C-5",
            red=223,
            green=184,
            blue=230,
            hue=206,
            saturation=122,
            lightness=207,
        ),
        FuelCode(
            grid_value=6,
            export_value=6,
            descriptive_name="Conifer Plantation",
            fuel_type="C-6",
            red=172,
            green=102,
            blue=237,
            hue=192,
            saturation=201,
            lightness=170,
        ),
        FuelCode(
            grid_value=7,
            export_value=7,
            descriptive_name="Ponderosa Pine - Douglas-Fir",
            fuel_type="C-7",
            red=112,
            green=12,
            blue=242,
            hue=188,
            saturation=231,
            lightness=127,
        ),
        FuelCode(
            grid_value=11,
            export_value=11,
            descriptive_name="Leafless Aspen",
            fuel_type="D-1",
            red=196,
            green=189,
            blue=151,
            hue=35,
            saturation=70,
            lightness=174,
        ),
        FuelCode(
            grid_value=12,
            export_value=12,
            descriptive_name="Green Aspen (with BUI Thresholding)",
            fuel_type="D-2",
            red=137,
            green=112,
            blue=68,
            hue=27,
            saturation=86,
            lightness=103,
        ),
        FuelCode(
            grid_value=21,
            export_value=21,
            descriptive_name="Jack or Lodgepole Pine Slash",
            fuel_type="S-1",
            red=251,
            green=190,
            blue=185,
            hue=3,
            saturation=227,
            lightness=218,
        ),
        FuelCode(
            grid_value=22,
            export_value=22,
            descriptive_name="White Spruce - Balsam Slash",
            fuel_type="S-2",
            red=247,
            green=104,
            blue=161,
            hue=238,
            saturation=229,
            lightness=176,
        ),
        FuelCode(
            grid_value=23,
            export_value=23,
            descriptive_name="Coastal Cedar - Hemlock - Douglas-Fir Slash",
            fuel_type="S-3",
            red=174,
            green=1,
            blue=126,
            hue=225,
            saturation=252,
            lightness=88,
        ),
        FuelCode(
            grid_value=31,
            export_value=31,
            descriptive_name="Matted Grass",
            fuel_type="O-1a",
            red=255,
            green=255,
            blue=190,
            hue=42,
            saturation=255,
            lightness=223,
        ),
        FuelCode(
            grid_value=32,
            export_value=32,
            descriptive_name="Standing Grass",
            fuel_type="O-1b",
            red=230,
            green=230,
            blue=0,
            hue=42,
            saturation=255,
            lightness=115,
        ),
        FuelCode(
            grid_value=40,
            export_value=40,
            descriptive_name="Boreal Mixedwood - Leafless",
            fuel_type="M-1",
            red=255,
            green=211,
            blue=127,
            hue=28,
            saturation=255,
            lightness=191,
        ),
        FuelCode(
            grid_value=50,
            export_value=50,
            descriptive_name="Boreal Mixedwood - Green",
            fuel_type="M-2",
            red=255,
            green=170,
            blue=0,
            hue=28,
            saturation=255,
            lightness=128,
        ),
        FuelCode(
            grid_value=70,
            export_value=70,
            descriptive_name="Dead Balsam Fir Mixedwood - Leafless",
            fuel_type="M-3",
            red=99,
            green=0,
            blue=0,
            hue=0,
            saturation=255,
            lightness=50,
        ),
        FuelCode(
            grid_value=80,
            export_value=80,
            descriptive_name="Dead Balsam Fir Mixedwood - Green",
            fuel_type="M-4",
            red=170,
            green=0,
            blue=0,
            hue=0,
            saturation=255,
            lightness=85,
        ),
        FuelCode(
            grid_value=101,
            export_value=101,
            descriptive_name="Non-fuel",
            fuel_type="Non-fuel",
            red=130,
            green=130,
            blue=130,
            hue=170,
            saturation=0,
            lightness=130,
        ),
        FuelCode(
            grid_value=102,
            export_value=102,
            descriptive_name="Water",
            fuel_type="Non-fuel",
            red=115,
            green=223,
            blue=255,
            hue=138,
            saturation=255,
            lightness=185,
        ),
    ]
)

NATIONAL_FUEL_TYPES = CFFDRSFuelTypes.from_lookup(NATIONAL_FUEL_CODES)
