apiVersion: v1
kind: Template
metadata: {}
parameters:
  - name: SUFFIX
  - name: TAG
    value: latest
    description: The output image tag being generated
  - name: GIT_URL
    value: https://github.com/bcgov/wps-api.git
  - name: GIT_REF
    value: prototype
labels:
  app.kubernetes.io/part-of: 'wps-api'
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      app: wps-api
    name: wps-api
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      app: wps-api
    name: wps-api${SUFFIX}
  spec:
    nodeSelector: null
    runPolicy: SerialLatestOnly
    completionDeadlineSeconds: 600 # 10 minutes
    output:
      to:
        kind: ImageStreamTag
        name: wps-api:${TAG}
    postCommit: {}
    resources:
      limits:
        cpu: '2'
        memory: 5Gi
      requests:
        cpu: '1'
        memory: 1Gi
    source:
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
      type: Git
      contextDir: 
    strategy:
      dockerStrategy:
        env:
          #- name: UPGRADE_PIP_TO_LATEST
            #value: 'true'
          - name: ENABLE_PIPENV
            value: 'true'
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
