apiVersion: v1
kind: Template
metadata: {}
parameters:
  - name: NAME
    value: wps-web
  - name: SUFFIX
  - name: TAG
    value: latest
    description: The output image tag beig deployed
  - name: DOCKER_REGISTRY
    required: true
objects:
- apiVersion: v1
  data:
    Caddyfile: |
      0.0.0.0:8080
      root /var/www/html
      log stdout
      errors stdout    
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: caddyfile-${NAME}${SUFFIX}
    labels:
      app: ${NAME}${SUFFIX}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      app: ${NAME}${SUFFIX}
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}${SUFFIX}
    template:
      metadata:
        labels:
          app: ${NAME}${SUFFIX}
      spec:
        automountServiceAccountToken: false
        containers:
          #- image: docker-registry.default.svc:5000/auzhsi-tools/wps-web:latest
          - image: ${DOCKER_REGISTRY}/${NAME}:${TAG}
            imagePullPolicy: Always
            name: wps-web
            args:
            - /tmp/scripts/run
            ports:
              - containerPort: 8080
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
              - name: caddy-${NAME}${SUFFIX}
                mountPath: /etc/Caddyfile
                readOnly: true
                subPath: Caddyfile
        volumes:
          - name: caddy-${NAME}${SUFFIX}
            configMap:
              defaultMode: 420
              name: caddyfile-${NAME}${SUFFIX}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
  spec:
    selector:
      app: ${NAME}${SUFFIX}
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 80
        targetPort: 8080
      - name: 8443-tcp
        protocol: TCP
        port: 443
        targetPort: 8443
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    labels:
      app: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
  spec:
    rules:
      - host: ${NAME}${SUFFIX}-auzhsi.pathfinder.gov.bc.ca
        http:
          paths:
            - backend:
                serviceName: ${NAME}${SUFFIX}
                servicePort: 80
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}-secure
  spec:
    host: ${NAME}${SUFFIX}-secure-auzhsi.pathfinder.gov.bc.ca
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${NAME}${SUFFIX}
    tls:
      termination: edge