pipeline {
    agent none
    environment {
        // Pipeline-wide vars
        ver = "0.0.1"
        projTools = "e1e498-tools"
        projDev = "e1e498-dev"
        projProd = "e1e498-prod"
        suffix = "pr-${env.CHANGE_ID}"
    }
    options {
        disableResume()
    }
    stages {
        stage('Startup') {
            agent { label 'build' }
            steps {
                echo "Aborting all running jobs ..."
                script {
                    abortAllPreviousBuildInProgress(currentBuild)
                }
            }
        }
        stage('Promote (PROD)') {
            agent { label 'deploy' }
            input {
                message "Should we promote this deployment to PRODUCTION?"
                ok "Yes!"
            }
            steps {
                script {
                    sh "./openshift/scripts/oc_promote.sh ${suffix} apply"
                    sh "./openshift/scripts/oc_promote_ubuntu.sh ${suffix} apply"
                }
            }
        }
        stage('Deploy (PROD)') {
            agent { label 'deploy' }
            steps {
                script {
                    // Update database template:
                    // The PVC_SIZE size does NOT match the currently provisioned size.
                    // The size of the storage is in fact 30Gi ; The volume claim for a
                    // stateful set cannot be altered. The stateful set needs to be re-created
                    // and data needs to be restored from backup.
                    sh "CPU_REQUEST=100m CPU_LIMIT=2000m MEMORY_REQUEST=8Gi MEMORY_LIMIT=16Gi PVC_SIZE=45Gi PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_db.sh prod apply"
                    // Deploy API
                    sh "CPU_REQUEST=50m CPU_LIMIT=500m MEMORY_REQUEST=2Gi MEMORY_LIMIT=2Gi REPLICAS=3 PROJ_TARGET=${projProd} VANITY_DOMAIN=psu.nrs.gov.bc.ca SECOND_LEVEL_DOMAIN=apps.silver.devops.gov.bc.ca ./openshift/scripts/oc_deploy.sh prod apply"
                    // Env Canada Subscriber
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_ec_gdps_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_ec_hrdps_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_ec_rdps_cronjob.sh prod apply"
                    // C-Haines
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_c_haines_cronjob.sh prod apply"
                    // BC FireWeather cronjobs
                    // Run forecast at 8h30 PDT and 16h30 PDT (so before and after noon)
                    sh "PROJ_TARGET=${projProd} SCHEDULE=\"30 15,23 * * *\" ./openshift/scripts/oc_provision_bcfw_p1_forecasts_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} SCHEDULE=\"15 * * * *\" ./openshift/scripts/oc_provision_bcfw_p1_hourly_actuals_cronjob.sh prod apply"
                    // Configure backups
                    sh "PROJ_TARGET=${projProd} BACKUP_VOLUME_SIZE=50Gi CPU_REQUEST=1000m CPU_LIMIT=2000m ./openshift/scripts/oc_provision_backup_postgres.sh prod apply"
                    sh "PROJ_TARGET=${projProd} CPU_REQUEST=1000m CPU_LIMIT=2000m ./openshift/scripts/oc_provision_backup_postgres_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} BACKUP_VOLUME_SIZE=3Gi ./openshift/scripts/oc_provision_backup_mariadb.sh prod apply"
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_backup_mariadb_cronjob.sh prod apply"
                    // Configure 
                    sh "PROJ_TARGET=${projProd} CERTBOT_STAGING=false DRYRUN=false ./openshift/scripts/oc_provision_certbot_cronjob.sh prod apply"
                }
            }
        }
    }
}