pipeline {
    agent none
    environment {
        // Pipeline-wide vars
        ver = "0.0.1"
        projTools = "e1e498-tools"
        projDev = "e1e498-dev"
        projProd = "e1e498-prod"
        suffix = "pr-${env.CHANGE_ID}"
    }
    options {
        disableResume()
    }
    stages {
        stage('Startup') {
            agent { label 'build' }
            steps {
                echo "Aborting all running jobs ..."
                script {
                    abortAllPreviousBuildInProgress(currentBuild)
                }
            }
        }
        stage('Promote (PROD)') {
            agent { label 'deploy' }
            input {
                message "Should we promote this deployment to PRODUCTION?"
                ok "Yes!"
            }
            steps {
                script {
                    sh "./openshift/scripts/oc_promote.sh ${suffix} apply"
                }
            }
        }
        stage('Deploy (PROD)') {
            agent { label 'deploy' }
            steps {
                script {
                    // Update database template:
                    // The PVC_SIZE size does NOT match the currently provisioned size.
                    // The size of the storage is in fact 30Gi ; The volume claim for a
                    // stateful set cannot be altered. The stateful set needs to be re-created
                    // and data needs to be restored from backup.
                    sh "CPU_REQUEST=100m CPU_LIMIT=2000m MEMORY_REQUEST=4Gi MEMORY_LIMIT=8Gi PVC_SIZE=25Gi PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_db.sh prod apply"
                    // Deploy API
                    sh "CPU_REQUEST=500m CPU_LIMIT=500m MEMORY_REQUEST=2Gi MEMORY_LIMIT=2Gi REPLICAS=3 PROJ_TARGET=${projProd} POSTGRES_USER=wps POSTGRES_DATABASE=wps SECOND_LEVEL_DOMAIN=apps.silver.devops.gov.bc.ca POSTGRES_WRITE_HOST=patroni-wps-prod-leader POSTGRES_READ_HOST=patroni-wps-prod-replica ./openshift/scripts/oc_deploy.sh prod apply"
                    // Env Canada Subscriber
                    sh "PROJ_TARGET=${projProd} POSTGRES_WRITE_HOST=patroni-wps-prod-leader POSTGRES_READ_HOST=patroni-wps-prod-replica POSTGRES_DATABASE=wps POSTGRES_USER=wps ./openshift/scripts/oc_provision_ec_gdps_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} POSTGRES_WRITE_HOST=patroni-wps-prod-leader POSTGRES_READ_HOST=patroni-wps-prod-replica POSTGRES_DATABASE=wps POSTGRES_USER=wps ./openshift/scripts/oc_provision_ec_hrdps_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} POSTGRES_WRITE_HOST=patroni-wps-prod-leader POSTGRES_READ_HOST=patroni-wps-prod-replica POSTGRES_DATABASE=wps POSTGRES_USER=wps ./openshift/scripts/oc_provision_ec_rdps_cronjob.sh prod apply"
                    // BC FireWeather cronjobs
                    // TODO: Change cron to: 30 8,16 * * * (was set 2 minutes early to avoid clash with pathfinder instance)
                    sh "PROJ_TARGET=${projProd} POSTGRES_WRITE_HOST=patroni-wps-prod-leader POSTGRES_READ_HOST=patroni-wps-prod-replica POSTGRES_DATABASE=wps POSTGRES_USER=wps SCHEDULE=\"28 8,16 * * *\" ./openshift/scripts/oc_provision_bcfw_p1_forecasts_cronjob.sh prod apply"
                    // TODO: Change cron to: 15 * * * * (was set 2 minutes early to avoid clash with pathfinder instance)
                    sh "PROJ_TARGET=${projProd} POSTGRES_WRITE_HOST=patroni-wps-prod-leader POSTGRES_READ_HOST=patroni-wps-prod-replica POSTGRES_DATABASE=wps POSTGRES_USER=wps SCHEDULE=\"13 * * * *\" ./openshift/scripts/oc_provision_bcfw_p1_hourly_actuals_cronjob.sh prod apply"
                    // Configure backups
                    sh "PROJ_TARGET=${projProd} BACKUP_VOLUME_SIZE=15Gi ./openshift/scripts/oc_provision_backup_postgres.sh prod apply"
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_backup_postgres_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} BACKUP_VOLUME_SIZE=4Gi ./openshift/scripts/oc_provision_backup_mariadb.sh prod apply"
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_backup_mariadb_cronjob.sh prod apply"
                }
            }
        }
    }
}