pipeline {
    agent none
    environment {
        // Pipeline-wide vars
        ver = "0.0.1"
        projTools = "auzhsi-tools"
        projDev = "auzhsi-dev"
        projProd = "auzhsi-prod"
        suffix = "pr-${env.CHANGE_ID}"
    }
    options {
        disableResume()
    }
    stages {
        stage('Startup') {
            agent { label 'build' }
            steps {
                echo "Aborting all running jobs ..."
                script {
                    abortAllPreviousBuildInProgress(currentBuild)
                }
            }
        }
        stage('Promote (PROD)') {
            agent { label 'deploy' }
            input {
                message "Should we promote this deployment to PRODUCTION?"
                ok "Yes!"
            }
            steps {
                script {
                    sh "./openshift/scripts/oc_promote.sh ${suffix} apply"
                }
            }
        }
        stage('Deploy (PROD)') {
            agent { label 'deploy' }
            steps {
                script {
                    // Update database template:
                    sh "CPU_REQUEST=100m CPU_LIMIT=2000m MEMORY_REQUEST=512Mi MEMORY_LIMIT=2Gi POD_MANAGEMENT_POLICY=OrderedReady PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_db.sh prod apply"
                    // Deploy API
                    sh "CPU_REQUEST=500m CPU_LIMIT=500m MEMORY_REQUEST=2Gi MEMORY_LIMIT=2Gi REPLICAS=3 PROJ_TARGET=${projProd} ./openshift/scripts/oc_deploy.sh prod apply"
                    // Env Canada Subscriber
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_ec_gdps_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_ec_hrdps_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_bcfw_p1_forecasts_cronjob.sh prod apply"
                    sh "PROJ_TARGET=${projProd} ./openshift/scripts/oc_provision_bcfw_p1_hourly_actuals_cronjob.sh prod apply"
                }
            }
        }
    }
}