apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    openshift.io/display-name: "wps-web" 
    description: "Wildfire Predictive Services - Fire Weather Index"  
    openshift.io/long-description: "Wildfire Predictive Services - Fire Weather Index" 
    tags: "wps,wps-web" 
    iconClass: icon-js 
    openshift.io/provider-display-name: "Government of British Columbia" 
    openshift.io/documentation-url: "https://github.com/bcgov/wps-web" 
    openshift.io/support-url: "https://github.com/bcgov/wps-web"
labels:
  app.kubernetes.io/part-of: "${NAME}"
parameters:
  - name: NAME
    description: Module name
    value: wps-web
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-###
    required: true
  - name: DOCKER_REGISTRY
    value: docker-registry.default.svc:5000
  - name: PROJECT_DEPLOY
    value: auzhsi-dev
  - name: PROJECT_TOOLS
    value: auzhsi-tools
  - name: CPU_REQUEST
    description: Requested CPU
    value: 500m
  - name: CPU_LIMIT
    description: CPU upper limit
    value: 500m
  - name: MEMORY_REQUEST
    description: Requested memory
    value: 1Gi
  - name: MEMORY_LIMIT
    description: Memory upper limit
    value: 1Gi
objects:
  - apiVersion: v1
    data:
      Caddyfile: |
        0.0.0.0:8080
        root /var/www/html
        log stdout
        errors stdout
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: caddyfile-${NAME}-${SUFFIX}
      labels:
        app: ${NAME}-${SUFFIX}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${NAME}-${SUFFIX}
      template:
        metadata:
          labels:
            app: ${NAME}-${SUFFIX}
        spec:
          automountServiceAccountToken: false
          containers:
            - image: ${DOCKER_REGISTRY}/${PROJECT_TOOLS}/${NAME}-${SUFFIX}-s2i:latest
              imagePullPolicy: Always
              name: ${NAME}
              args:
                - /tmp/scripts/run
              ports:
                - containerPort: 8080
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              volumeMounts:
                - name: caddy-${NAME}-${SUFFIX}
                  mountPath: /etc/Caddyfile
                  readOnly: true
                  subPath: Caddyfile
          volumes:
            - name: caddy-${NAME}-${SUFFIX}
              configMap:
                defaultMode: 420
                name: caddyfile-${NAME}-${SUFFIX}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      selector:
        app: ${NAME}-${SUFFIX}
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      host: ${NAME}-${SUFFIX}.pathfinder.gov.bc.ca
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}-${SUFFIX}
      tls:
        termination: edge
