apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ubuntu-base
labels:
  app: ${NAME}${SUFFIX}
  phase: build
  app.kubernetes.io/name: uvicorn-gunicorn-fastapi
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "20.04"
parameters:
  - name: NAME
    value: ubuntu-base
  - name: SUFFIX
  - name: VERSION
    description: Output version
    value: "20.04"
  - name: GIT_URL
    value: https://github.com/bcgov/wps.git
  - name: GIT_BRANCH
    value: main
objects:
  #ImageStream is create if it doesn't already exist
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ubuntu-base
        common: "true"
      name: ubuntu-base
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        app: ubuntu-base
      name: ubuntu-base
    spec:
      completionDeadlineSeconds: 2400 # 40 minutes (this build can take a lot of time!)
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}${SUFFIX}:${VERSION}
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: origin/${GIT_BRANCH}
        contextDir: openshift/ubuntu-base/docker
      strategy:
        type: Docker
