version: "3.8"
services:
  db:
    image: postgis/postgis
    hostname: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tileserv
      - POSTGRES_PASSWORD=tileserv
      - POSTGRES_DB=tileserv
      - POSTGRES_HOST_AUTH_METHOD="trust"
    networks:
      - worker_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tileserv" ]
      interval: 5s
      timeout: 5s
      retries: 5
  pg_tileserv:
    image: pramsey/pg_tileserv
    ports:
      - 7800:7800
    environment:
      - DATABASE_URL=postgres://tileserv:tileserv@db:5432/tileserv
    networks:
      - worker_network
    depends_on:
      db:
        condition: service_healthy
networks:
  worker_network:
    driver: bridge
