import { BurnStatusEnum, FireWatchBurnForecast, FuelTypeEnum, InPrescriptionEnum } from "@/features/fireWatch/interfaces";
import { DateTime } from "luxon";

export const data: FireWatchBurnForecast[] = [
  {
    fireWatch: {
      id: 38,
      geometry: [1069170, 511739],
      burnWindowEnd: DateTime.fromISO('2025-10-01'),
      burnWindowStart: DateTime.fromISO('2025-05-01'),
      contactEmail: ['darren.boss@gov.bc.ca'],
      fireCentre: { id: 14, name: 'test' },
      station: { code: 1093, name: 'test' },
      status: BurnStatusEnum.ACTIVE,
      title: 'Cumberland',
      fuelType: FuelTypeEnum.C2,
      tempMin: 5,
      tempPreferred: 15,
      tempMax: 20,
      rhMin: 20,
      rhPreferred: 40,
      rhMax: 50,
      windSpeedMin: 5,
      windSpeedPreferred: 15,
      windSpeedMax: 15,
      ffmcMin: 86,
      ffmcPreferred: 90,
      ffmcMax: 92,
      dmcMin: 10,
      dmcPreferred: 25,
      dmcMax: 40,
      dcMin: 15,
      dcPreferred: 150,
      dcMax: 400,
      isiMin: 5,
      isiPreferred: 9,
      isiMax: 14,
      buiMin: 5,
      buiPreferred: 20,
      buiMax: 60,
      hfiMin: 1500,
      hfiPreferred: 2500,
      hfiMax: 3500
    },
    burnForecasts: [
      {
        id: 1,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-13'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.YES
      },
      {
        id: 2,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-14'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.YES
      },
      {
        id: 3,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-15'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.HFI
      }
    ]
  },
  {
    fireWatch: {
      id: 39,
      geometry: [1069170, 511739],
      burnWindowEnd: DateTime.fromISO('2025-10-01'),
      burnWindowStart: DateTime.fromISO('2025-05-01'),
      contactEmail: ['darren.boss@gov.bc.ca'],
      fireCentre: { id: 14, name: 'test' },
      station: { code: 1093, name: 'test' },
      status: BurnStatusEnum.ACTIVE,
      title: 'Comox',
      fuelType: FuelTypeEnum.C3,
      tempMin: 5,
      tempPreferred: 15,
      tempMax: 20,
      rhMin: 20,
      rhPreferred: 40,
      rhMax: 50,
      windSpeedMin: 5,
      windSpeedPreferred: 15,
      windSpeedMax: 15,
      ffmcMin: 86,
      ffmcPreferred: 90,
      ffmcMax: 92,
      dmcMin: 10,
      dmcPreferred: 25,
      dmcMax: 40,
      dcMin: 15,
      dcPreferred: 150,
      dcMax: 400,
      isiMin: 5,
      isiPreferred: 9,
      isiMax: 14,
      buiMin: 5,
      buiPreferred: 20,
      buiMax: 60,
      hfiMin: 1500,
      hfiPreferred: 2500,
      hfiMax: 3500
    },
    burnForecasts: [
      {
        id: 1,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-13'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.NO
      },
      {
        id: 2,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-14'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.HFI
      },
      {
        id: 3,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-15'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.NO
      }
    ]
  },
  {
    fireWatch: {
      id: 40,
      geometry: [1069170, 511739],
      burnWindowEnd: DateTime.fromISO('2025-10-01'),
      burnWindowStart: DateTime.fromISO('2025-05-01'),
      contactEmail: ['darren.boss@gov.bc.ca'],
      fireCentre: { id: 14, name: 'test' },
      station: { code: 1093, name: 'test' },
      status: BurnStatusEnum.ACTIVE,
      title: 'Courtenay',
      fuelType: FuelTypeEnum.C2,
      tempMin: 5,
      tempPreferred: 15,
      tempMax: 20,
      rhMin: 20,
      rhPreferred: 40,
      rhMax: 50,
      windSpeedMin: 5,
      windSpeedPreferred: 15,
      windSpeedMax: 15,
      ffmcMin: 86,
      ffmcPreferred: 90,
      ffmcMax: 92,
      dmcMin: 10,
      dmcPreferred: 25,
      dmcMax: 40,
      dcMin: 15,
      dcPreferred: 150,
      dcMax: 400,
      isiMin: 5,
      isiPreferred: 9,
      isiMax: 14,
      buiMin: 5,
      buiPreferred: 20,
      buiMax: 60,
      hfiMin: 1500,
      hfiPreferred: 2500,
      hfiMax: 3500
    },
    burnForecasts: [
      {
        id: 1,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-13'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.NO
      },
      {
        id: 2,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-14'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.NO
      },
      {
        id: 3,
        fireWatchId: 38,
        date: DateTime.fromISO('2025-05-15'),
        temp: 12,
        rh: 20,
        windSpeed: 6,
        ffmc: 21,
        dmc: 16,
        dc: 12,
        isi: 15,
        bui: 23,
        hfi: 21,
        inPrescription: InPrescriptionEnum.NO
      }
    ]
  }
]
