name: ASA Go

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  web_tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20.x]
    name: ASA Go Web Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ionic CLI
        working-directory: ./mobile/asa-go
        run: npm install -g @ionic/cli
      - uses: actions/cache@v4
        id: asa-go-cache
        with:
          path: |
            mobile/asa-go/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        working-directory: ./mobile/asa-go
        if: steps.asa-go-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Test with Coverage
        working-directory: ./mobile/asa-go
        run: yarn run test:ci
      - name: Upload web test coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: web
          name: web-tests
          # we want to ensure code coverage is good, so we fail on error. (default is false)
          fail_ci_if_error: true

  swift_plugin_tests:
    runs-on: macos-latest
    name: Keycloak Swift Plugin Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: asa-go-keycloak-cache
        with:
          path: |
            mobile/keycloak/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install keycloak plugin dependencies
        working-directory: ./mobile/keycloak
        if: steps.asa-go-keycloak-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Setup iOS Simulator
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcrun simctl list runtimes | head -20
          xcrun simctl list devices | head -20
          # Try to create a simple simulator
          xcrun simctl create TestDevice "iPhone 16" || xcrun simctl create TestDevice "iPhone 15" || true
          xcrun simctl list devices | grep TestDevice || true
      - name: Test Keycloak Swift Plugin
        working-directory: ./mobile/keycloak
        run: xcodebuild test -scheme "Keycloak" -destination "generic/platform=iOS Simulator" -enableCodeCoverage YES build test
      - name: Upload Swift plugin test coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: swift
          name: swift-plugin-tests
          # we want to ensure code coverage is good, so we fail on error. (default is false)
          fail_ci_if_error: true
