name: ASA Go Screenshots

on:
  workflow_dispatch:
  push:
    branches:
      - task/asago-automated-screenshots

jobs:
  screenshots:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - uses: actions/cache@v5
        id: asa-go-keycloak-cache
        with:
          path: mobile/keycloak/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install keycloak plugin
        working-directory: ./mobile/keycloak
        if: steps.asa-go-keycloak-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build keycloak plugin
        working-directory: ./mobile/keycloak
        run: yarn build

      - uses: actions/cache@v5
        id: asa-go-cache
        with:
          path: mobile/asa-go/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: ./mobile/asa-go
        if: steps.asa-go-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Install Playwright browsers
        working-directory: ./mobile/asa-go
        run: yarn playwright install --with-deps chromium

      - name: Create environment settings
        working-directory: ./mobile/asa-go
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_PMTILES_BUCKET: ${{ secrets.VITE_PMTILES_BUCKET }}
          VITE_MUI_LICENSE_KEY: ${{ secrets.VITE_MUI_LICENSE_KEY }}
          VITE_BASEMAP_TILE_URL: ${{ secrets.VITE_BASEMAP_TILE_URL }}
          VITE_BASEMAP_STYLE_URL: ${{ secrets.VITE_BASEMAP_STYLE_URL }}
        run: |
          echo "VITE_MUI_LICENSE_KEY=${VITE_MUI_LICENSE_KEY}" >> .env.screenshot
          echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}" >> .env.screenshot
          echo "VITE_PMTILES_BUCKET=${VITE_PMTILES_BUCKET}" >> .env.screenshot
          echo "VITE_BASEMAP_TILE_URL=${VITE_BASEMAP_TILE_URL}" >> .env.screenshot
          echo "VITE_BASEMAP_STYLE_URL=${VITE_BASEMAP_STYLE_URL}" >> .env.screenshot

      - name: Build
        working-directory: ./mobile/asa-go
        run: yarn build:screenshot

      - name: Take screenshots
        working-directory: ./mobile/asa-go
        run: yarn screenshot

      - uses: actions/upload-artifact@v7
        with:
          name: ASA-Go-Screenshots
          path: mobile/asa-go/screenshots/
          retention-days: 30
          if-no-files-found: error
