name: ASA Go

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: macos-14
    strategy:
      matrix:
        node-version: [20.x]
    name: Build and test ASA Go
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ionic CLI
        working-directory: ./mobile/asa-go
        run: npm install -g @ionic/cli
      - name: Test
        working-directory: ./mobile/asa-go
        run: yarn install && yarn test

