name: ASA Go

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: macos-15
    strategy:
      matrix:
        node-version: [20.x]
    name: Build and test ASA Go
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ionic CLI
        working-directory: ./mobile/asa-go
        run: npm install -g @ionic/cli
      - uses: actions/cache@v4
        id: asa-go-cache
        with:
          path: |
            mobile/asa-go/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v4
        id: asa-go-keycloak-cache
        with:
          path: |
            mobile/keycloak/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install keycloak plugin
        working-directory: ./mobile/keycloak
        if: steps.asa-go-keycloak-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Install dependencies
        working-directory: ./mobile/asa-go
        if: steps.asa-go-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Test with Coverage
        working-directory: ./mobile/asa-go
        run: yarn run test:ci
      - name: Test Keycloak Swift Plugin
        working-directory: ./mobile/keycloak
        run: xcodebuild test -scheme "Keycloak -destination "platform=iOS Simulator,name=iPhone 16 Pro"
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          # we want to ensure code coverage is good, so we fail on error. (default is false)
          fail_ci_if_error: true
