name: Deploy WPS Weather

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/packages/wps-weather/**"

env:
  SUFFIX: pr-${{ github.event.number }}

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build and push WPS Weather image
        uses: bcgov/actions/builder-ghcr@4ad61a784f1c17765b03d8d6de9737c1d3f4c0f2 # v0.5.0
        with:
          package: wps-weather
          build_context: .
          build_file: backend/packages/wps-weather/Dockerfile
          tags: ${{ env.SUFFIX }}

  deployments:
    name: Deployments
    needs: [build-image]
    runs-on:
      group: Larger Runners - OpenShift Static-IP
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/oc-setup

      - uses: ./.github/actions/oc-login
        with:
          oc-server: ${{ secrets.OPENSHIFT_CLUSTER }}
          oc-token: ${{ secrets.OC4_DEV_TOKEN }}
          oc-namespace: e1e498-dev

      - name: Provision S3 Retention Cronjob
        shell: bash
        run: |
          bash openshift/scripts/oc_provision_s3_data_retention.sh ${SUFFIX} | oc -n e1e498-dev apply -f -

      - name: Deploy ECCC Consumer
        shell: bash
        run: |
          bash openshift/scripts/oc_provision_eccc_grib_consumer.sh ${SUFFIX} apply
