name: Deploy WPS Weather

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/packages/wps-weather/**"

env:
  SUFFIX: pr-${{ github.event.number }}

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push WPS Weather image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/packages/wps-weather/Dockerfile
          push: true
          tags: ghcr.io/bcgov/wps-weather:${{ env.SUFFIX }}

  deployments:
    name: Deployments
    needs: [build-image]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: ./.github/actions/oc-setup

      - uses: ./.github/actions/oc-login
        with:
          oc-server: ${{ secrets.OPENSHIFT_CLUSTER }}
          oc-token: ${{ secrets.OC4_DEV_TOKEN }}
          oc-namespace: e1e498-dev

      - name: Provision S3 Retention Cronjob
        shell: bash
        run: |
          bash openshift/scripts/oc_provision_s3_data_retention.sh ${SUFFIX} apply

      - name: Deploy ECCC Consumer
        shell: bash
        run: |
          bash openshift/scripts/oc_provision_eccc_grib_consumer.sh ${SUFFIX} apply
