name: Deploy WPS Weather

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/packages/wps-weather/**"

env:
  SUFFIX: pr-${{ github.event.number }}

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build and push WPS Weather image
        uses: bcgov/actions/builder-ghcr@0992e41cd11c5370b77f9e6066effe63efe9f8c9 # v0.4.0
        with:
          package: wps-weather
          build_context: .
          build_file: backend/packages/wps-weather/Dockerfile
          tags: ${{ env.SUFFIX }}

  deployments:
    name: Deployments
    needs: [build-image]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: ./.github/actions/oc-setup

      - uses: ./.github/actions/oc-login
        with:
          oc-server: ${{ secrets.OPENSHIFT_CLUSTER }}
          oc-token: ${{ secrets.OC4_DEV_TOKEN }}
          oc-namespace: e1e498-dev

      - name: Provision S3 Retention Cronjob
        shell: bash
        run: |
          bash openshift/scripts/oc_provision_s3_data_retention.sh ${SUFFIX} apply

      - name: Deploy ECCC Consumer
        shell: bash
        run: |
          bash openshift/scripts/oc_provision_eccc_grib_consumer.sh ${SUFFIX} apply
