name: deploy-command

on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    # Use this as an initial start point
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
