name: GDAL

on:
  pull_request:
    branches:
      - main
jobs:
  lint-api:
    name: GDAL install
    runs-on: ubuntu-24.04
    container: ghcr.io/osgeo/gdal:ubuntu-small-3.9.2
    strategy:
      matrix:
        python-version: [3.12.3]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install ubuntu pre-requisites (api)
        run: |
          apt-get update
          apt-get -y install libudunits2-dev r-base-dev libgdal-dev libproj-dev libgeos-dev libsqlite3-dev libtirpc-dev
          gdal-config --version
