name: Sprint issue metrics
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 21 * * 3"

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Get dates for last sprint
        shell: bash
        run: |
          # Determine if the current week is an "even" week (biweekly toggle)
          if [ $(( $(date +%V) % 2 )) -eq 1 ]; then
              # Calculate the first and last day of the 2-week period
              first_day=$(date -d "2 weeks ago" +%Y-%m-%d)
              last_day=$(date +%Y-%m-%d)
              # Set the date range for the 2-week period
              echo "$first_day..$last_day"
              echo "biweekly_period=$first_day..$last_day" >> "$GITHUB_ENV"
          else
              echo "Skipping run; off-week in biweekly schedule."
              echo "skip_run=true" >> "$GITHUB_ENV" 
          fi

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        if: ${{ env.skip_run != 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HIDE_LABEL_METRICS: "true"
          HIDE_TIME_TO_ANSWER: "true"
          HIDE_TIME_TO_FIRST_RESPONSE: "true"
          REPORT_TITLE: "Sprint metrics - ${{ env.biweekly_period }}"
          SEARCH_QUERY: "repo:bcgov/wps is:issue closed:${{ env.biweekly_period }}"

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        if: ${{ env.skip_run != 'true' }}
        with:
          title: Sprint metrics report
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
