# Pipeline for Pull Requests
#
# Lint, Unit Test, Build, Deploy and Cleanup
#
name: Pipeline - Pull Request

on:
  pull_request:
    types:
      [opened, reopened, synchronize, closed]

jobs:
  lint-and-test:
    name: Lint and Unit Test
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run test:ci

  build-and-deploy:
    name: Build and Deploy from Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Variables
        shell: bash
        run: |
          echo -e "\n\n--- Environment Variables ---\n"
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          
          echo -e "\n\n--- Workflow (Custom) Variables ---\n"
          echo "::set-env name=SUFFIX::pr-${{ github.event.number }}"
          echo "SUFFIX: pr-${{ github.event.number }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Builds
        if: github.event.pull_request.state == 'open'
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: GIT_BRANCH=${GITHUB_HEAD_REF} openshift/scripts/oc_build.sh ${SUFFIX} apply

      - name: Deploy
        if: github.event.pull_request.state == 'open'
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: openshift/scripts/oc_deploy.sh ${SUFFIX} apply

      - name: Cleanup
        if: github.event.pull_request.state == 'closed'
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: openshift/scripts/oc_cleanup.sh ${SUFFIX} apply