name: Post Merge Integration

on:
  push:
    branches:
      - main

jobs:
  lint-and-test-api:
    name: Python - Lint, Test with coverage
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.10.4]
        R: ["4.1.2"]
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # For sonar-scanner to work properly we can't use a shallow fetch.
          fetch-depth: 0
      - name: Setup Python ${{ matrix.python-version }} (api)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache poetry installer
        uses: actions/cache@v3
        id: cache-poetry-installer
        env:
          cache-name: cache-poetry-installer
        with:
          path: "~/poetry_installer"
          key: "poetry-installer-1.2.1"
      - name: Download poetry installer
        if: steps.cache-poetry-installer.outputs.cache-hit != 'true'
        run: |
          echo
          mkdir ~/poetry_installer
          curl -sSL https://install.python-poetry.org > ~/poetry_installer/install-poetry.py
      - name: Install poetry (api)
        run: |
          cd ~/poetry_installer
          python install-poetry.py --version 1.2.1
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
      # poetry cache folder: /home/runner/.cache/pypoetry
      - name: Cache poetry
        uses: actions/cache@v3
        env:
          cache-name: cache-poetry
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-cache-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-cache-
      - name: Install python dependencies using poetry (api)
        working-directory: ./api
        run: |
          poetry install
      - name: Install ubuntu pre-requisites (api)
        # The python gdal and R component relies on libgdal-dev being installed.
        # The api uses wkhtmltopdf to generate pdf's.
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install libgdal-dev wkhtmltopdf
      - name: Install gdal python (api)
        # We don't have much control over what version of gdal we're getting, it's pretty much whatever is
        # available to us. As such, gdal is not installed by poetry, since the version will differ between
        # platforms.
        # Also have to be absolutely sure that numpy is installed before gdal (otherwise gdal doesn't install
        # correctly, and you'll run into ndarray errors.)
        # On ubuntu20.04, the most recent we have is gdal, so we use pygdal to install it. (used to use
        # gdal, but it now has a bug that causes it to fail to install on ubuntu20.04)
        working-directory: ./api
        run: |
          poetry run python -m pip install numpy
          poetry run python -m pip install gdal==$(gdal-config --version)
      - name: Lint (api)
        # We used to be able to do linting before installing gdal, but it's not possible anymore.
        # We can however place it ahead of the R installs.
        working-directory: ./api
        run: |
          poetry run pylint --rcfile=.pylintrc app/*.py app/**/*.py
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - name: Cache renv (api)
        # You have to create the renv.lock file on your local machine
        # install.packages("renv")
        # renv::install("cffdrs", dependencies = TRUE)
        # renv::snapshot()
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore R packages
        working-directory: ./r
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Unit Test with coverage (api)
        working-directory: ./api
        run: |
          export LD_LIBRARY_PATH=$(poetry run python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}
          export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/$LD_PRELOAD
          export CLASSPATH=./libs/REDapp_Lib.jar:./libs/WTime.jar:./libs/hss-java.jar:$CLASSPATH
          export ORIGINS=testorigin
          poetry run coverage run --source=app -m pytest -o log_cli=true --disable-warnings -vvv --log-level=DEBUG
      - name: Create coverage report (api)
        working-directory: ./api
        shell: bash
        run: |
          poetry run coverage report
          poetry run coverage xml -o coverage-reports/coverage-report.xml
      - name: Archive coverage report (api)
        uses: actions/upload-artifact@v3
        with:
          name: api-coverage-report
          path: ./api/coverage-reports/coverage-report.xml
  lint-and-test-web:
    name: Web - Lint, Test with coverage
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # For sonar-scanner to work properly we can't use a shallow fetch.
          fetch-depth: 0
      - name: Setup kernel for react, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install node dependencies (web)
        working-directory: ./web
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Lint (web)
        working-directory: ./web
        run: yarn run lint
      # "Error: ENOSPC: System limit for number of file watchers reached" can be addressed
      # with this: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details
      # It seems unnecessary at the moment because tests pass anyway
      - name: Cypress tests with coverage (web)
        working-directory: ./web
        run: yarn run cypress:ci
      - name: Unit tests (web)
        working-directory: ./web
        run: yarn run coverage:ci
      - name: Merge and finalize test coverage (web)
        working-directory: ./web
        run: yarn run finalizeCoverage

      - name: Archive coverage report (web)
        uses: actions/upload-artifact@v3
        with:
          name: web-coverage-report
          path: ./web/finalCoverage
  upload-code-coverage:
    name: Coverage with CodeCov
    runs-on: ubuntu-22.04
    needs: [lint-and-test-web, lint-and-test-api]
    steps:
      # we need to checkout, so that we have codecov.yml
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          # we want to ensure code coverage is good, so we fail on error. (default is false)
          fail_ci_if_error: true
