name: Post Merge Integration

on:
  push:
    branches:
      - main

jobs:
  lint-api:
    name: Lint (api)
    uses: ./.github/workflows/.poetry_and_r.yml
    with:
      poetry_command: poetry run ruff app/*.py app/**/*.py
      working_directory: ./api
      setup_r: false
      upload_coverage: false
  test-api:
    name: Python - Test with coverage
    uses: ./.github/workflows/.poetry_and_r.yml
    with:
      poetry_command: |
        export LD_LIBRARY_PATH=$(poetry run python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}
        export CLASSPATH=./libs/REDapp_Lib.jar:./libs/WTime.jar:./libs/hss-java.jar:$CLASSPATH
        export ORIGINS=testorigin
        export SFMS_SECRET=secret
        poetry run coverage run --source=app -m pytest app/tests -x -o log_cli=true --disable-warnings -vvv
      working_directory: ./api
      setup_r: true
      upload_coverage: true

  lint-and-test-web:
    name: Web - Lint, Test with coverage
    uses: ./.github/workflows/.web.yml

  upload-code-coverage:
    name: Coverage with CodeCov
    runs-on: ubuntu-22.04
    needs: [lint-and-test-web, test-api]
    steps:
      # we need to checkout, so that we have codecov.yml
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          # we want to ensure code coverage is good, so we fail on error. (default is false)
          fail_ci_if_error: true
