name: DEV

on:
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    name: Lint and Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm run test:ci

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        shell: bash
        run: |
          echo "::set-env name=SUFFIX::pr-${{ github.event.number }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: GIT_BRANCH=${GITHUB_HEAD_REF} openshift/scripts/oc_build.sh ${SUFFIX} apply

      - name: Deploy to Dev
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: openshift/scripts/oc_deploy.sh ${SUFFIX} apply
