approvedGitRepositories:
  - "https://github.com/cffdrs/cffdrs_ts.git"

enableScripts: false

nodeLinker: node-modules

packageExtensions:
  "@sentry/vite-plugin@*":
    peerDependencies:
      rollup: "*"
